navikt/familie-ef-sak

pom.xml

Lagt til sonarcloud i pom og oppdatert secrets i Github

Sonarcloud

---

.github/workflows/deploy-prod.yml

Deploy til prod

---

src/main/kotlin/no/nav/familie/ef/sak/api/PersonInfoController.kt
src/test/kotlin/no/nav/familie/ef/sak/config/FamilieIntegrasjonerMock.kt

Små endringer - legg til @PersontilgangConstraint - fix bug. 
Legg til mulighet for mock av "ikketilgang" i utviklingsmiljø

Legg på @PersontilgangConstraint og mock med ikketilgang

---

src/main/kotlin/no/nav/familie/ef/sak/api/dto/PersonopplysningerDto.kt
src/main/kotlin/no/nav/familie/ef/sak/api/dto/SakSøkDto.kt
src/main/kotlin/no/nav/familie/ef/sak/api/gui/PersonopplysningerController.kt
src/main/kotlin/no/nav/familie/ef/sak/api/gui/SakSøkController.kt
src/main/kotlin/no/nav/familie/ef/sak/integration/dto/pdl/PdlPerson.kt
src/main/kotlin/no/nav/familie/ef/sak/service/PersonopplysningerService.kt
src/main/kotlin/no/nav/familie/ef/sak/service/SakSøkService.kt
src/test/kotlin/no/nav/familie/ef/sak/config/PdlClientConfig.kt
src/test/kotlin/no/nav/familie/ef/sak/integration/PdlClientTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/PersonopplysningerServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/SakSøkServiceTest.kt
src/test/resources/json/søker_kort.json

Endret om slik header-api(saksøk) og personopplysninger mottsvarar det som kreves av frontend 
Felt fra SakSøkDto er flyttet til PersonopplysningerDto

Personopplysninger api

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/api/dto/PersonopplysningerDto.kt
src/main/kotlin/no/nav/familie/ef/sak/config/IntegrasjonerConfig.kt
src/main/kotlin/no/nav/familie/ef/sak/integration/FamilieIntegrasjonerClient.kt
src/main/kotlin/no/nav/familie/ef/sak/integration/dto/EgenAnsatt.kt
src/main/kotlin/no/nav/familie/ef/sak/integration/dto/pdl/PdlPersonUtil.kt
src/main/kotlin/no/nav/familie/ef/sak/service/PersonopplysningerService.kt
src/test/kotlin/no/nav/familie/ef/sak/config/FamilieIntegrasjonerMock.kt
src/test/kotlin/no/nav/familie/ef/sak/config/PdlClientConfig.kt
src/test/kotlin/no/nav/familie/ef/sak/service/PersonopplysningerServiceTest.kt

Tagit inn kotlin coroutines 
Avhengig av https://github.com/navikt/familie-integrasjoner/pull/124

Lagt in henting av egenAnsatt og navn til personer tilkoblet søkeren

---

src/main/kotlin/no/nav/familie/ef/sak/api/dto/Felles.kt
src/main/kotlin/no/nav/familie/ef/sak/api/dto/Overgangsstønad.kt
src/main/kotlin/no/nav/familie/ef/sak/mapper/OvergangsstønadMapper.kt
src/main/kotlin/no/nav/familie/ef/sak/service/OvergangsstøandService.kt

En del av https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1302

Overgangsstonad stonadsperiode

---

src/main/kotlin/no/nav/familie/ef/sak/service/BehandlingService.kt
src/test/kotlin/no/nav/familie/ef/sak/service/steg/StegServiceTest.kt

Har byttet ut persist og save med insert/update.

Bugfix: Oppdater repository-metoder

---

src/main/kotlin/no/nav/familie/ef/sak/api/fagsak/FagsakController.kt
src/main/kotlin/no/nav/familie/ef/sak/validering/Behandlingstilgang.kt
src/main/kotlin/no/nav/familie/ef/sak/validering/FagsakPersontilgang.kt
src/main/kotlin/no/nav/familie/ef/sak/validering/FagsakPersontilgangConstraint.kt
src/main/kotlin/no/nav/familie/ef/sak/validering/Persontilgang.kt
src/test/kotlin/no/nav/familie/ef/sak/OppslagSpringRunnerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/api/fagsak/FagsakControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/api/gui/VurderingControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/BehandlingRepositoryTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/FagsakRepositoryTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/InsertUpdateRepositoryImplTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/OppgaveRepositoryTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/RepositoryTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/SøknadRepositoryTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/VilkårVurderingRepositoryTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/FagsakServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/KodeverkServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/steg/StegServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/økonomi/TilkjentYtelseRepositoryTest.kt

Har brukt samme struktur som tidligere, men frykter at vi ender opp med en hel haug med "Constraints" - er dette et bra pattern eller burde personIdent-sjekken løses i selve koden? Det trenger vi vel på omtrent samtlige kall?

Sjekk tilgang til bruker mfor uthenting av fagsak

---

src/main/kotlin/no/nav/familie/ef/sak/api/journalføring/JournalføringController.kt
src/main/kotlin/no/nav/familie/ef/sak/api/journalføring/JournalføringResponse.kt
src/main/kotlin/no/nav/familie/ef/sak/config/PdlConfig.kt
src/main/kotlin/no/nav/familie/ef/sak/integration/PdlClient.kt
src/main/kotlin/no/nav/familie/ef/sak/integration/dto/pdl/PdlPersonRequest.kt
src/main/kotlin/no/nav/familie/ef/sak/integration/dto/pdl/PdlPersonRequestVariables.kt
src/main/resources/pdl/aktor_ident.graphql
src/main/resources/pdl/hent_ident.graphql
src/test/kotlin/no/nav/familie/ef/sak/api/journalføring/JournalføringControllerTest.kt

hentJournalPost sender med personIdent i tillegg til journalposten.

hentJournalpost sender med personident

---

src/main/kotlin/no/nav/familie/ef/sak/api/avstemming/AvstemmingController.kt
src/main/kotlin/no/nav/familie/ef/sak/api/avstemming/GrensesnittavstemmingDto.kt
src/main/kotlin/no/nav/familie/ef/sak/integration/OppdragClient.kt
src/main/kotlin/no/nav/familie/ef/sak/service/AvstemmingService.kt
src/main/kotlin/no/nav/familie/ef/sak/service/TilkjentYtelseService.kt
src/main/kotlin/no/nav/familie/ef/sak/task/GrensesnittavstemmingPayload.kt
src/main/kotlin/no/nav/familie/ef/sak/task/GrensesnittavstemmingTask.kt
src/main/kotlin/no/nav/familie/ef/sak/økonomi/UtbetalingsoppdragGenerator.kt
src/test/kotlin/no/nav/familie/ef/sak/task/GrensesnittavstemmingTaskTest.kt

Laget en endrepunkt for att trigge grensesnittavstemming manuellt -> https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-2606
Endre Grensesnittavstemming slik at payloaden blir mer fleksibel og kan håntere flere stønader.

Lager endepunkt for att trigge grensesnittavstemming manuellt.

---

src/main/kotlin/no/nav/familie/ef/sak/api/avstemming/GrensesnittavstemmingDto.kt
src/main/kotlin/no/nav/familie/ef/sak/task/GrensesnittavstemmingTask.kt

Ta triggertid som en LocalDateTime på endepunktet som trigger grensesnittavstemming

Grensesnittavstemming-testfix

---

src/main/kotlin/no/nav/familie/ef/sak/api/dto/InngangsvilkårDto.kt
src/main/kotlin/no/nav/familie/ef/sak/repository/domain/Vilkårsvurdering.kt
src/main/kotlin/no/nav/familie/ef/sak/service/VurderingService.kt
src/test/kotlin/no/nav/familie/ef/sak/service/VurderingServiceTest.kt

Trenger vilkårstype for å returnere vurdering til frontend.
Og en omskrivning av DTO for å dele opp vurderinger og grunnlagsdata
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-2195

Feature/sivilstand legg til vilkårtype

---

src/main/kotlin/no/nav/familie/ef/sak/service/JournalføringService.kt

Svar på https://github.com/navikt/familie-ef-sak/pull/365/files#r525026072 og https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-2971

Fjerne unødvendig try-catch ved uthenting av søknad på journalføringen

---

.github/workflows/deploy-dev.yml

Legger til mulighet for å bygge og deploye valgfri branch til preprod

Legger til workflow dispatch

---

pom.xml

Reverts navikt/familie-ef-sak#423

Revert "Bump spring-cloud-contract-wiremock from 2.2.5.RELEASE to 3.0.0"

---

src/main/kotlin/no/nav/familie/ef/sak/health/InfotrygdFeedHealth.kt
src/main/kotlin/no/nav/familie/ef/sak/integration/InfotrygdFeedClient.kt
src/main/resources/application-dev.yml
src/main/resources/application.yml

Del 1 i
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-3022

Infotrygd feed client

---

src/main/kotlin/no/nav/familie/ef/sak/api/dto/BosituasjonDto.kt
src/main/kotlin/no/nav/familie/ef/sak/api/dto/InngangsvilkårDto.kt
src/main/kotlin/no/nav/familie/ef/sak/api/dto/VilkårsvurderingDto.kt
src/main/kotlin/no/nav/familie/ef/sak/api/gui/VurderingController.kt
src/main/kotlin/no/nav/familie/ef/sak/mapper/BosituasjonMapper.kt
src/main/kotlin/no/nav/familie/ef/sak/repository/domain/Vilkårsvurdering.kt
src/main/kotlin/no/nav/familie/ef/sak/service/VurderingService.kt
src/main/kotlin/no/nav/familie/ef/sak/vurdering/DelvilkårRegler.kt
src/test/kotlin/no/nav/familie/ef/sak/service/VurderingServiceTest.kt

- Legger til DTO for bosituasjon i inngangsvilkår
- Legger til begrunnelsesfelt i `Delvilkår`-objekter
[PR frontend som er avhengig av denne](https://github.com/navikt/familie-ef-sak-frontend/pull/80)

Inngangsvilkår bosituasjon

---

src/main/kotlin/no/nav/familie/ef/sak/api/ekstern/PerioderOvergangsstønadController.kt
src/main/kotlin/no/nav/familie/ef/sak/health/InfotrygdReplikaHealth.kt
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/application.yml

Legger til tilgangskontroll på uthenting av perioder
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-2843
Erstatter https://github.com/navikt/familie-ef-sak/pull/436
Mulig vi må legge til noe liknende når BA skal ha tilgang til dette

Lagt til tilgangskontroll av henting av perioder for arena

---

src/main/kotlin/no/nav/familie/ef/sak/api/dto/MedlemskapDto.kt
src/main/kotlin/no/nav/familie/ef/sak/config/IntegrasjonerConfig.kt
src/main/kotlin/no/nav/familie/ef/sak/integration/FamilieIntegrasjonerClient.kt
src/main/kotlin/no/nav/familie/ef/sak/mapper/MedlemskapMapper.kt
src/main/kotlin/no/nav/familie/ef/sak/service/VurderingService.kt
src/test/kotlin/no/nav/familie/ef/sak/config/FamilieIntegrasjonerMock.kt
src/test/kotlin/no/nav/familie/ef/sak/service/VurderingServiceTest.kt

Legg til unntak fra medl (vi legger bare til unntak med "gyldig vedtak" i denne omgangen). 
Mulig vi skal gjøre med med vedtak som er under vurdering senere. Vi undersøker også om lovvalg er relavant for oss.

Medl grunnlag

---

nais-dev.yaml
nais-prod.yaml
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/application.yml

Hade brukt feil DISCOVERY_URL 
Og fikset slik att den henter sts username/passord fra riktig sted, slik att vi kan slette brukernavn/passord fra våre egne secrets

Sts config

---

src/main/kotlin/no/nav/familie/ef/sak/api/dto/BehandlingHistorikkDto.kt
src/main/kotlin/no/nav/familie/ef/sak/api/gui/BehandlingshistorikkController.kt
src/main/kotlin/no/nav/familie/ef/sak/repository/BehandlingshistorikkRepository.kt
src/main/kotlin/no/nav/familie/ef/sak/repository/domain/Behandlingshistorikk.kt
src/main/kotlin/no/nav/familie/ef/sak/service/BehandlingshistorikkService.kt
src/test/kotlin/no/nav/familie/ef/sak/api/gui/BehandlingshistorikkControllerTest.kt

For å vise utfall og begrunnelse i frontend till hvorfor ett vedtak er underkjent
Endret url
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-3218
https://github.com/navikt/familie-ef-sak-frontend/pull/87

Behandlingshistorikk - Sender med utfall og metadata til frontend

---

.github/workflows/deploy-dev.yml
.github/workflows/integrasjonsTest.yml

* Skal vi bygge for Synchronized?

Ikke bygg for hver push

---

Dockerfile

https://nav-it.slack.com/archives/CJN0STWB0/p1612387453141300

Nais kjører ikke lengre appene med root og RUN chmod crasher

---

src/main/kotlin/no/nav/familie/ef/sak/repository/domain/Vilkårsvurdering.kt
src/main/resources/db/migration/V31__Migrer_eksisterende_vilkårsresultater.sql
src/test/kotlin/no/nav/familie/ef/sak/DatabaseChangesTest.kt
src/test/kotlin/no/nav/familie/ef/sak/api/gui/VurderingControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/VurderingServiceTest.kt

Endrer JA/NEI til OPPFYLT/IKKE_OPPFYLT
Oppdatert med skript som migrerer verdier i databasen fra JA -> OPPFYLT og NEI -> IKKE_OPPFYLT

Refaktorering av vilkaarsresultat

---

src/main/kotlin/no/nav/familie/ef/sak/repository/domain/Vilkårsvurdering.kt
src/main/kotlin/no/nav/familie/ef/sak/vurdering/DelvilkårRegler.kt

Fjernet det ene delvilkåret på samliv :)

Samliv feedback

---

src/main/kotlin/no/nav/familie/ef/sak/api/gui/VedtaksbrevController.kt
src/main/kotlin/no/nav/familie/ef/sak/config/DatabaseConfiguration.kt
src/main/kotlin/no/nav/familie/ef/sak/repository/domain/Fil.kt
src/main/kotlin/no/nav/familie/ef/sak/repository/domain/Vedtaksbrev.kt
src/main/kotlin/no/nav/familie/ef/sak/service/VedtaksbrevService.kt
src/main/kotlin/no/nav/familie/ef/sak/service/steg/BeslutteVedtakSteg.kt
src/test/kotlin/ApplicationLocal.kt
src/test/kotlin/ApplicationLocalPostgres.kt
src/test/kotlin/no/nav/familie/ef/sak/OppslagSpringRunnerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/config/BrevClientMock.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/VedtaksbrevRepositoryTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/steg/BeslutteVedtakStegTest.kt

Legger til en mock av BrevClient for bruk i tester.

Legger til brevClientMock

---

src/main/kotlin/no/nav/familie/ef/sak/api/gui/PersonopplysningerController.kt

Trenger denne for å hente info til personlinjen

Ny endepunkt for å hente personopplysninger gitt en fagsakId

---

src/main/kotlin/no/nav/familie/ef/sak/blankett/BlankettClient.kt
src/main/kotlin/no/nav/familie/ef/sak/blankett/BlankettController.kt
src/main/kotlin/no/nav/familie/ef/sak/blankett/BlankettPdfRequest.kt
src/main/kotlin/no/nav/familie/ef/sak/service/PersonopplysningerService.kt
src/main/resources/application-dev.yml
src/main/resources/application.yml
src/test/resources/application-local.yml

En liten del av POC - lag pdf-blankettf: 
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-3674
behandlingsId => pdf.

Enkelt endepunkt for blankett

---

src/main/kotlin/no/nav/familie/ef/sak/blankett/BlankettService.kt
src/test/kotlin/no/nav/familie/ef/sak/OppslagSpringRunnerTest.kt

Legg til lagreTomBlankett når vi oppretter behandling av type blankett

Lag blankettbehandling med tom pdf

---

src/main/kotlin/no/nav/familie/ef/sak/integration/JournalpostClient.kt
src/main/kotlin/no/nav/familie/ef/sak/repository/BehandlingRepository.kt
src/main/kotlin/no/nav/familie/ef/sak/service/steg/BlankettSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/service/steg/StegService.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/BehandlingRepositoryTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/steg/JournalførBlankettStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/steg/StegServiceTest.kt

Har igjen et par TODOs på blankett-steg, men lager PR for første utkast slik at det er enklere å teste i preprod

Første versjon av implementasjon av utfør blankettsteg

---

nais-t4.yaml
src/main/kotlin/no/nav/familie/ef/sak/api/ekstern/PerioderOvergangsstønadController.kt
src/main/kotlin/no/nav/familie/ef/sak/service/PerioderOvergangsstønadService.kt
src/main/resources/application.yml

Og lagt til en endepunkt med azure token validering
Gjør det mulig å teste for oss og få den å virke i t4.. 
https://github.com/navikt/vault-iac/pull/3240

Fikset url til integrasjon som virker i default og t4 namespace

---

src/main/kotlin/no/nav/familie/ef/sak/mapper/BarnMedSamværMapper.kt
src/main/kotlin/no/nav/familie/ef/sak/service/GrunnlagsdataService.kt
src/main/kotlin/no/nav/familie/ef/sak/service/VurderingService.kt
src/test/kotlin/no/nav/familie/ef/sak/service/GrunnlagsdataServiceTest.kt

Sortering av barn feiler nå, siden det sorteres i registergrunnlaget. Flytter sortering til GrunnlagsdataService

Flytter sortering av barn til VurderingService

---

src/main/kotlin/no/nav/familie/ef/sak/config/IntegrasjonerConfig.kt
src/main/kotlin/no/nav/familie/ef/sak/integration/FamilieIntegrasjonerClient.kt
src/main/kotlin/no/nav/familie/ef/sak/service/VedtaksbrevService.kt
src/main/kotlin/no/nav/familie/ef/sak/service/steg/DistribuerVedtaksbrevSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/service/steg/JournalførVedtaksbrevSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/service/steg/StegService.kt
src/main/kotlin/no/nav/familie/ef/sak/task/DistribuerVedtaksbrevTask.kt
src/main/kotlin/no/nav/familie/ef/sak/task/JournalførVedtaksbrevTask.kt
src/test/kotlin/no/nav/familie/ef/sak/service/VedtaksbrevServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/steg/DistribuerVedtaksbrevStegStegTest.kt

[Favro-kort](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-3518)
Får ikke verifisert dette i preprod før ABAC rolletilgang er på plass ref https://jira.adeo.no/browse/ROLLE-48#

Utsending brev

---

src/main/kotlin/no/nav/familie/ef/sak/api/dto/Overgangsstønad.kt
src/main/kotlin/no/nav/familie/ef/sak/mapper/AktivitetMapper.kt
src/test/kotlin/no/nav/familie/ef/sak/mapper/AktivitetMapperTest.kt

Legger ved filtrering på barn med særligeTilsynsbehov og nytt felt datoOppstartJobb i mapping av aktivitet

Aktivitet visning

---

src/main/kotlin/no/nav/familie/ef/sak/api/beregning/VedtakService.kt
src/main/kotlin/no/nav/familie/ef/sak/api/gui/VedtakController.kt
src/test/kotlin/no/nav/familie/ef/sak/api/beregning/VedtakServiceTest.kt

Legger til endepunkt for å hente lagrede vedtak for visning i frontend

Hent vedtak

---

src/main/kotlin/no/nav/familie/ef/sak/api/gui/TestSaksbehandlingController.kt
src/main/kotlin/no/nav/familie/ef/sak/blankett/BlankettSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/repository/BehandlingsjournalpostRepository.kt
src/main/kotlin/no/nav/familie/ef/sak/repository/domain/Behandling.kt
src/main/kotlin/no/nav/familie/ef/sak/repository/domain/Behandlingsjournalpost.kt
src/main/kotlin/no/nav/familie/ef/sak/service/BehandlingService.kt
src/main/kotlin/no/nav/familie/ef/sak/service/JournalføringService.kt
src/main/kotlin/no/nav/familie/ef/sak/service/VedleggService.kt
src/main/kotlin/no/nav/familie/ef/sak/service/steg/JournalførVedtaksbrevSteg.kt
src/test/kotlin/no/nav/familie/ef/sak/OppslagSpringRunnerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/BehandlingsjournalpostRepositoryTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/BehandlingServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/JournalføringServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/VedleggServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/steg/JournalførBlankettStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/steg/JournalførVedtaksbrevStegTest.kt

For å unngå att vi henter unødvendig mye data når vi henter behandling

Splittet ut Behandlingsjournalpost.kt fra Behandling.kt

---

pom.xml

Erstatter:
* https://github.com/navikt/familie-ef-sak/pull/594/files
* https://github.com/navikt/familie-ef-sak/pull/592/files
* https://github.com/navikt/familie-ef-sak/pull/591
* https://github.com/navikt/familie-ef-sak/pull/590
* https://github.com/navikt/familie-ef-sak/pull/571/files
* https://github.com/navikt/familie-ef-sak/pull/570/files

Oppdatert dependencies med versjoner fra dependabot

---

src/main/resources/application-dev.yml
src/main/resources/application.yml

Var ikke helt riktig i https://github.com/navikt/familie-ef-sak/pull/612

Må ha med api:// og .default i scope

---

src/main/kotlin/no/nav/familie/ef/sak/api/beregning/VedtakDto.kt
src/main/kotlin/no/nav/familie/ef/sak/api/beregning/VedtakService.kt
src/main/kotlin/no/nav/familie/ef/sak/blankett/BlankettService.kt
src/test/kotlin/no/nav/familie/ef/sak/api/beregning/VedtakServiceTest.kt

Usikker på hva som er best/mest hensiktsmessig, men tenker at dersom frontend ikke forholder seg til en "dato" - så trenger ikke DTO-en å gjøre det heller? 
Hva tenker dere? Bør vi bruke Year-Month isteden?

Bytt ut dto-verdiene med år og måned istedenfor full dato

---

src/main/kotlin/no/nav/familie/ef/sak/api/gui/FagsakController.kt
src/main/kotlin/no/nav/familie/ef/sak/service/FagsakService.kt

Det var slik det virket tidligere med ble skrevet om i a5cd9f1dd767ec4ecbc8d590f4a3cdd24c5313aa då jeg ikke trodde man burde opprette den

Henting av fagsak skal opprette fagsak hvis den ikke finnes fra før.

---

pom.xml

Erstatter
- https://github.com/navikt/familie-ef-sak/pull/633
- https://github.com/navikt/familie-ef-sak/pull/619
- https://github.com/navikt/familie-ef-sak/pull/618
- https://github.com/navikt/familie-ef-sak/pull/616
- https://github.com/navikt/familie-ef-sak/pull/615
- https://github.com/navikt/familie-ef-sak/pull/605

Oppgraderer avhengigheter

---

src/main/kotlin/no/nav/familie/ef/sak/api/beregning/Beregning.kt
src/main/kotlin/no/nav/familie/ef/sak/api/beregning/BeregningController.kt
src/main/kotlin/no/nav/familie/ef/sak/api/beregning/BeregningRequest.kt
src/main/kotlin/no/nav/familie/ef/sak/api/beregning/BeregningService.kt
src/main/kotlin/no/nav/familie/ef/sak/api/beregning/VedtakDto.kt
src/main/kotlin/no/nav/familie/ef/sak/api/beregning/VedtakService.kt
src/main/kotlin/no/nav/familie/ef/sak/blankett/BlankettService.kt
src/main/kotlin/no/nav/familie/ef/sak/service/steg/BeregnYtelseSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/service/steg/StegService.kt
src/main/kotlin/no/nav/familie/ef/sak/util/Periode.kt
src/main/kotlin/no/nav/familie/ef/sak/vurdering/medlemskap/MedlemskapRegelsett.kt
src/main/kotlin/no/nav/familie/ef/sak/vurdering/medlemskap/Medlemskapshistorikk.kt
src/test/kotlin/no/nav/familie/ef/sak/api/beregning/BeregningServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/api/beregning/BeregningTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/VedtakRepositoryTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vurdering/medlemskap/MedlemskapshistorikkTest.kt

Gitt innteksperioder med samordningsfradrag og vedtaksperioder og ska `beregnYtelse` returnere en liste med beløp og perioder utifrån denne formel 
((2,25grunnbeløpet - 0,45(inntekt - 0,5grunnbeløpet)/12) - samordningsfradrag

Beregning av stønad 

---

.github/workflows/build-dev.yml
src/main/kotlin/no/nav/familie/ef/sak/api/beregning/VedtakDto.kt
src/main/kotlin/no/nav/familie/ef/sak/api/beregning/VedtakService.kt
src/main/kotlin/no/nav/familie/ef/sak/api/beregning/VedtaksperiodeDto.kt
src/main/kotlin/no/nav/familie/ef/sak/blankett/BlankettService.kt
src/main/kotlin/no/nav/familie/ef/sak/config/ApplicationConfig.kt
src/main/kotlin/no/nav/familie/ef/sak/repository/domain/Vedtak.kt
src/main/kotlin/no/nav/familie/ef/sak/service/steg/BeregnYtelseSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/service/steg/VedtaBlankettSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/util/ObjectMapperProvider.kt
src/main/resources/db/migration/V44__avslåbegrunnelse_vedtak_tabell.sql
src/test/kotlin/no/nav/familie/ef/sak/DatabaseChangesTest.kt
src/test/kotlin/no/nav/familie/ef/sak/api/beregning/BeregningControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/api/beregning/VedtakServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/steg/VedtaBlankettStegTest.kt

[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-4460)

Avslå søknad i blankett-modus

---

.github/workflows/build-dev.yml
.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml

Github skal fase ut deres (docker) "Package Registry (GPR)" til fordel for deres "GitHub Container Registry (GHCR)".
https://nav-it.slack.com/archives/C01DE3M9YBV/p1613039240045100

Tar i bruk ghcr

---

pom.xml

Erstatter 
- https://github.com/navikt/familie-ef-sak/pull/671
- https://github.com/navikt/familie-ef-sak/pull/670
- https://github.com/navikt/familie-ef-sak/pull/669
- https://github.com/navikt/familie-ef-sak/pull/668
- https://github.com/navikt/familie-ef-sak/pull/667
- https://github.com/navikt/familie-ef-sak/pull/657
- https://github.com/navikt/familie-ef-sak/pull/648
- https://github.com/navikt/familie-ef-sak/pull/647
- https://github.com/navikt/familie-ef-sak/pull/645

Dependabot oppdateringer

---

src/main/kotlin/no/nav/familie/ef/sak/api/dto/DokumentinfoDto.kt
src/main/kotlin/no/nav/familie/ef/sak/service/VedleggService.kt

Legg på klokkeslett bak datoen så blir det enkelt for saksbehandler å identifisere om dokumenter har kommen inn samtidig.

Tea-4578: Skal vise klokkslettet for innsendingen av dokument

---

src/main/kotlin/no/nav/familie/ef/sak/api/gui/VedtaksbrevController.kt

Fjern gammelt endepunk som ikke skal bruker og ta bort unødvendig nullsjekk.

Ta bort unødvendig null sjekk

---

src/test/kotlin/no/nav/familie/ef/sak/service/steg/FerdigstillBehandlingStegTest.kt

Minipirk - etter siste merge ;)

Forslag til litt bedre "testbeskrivelse"?

---

pom.xml

For å bedre håndtere optimistic lock exception

Oppdaterer prosessering

---

src/main/kotlin/no/nav/familie/ef/sak/regler/RegelId.kt

favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-5136
@alexandraback Om jeg skjønner riktig så regelId er spørsmål fra sak-frontend?

endrer samlivsbrudd til samlivsbruddet

---

src/main/kotlin/no/nav/familie/ef/sak/api/dto/FagsakDto.kt
src/main/kotlin/no/nav/familie/ef/sak/iverksett/SimuleringService.kt
src/main/kotlin/no/nav/familie/ef/sak/repository/TilkjentYtelseRepository.kt
src/main/kotlin/no/nav/familie/ef/sak/service/BehandlingService.kt
src/main/kotlin/no/nav/familie/ef/sak/service/FagsakService.kt
src/main/kotlin/no/nav/familie/ef/sak/service/TilkjentYtelseService.kt
src/test/kotlin/no/nav/familie/ef/sak/iverksett/SimuleringServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/økonomi/TilkjentYtelseServiceTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-4918
Litt usikker på om dette er riktig måte å løse den på. Tar gjerne innspill. @charliemidtlyng har sikkert noen tanker?

Skal returnere om en fagsak er løpende eller ikke

---

.deploy/vars-dev.yaml

Kun for dev til å begynne med.

Tillat kall fra ny app familie-ef-personhendelse

---

pom.xml

Erstatter 
- https://github.com/navikt/familie-ef-sak/pull/802
- https://github.com/navikt/familie-ef-sak/pull/800
- https://github.com/navikt/familie-ef-sak/pull/799
- https://github.com/navikt/familie-ef-sak/pull/798
- https://github.com/navikt/familie-ef-sak/pull/779
- https://github.com/navikt/familie-ef-sak/pull/777
- https://github.com/navikt/familie-ef-sak/pull/765
- https://github.com/navikt/familie-ef-sak/pull/757
- https://github.com/navikt/familie-ef-sak/pull/709

Oppdaterer dependencies spring 2.5.4

---

src/main/kotlin/no/nav/familie/ef/sak/api/Feil.kt
src/main/kotlin/no/nav/familie/ef/sak/api/gui/RevurderingsController.kt
src/main/kotlin/no/nav/familie/ef/sak/repository/domain/Behandling.kt
src/main/kotlin/no/nav/familie/ef/sak/service/BehandlingService.kt
src/main/kotlin/no/nav/familie/ef/sak/service/RevurderingService.kt
src/main/kotlin/no/nav/familie/ef/sak/service/SøknadService.kt
src/main/kotlin/no/nav/familie/ef/sak/service/VurderingService.kt
src/main/kotlin/no/nav/familie/ef/sak/util/OpprettBehandlingUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/service/BehandlingServiceIntegrationTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/BehandlingServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/RevurderingServiceIntegrationTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/SøknadServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/VurderingServiceIntegratsjonsTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/steg/FerdigstillBehandlingStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/util/OpprettBehandlingUtilTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-5803
Kopierer over søknad, grunnlagsdata og vurderinger til ny behandling. 
Lagt inn valideringer på opprettelse av ny behandling. Fint om reglene kontrolleres en ekstra gang der! :) 
2 sonarissues, begge er TODO's som vi lagt til i koden

Start revurdering

---

src/main/kotlin/no/nav/familie/ef/sak/service/RevurderingService.kt
src/main/kotlin/no/nav/familie/ef/sak/task/BehandlingsstatistikkTask.kt
src/test/kotlin/no/nav/familie/ef/sak/config/IverksettClientMock.kt

Setter behandlingsstatus og stegtype på revurdering til Utredes/BeregnYtelse. Sett søknadsdato = now() i statistikk for revurdering.

Send motatt/påbegynt statistikk for revurdering. 

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/task/BehandlingsstatistikkTask.kt

Bruk ny kontrakt for BehandlingsstatistikkTask.kt - henvendelseTidspunkt.
Legg til relatert behandlingsid (hvis hendelse != ferdig)

Bruk ny kontrakt for BehandlingsstatistikkTask

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/api/gui/TestSaksbehandlingController.kt
src/main/kotlin/no/nav/familie/ef/sak/blankett/BlankettSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/integration/JournalpostClient.kt
src/main/kotlin/no/nav/familie/ef/sak/service/JournalføringService.kt
src/main/kotlin/no/nav/familie/ef/sak/service/TotrinnskontrollService.kt
src/main/kotlin/no/nav/familie/ef/sak/sikkerhet/SikkerhetContext.kt
src/main/kotlin/no/nav/familie/ef/sak/simulering/SimuleringService.kt
src/test/kotlin/no/nav/familie/ef/sak/integration/JournalpostClientTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/JournalføringServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/steg/JournalførBlankettStegTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-4120
Koblet til https://github.com/navikt/familie-integrasjoner/pull/460
Nå i dev vises bare "fam" i, noe koblet til att AD i test ikke gir noe spennende

Sender med saksbehandlerident til dokarkiv

---

src/main/kotlin/no/nav/familie/ef/sak/vilkår/VurderingController.kt

Co-authered-by:Eirik Arseth <eirik.arseth@nav.no>

Minipr: Flytt VurderingController.kt til vilkår

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/brev/BrevClient.kt
src/main/kotlin/no/nav/familie/ef/sak/brev/FrittståendeBrevController.kt
src/main/kotlin/no/nav/familie/ef/sak/brev/FrittståendeBrevService.kt
src/main/kotlin/no/nav/familie/ef/sak/brev/dto/FrittståendeBrevDto.kt
src/main/kotlin/no/nav/familie/ef/sak/iverksett/IverksettClient.kt
src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/IverksettClientMock.kt

Utsending av frittstående brev. Venter på frontend og iverksett for å teste denne.

Utsending av frittstående brev

---

src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdReplikaClient.kt
src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdService.kt
src/test/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdPeriodeUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/service/InfotrygdServiceTest.kt

Pre-work for https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-5800
Legger også til endepunkt for å kunne hente ut periodene til frontend

Legger til funksjonalitet for å hente perioder fra replika

---

README.md
pom.xml
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/config/DatabaseConfiguration.kt
src/main/kotlin/no/nav/familie/ef/sak/simulering/DbMigreringService.kt
src/main/kotlin/no/nav/familie/ef/sak/simulering/SimuleringService.kt
src/main/kotlin/no/nav/familie/ef/sak/simulering/Simuleringsresultat.kt
src/main/kotlin/no/nav/familie/ef/sak/simulering/SimuleringsresultatDto.kt
src/main/kotlin/no/nav/familie/ef/sak/simulering/SimuleringsresultatRepository.kt
src/main/resources/db/migration/V62__beriket_simuleringsresultat.sql
src/test/kotlin/no/nav/familie/ef/sak/iverksett/SimuleringBeriketDbMigreringTest.kt
src/test/kotlin/no/nav/familie/ef/sak/iverksett/SimuleringServiceTest.kt

Første steg for å hente beriket simulering fra ef-iverksett

Migering for å legge til beriket simuleringsresultat. 

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/OpprettBehandlingUtil.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/RevurderingService.kt
src/test/kotlin/no/nav/familie/ef/sak/felles/util/OpprettBehandlingUtilTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/RevurderingServiceIntegrationTest.kt

Skal kunne opprette en revurdering der forrige behandling er avslått. Hvis det finnes en forrige behandling som er iverksatt, så brukes søknaden til den, hvis ikke så bruker vi avslådde behandlingen sin søknad
med @charliemidtlyng og @ViktorGSolberg 
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-6702

Revurdering etter avslått behandling

---

src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/SøkService.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/dto/Søkeresultat.kt
src/test/kotlin/no/nav/familie/ef/sak/service/SøkServiceTest.kt

Henger sammen med [denne PRen](https://github.com/navikt/familie-ef-sak-frontend/pull/576) frontend.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-4918).

Legg erLøpende på søkeresultat

---

src/main/resources/db/migration/V70__konsistensavstemming_tidsplan_2022.sql

Dette er det jeg fått fra økonomi, skal sjekke hvorfor vi får 2 datoer i januar og 0 i desember

Lagt inn datoer for konsistensavstemming for 2022

---

src/main/kotlin/no/nav/familie/ef/sak/vedlegg/DokumentinfoDto.kt
src/main/kotlin/no/nav/familie/ef/sak/vedlegg/VedleggService.kt

Løser [denne oppgaven](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7051).
Hører til [denne frontend-PRen](https://github.com/navikt/familie-ef-sak-frontend/pull/671).

Legg til journalstatus på dokumenter

---

src/main/kotlin/no/nav/familie/ef/sak/arbeidsfordeling/ArbeidsfordelingService.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/config/CacheConfig.kt
src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveService.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/GrunnlagsdataHenterService.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/GrunnlagsdataRegisterService.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/GrunnlagsdataService.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/PersonopplysningerService.kt
src/test/kotlin/no/nav/familie/ef/sak/service/ArbeidsfordelingServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/GrunnlagsdataServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/OppgaveServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/PersonopplysningerServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/VilkårGrunnlagServiceTest.kt

Skulle fikse caching av oppgavemappe som ikke virker når man kaller en `@cacheable` metode fra samma klasse.
Tok å la til cacheable på noen andre metoder og
For å unngå att alle `@cacheable` metoder skal ut i egen klasse så la jeg til
return cacheManager.get("navEnhet", ident) {
som egentlige gjør det samme som `@Cacheable` (men veldig forenklet)

Fikser bruk av cache, samt legger til cache

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SendTilBeslutterSteg.kt
src/test/kotlin/no/nav/familie/ef/sak/api/gui/VedtakControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SendTilBeslutterStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt

Løser favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7232
Fordi vi ikke resetter state ved redigering (kun ved sletting) av vilkår må vi validere ved innsending.
Nå vil vi validere at:
* Hvis innvilget må alle vilkårsvurderinger være behandlet og ha resultat "Oppfylt"

Legg til "innvilget" tilstands-validering når vi sender til beslutter.

---

src/main/kotlin/no/nav/familie/ef/sak/vedtak/domain/Vedtak.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakDto.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/VurderingStegService.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/regler/evalutation/OppdaterVilkår.kt
src/main/resources/db/migration/V72__avslagsarsak_vedtak_og_beregning.sql
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/BeregningControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vilkår/regler/evalutation/OppdaterVilkårTest.kt

Man skal kunne avslå vedtak selv om ikke alle vilkår er vurdert. Dersom det ikke er noen vilkår som ikke er oppfylt ved avslag må saksbehandler derfor velge en årsak. Årsak legges derfor til på Vedtak. Løser følgende kort: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7103

Logikk ved avslag

---

.github/workflows/build-dev.yml
.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
Dockerfile
pom.xml

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7390

Oppdaterer til Jdk17

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BehandlingSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/StegService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/VentePåTekniskOpphørStatus.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingshistorikk/domain/Behandlingshistorikk.kt
src/main/kotlin/no/nav/familie/ef/sak/beregning/BeregningRequest.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/SøkService.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/config/SwaggerDocumentationConfig.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/exception/Feil.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/sikkerhet/TilgangInterceptor.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/mapper/BarnMedSamværMapper.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/regler/vilkår/SivilstandRegel.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseStegTest.kt

Prøvd å splittet opp i flere commits

Rydder opp i warnings i koden

---

src/main/kotlin/no/nav/familie/ef/sak/vedtak/uttrekk/UttrekkArbeidssøkerRepository.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/uttrekk/UttrekkArbeidssøkerService.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/uttrekk/UttrekkController.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/uttrekk/UttrekkArbeidssøkerRepositoryTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/uttrekk/UttrekkArbeidssøkerServiceTest.kt

Fortsetting på https://github.com/navikt/familie-ef-sak/pull/1004

Uttrekk arbeidssøkere paginering

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/RevurderingService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/domain/Fagsak.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/PdlClient.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/pdl/PdlPerson.kt
src/main/kotlin/no/nav/familie/ef/sak/simulering/SimuleringService.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/iverksett/SimuleringServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/FagsakServiceTest.kt
src/test/resources/application-integrasjonstest.yaml

Vi kan ikke merge denne før oppdrag synkroniserer personidenter. 
Frykten min er TilkjentYtelse og bruken av personIdent der. Vil det kunne ødelegge for oss senere? Konsistensavstemming? Denne sendes iallefall ikke til iverksett, men brukes litt internt i `ef-sak`

Synkronisere personident

---

src/main/kotlin/no/nav/familie/ef/sak/vedtak/VedtakHistorikkBeregner.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/AndelHistorikkBeregnerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/VedtakHistorikkBeregnerTest.kt
src/test/resources/økonomi/opphør.csv
src/test/resources/økonomi/opphør_midt_i_periode.csv

Skal håndtere vedtak som er av typen opphør

Vedtakshistorikk opphør

---

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/arbeidssøker/ArbeidssøkerClient.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/arbeidssøker/ArbeidssøkerResponse.kt

Fant noen småfeil. Men får fortsatt ikke kjørt jobbet helt pga noe rart i API'et som timear ut. Har sendt melding til de som er ansvarlige for API'et

Feilfiks arbeidssøker personident

---

src/main/kotlin/no/nav/familie/ef/sak/amelding/InntektController.kt
src/main/kotlin/no/nav/familie/ef/sak/amelding/InntektService.kt
src/main/kotlin/no/nav/familie/ef/sak/amelding/ekstern/AMeldingInntektClient.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/dto/BehandlingDto.kt
src/test/kotlin/no/nav/familie/ef/sak/amelding/AMeldingInntektControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/InntektClientMock.kt

Legger til endepunkt for å kalle a-inntekt via proxy, for å generere url til a-inntekt,  
Trengs før https://github.com/navikt/familie-ef-sak-frontend/pull/727 merges
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7485

Frontend kan ikke kalle a-inntekt direkte pga CSP

---

src/test/kotlin/no/nav/familie/ef/sak/api/gui/VedtakControllerTest.kt

Test: Send behandling til beslutter med resultat innvilge.
Hvis _alle_ vurderinger er oppfylt skal det gå bra
Hvis noen vurderinger mangler eller ikke er oppfylt skal vi få en riktig frontendfeilmelding.

Vedtak legg til innvilget test

---

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/arbeidssøker/ArbeidssøkerResponse.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/uttrekk/UttrekkArbeidssøkerService.kt

https://nav-it.slack.com/archives/G012YEK9YQ1/p1641207086003900

Arbeidssøkerresponse kan inneholde nullable tilOgMedDato

---

src/main/kotlin/no/nav/familie/ef/sak/vedtak/uttrekk/OpprettUttrekkArbeidssøkerTask.kt
src/main/resources/db/migration/V78__uttrekk_arbeidssøkere_slett_task.sql

Sletter task som ble opprettet for februar. Denne tasken skal opprettes fra tasken som kjøres i januar

Sletter opprettelse av task.

---

pom.xml

Erstatter:
- https://github.com/navikt/familie-ef-sak/pull/1064
- https://github.com/navikt/familie-ef-sak/pull/1063
- https://github.com/navikt/familie-ef-sak/pull/1062
- https://github.com/navikt/familie-ef-sak/pull/1061

Dependabot oppdateringer 20220103-105825

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/FerdigstillBehandlingSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingshistorikk/BehandlingshistorikkController.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingshistorikk/BehandlingshistorikkService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingshistorikk/domain/Behandlingshistorikk.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingshistorikk/dto/HendelseshistorikkDto.kt
src/test/kotlin/no/nav/familie/ef/sak/api/gui/BehandlingshistorikkControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/BehandlingshistorikkServiceTest.kt

Løser punktene under "utbedringer" i [denne oppgaven](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7359)

Hendelseshistorikk utbedringer

---

src/main/resources/application-dev.yml
src/main/resources/application.yml

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7659

Tar i bruk Q1 i dev

---

src/main/kotlin/no/nav/familie/ef/sak/blankett/BlankettPdfRequest.kt
src/main/kotlin/no/nav/familie/ef/sak/blankett/BlankettService.kt

https://nav-it.slack.com/archives/C01087QRJ2U/p1641986959033400?thread_ts=1641477798.006500&cid=C01087QRJ2U
* https://github.com/navikt/familie-ef-blankett/pull/55

Sender med årsak til behandling til saksbehandlerblankett

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdController.kt
src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdPerioderDto.kt
src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdService.kt
src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InternPeriode.kt
src/main/kotlin/no/nav/familie/ef/sak/infotrygd/PeriodeService.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/GrunnlagsdataRegisterService.kt
src/test/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdPeriodeParser.kt
src/test/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdPeriodeTestUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdPeriodeUtilTest.kt
src/test/kotlin/no/nav/familie/ef/sak/infotrygd/PeriodeServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/InfotrygdReplikaMock.kt

Det er ønskelig å vise vedtaksperioder fra infotrygd
Avhengig av:
* https://github.com/navikt/familie-kontrakter/pull/465

Infotrygd perioder controller

---

.deploy/vars-prod.yaml

NB: Ikke merge denne PR-en før kl 14:00

endret clusteren til prod-gcp for familie-ba-sak

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/MigreringService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/TestSaksbehandlingController.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/MigreringController.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/dto/MigreringInfo.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/MigreringServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdPeriodeTestUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/InfotrygdReplikaMock.kt
src/test/kotlin/no/nav/familie/ef/sak/service/GrunnlagsdataServiceTest.kt

Legger til mulighet for å hente ut litt metadata om hvordan migreringen kommer tolkes.
Samt mulighet for å trigge migrering fra frontend
* https://github.com/navikt/familie-ef-sak-frontend/pull/798
* https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7649

Migrering - metadata om migrering og trigge migrering fra frontend

---

src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdService.kt

Randomsortering nå, fint hvis disse blir sortert til frontend :)

Returnerer infotrygdsaker sortert på mottatt dato

---

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/ereg/EregDomene.kt
src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/EregClientMock.kt
src/test/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/ereg/EregClientTest.kt

Endepunktet vi går mot returnerer ikke virksomhetDetaljer. Se https://modapp-q1.adeo.no/ereg/api/swagger-ui.html#/organisasjon.v1/hentOrganisasjonUsingGET

Fjerner virksomhetDetaljer fra OrganisasjonDto

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/beregning/BeregningController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt

Fjerner:
"familie.ef.sak.innvilge-med-opphoer",
"familie.ef.sak.endringslogg",

Slett toggles som er enablet i prod

---

src/main/kotlin/no/nav/familie/ef/sak/fagsak/SøkService.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/dto/Søkeresultat.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7899
Litt av en quick-fix, vi kommer skrive om henting og visning av fagsak senere, men var ønskelig å få inn denne nå
* https://github.com/navikt/familie-ef-sak-frontend/pull/848

Sender med erMigrert til frontend på søk

---

src/main/kotlin/no/nav/familie/ef/sak/vedtak/VedtakController.kt
src/main/resources/application.yml

Gjorde et testkall i preprod med dato, og det ser ut til å virke

Erstatter datetimeformat med spring properties

---

src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakPersonController.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakPersonRepository.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakPersonService.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakRepository.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/SøkController.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/SøkService.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/domain/Fagsak.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/dto/FagsakDto.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/dto/FagsakPersonDto.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/dto/Søkeresultat.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/sikkerhet/TilgangService.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/PersonopplysningerController.kt
src/test/kotlin/no/nav/familie/ef/sak/api/gui/SøkControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/fagsak/FagsakPersonControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/fagsak/FagsakPersonRepositoryTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/TilgangServiceTest.kt

Lagt til endepunkter for å hente informasjon koblet til personen, koblet til det nye overbygget
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7770

FagsakPerson endepunkter

---

src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdService.kt
src/test/kotlin/no/nav/familie/ef/sak/service/InfotrygdServiceTest.kt

Er til visning av saker i frontend
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7926

Skal sortere saker fra infotrygd by vedtaksdato desc, mottattdato desc

---

pom.xml

Erstatter:
* https://github.com/navikt/familie-ef-sak/pull/1134
* https://github.com/navikt/familie-ef-sak/pull/1116
* https://github.com/navikt/familie-ef-sak/pull/1115
* https://github.com/navikt/familie-ef-sak/pull/1114

Dependabot 20220208 072515

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt

Co-authored-by: Eirik Aarseth <eirik.arseth@nav.no>

Legg til toggle - vis lag manuel tilbakekreving

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt

* https://github.com/navikt/familie-ef-sak-frontend/pull/880

Legger til featuretoggle for migrering fra oppgavebenken

---

src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseStegTest.kt

Gjør dette i egen PR før jeg legger til nye tester for opphør

Bruker fellesmetoder for å få enklere tester i BeregnYtelseSteg

---

src/main/kotlin/no/nav/familie/ef/sak/metrics/MålerService.kt

https://micrometer.io/docs/concepts#_gauges
https://nav-it.slack.com/archives/C01087QRJ2U/p1644843566306029

Må bruke et objekt med strong reference for å holde på verdiet til gauge

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/MigreringService.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/MigreringServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/iverksett/oppgaveforbarn/ForberedOppgaverForBarnServiceTest.kt

Lagt til att man kan migrere siste måneden bak i tiden
Og lagt til att kjøremåneden også kan migreres, tidligere migrerte vi fra neste måned
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8020

Migrering bak i tiden

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/RevurderingsController.kt

* https://github.com/navikt/familie-ef-sak/pull/1231/files

Litt ekstra feilmelding for søknads-revurderinger

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseSteg.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseStegTest.kt

Trenger ikke de når vi har patchet med startdato
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8137

Trenger ikke validering av tidligere opphør/0-andeler 

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingController.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/dto/BehandlingDto.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakService.kt

Behandling i frontend har behov for å vite stønadstype i mange tilfeller nå som vi begynner å implementere barnetilsyn og etterhvert skolepenger

Behandling dto stønadstype

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseSteg.kt

Fjerner featuretoggle for bruk av startdato etter patchning

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/AutomatiskMigreringController.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/AutomatiskMigreringService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/MigreringService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/MigreringsstatusRepository.kt
src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdReplikaClient.kt
src/main/resources/db/migration/V96__migrering.sql
src/test/kotlin/no/nav/familie/ef/sak/behandling/migrering/AutomatiskMigreringServiceTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7845

Automatiskt migrering av overgangsstønad

---

src/main/kotlin/no/nav/familie/ef/sak/ekstern/EksternBehandlingService.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakController.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakPersonService.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakRepository.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/SøkService.kt
src/main/kotlin/no/nav/familie/ef/sak/tilkjentytelse/TilkjentYtelseService.kt
src/test/kotlin/no/nav/familie/ef/sak/ekstern/EksternBehandlingControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/service/SøkServiceTest.kt

Det er lettere å holde styr på hva som henter fagsak med personer og hva som oppdaterer/burde oppdatere ident hvis all aksess til repository skjer ett sted.

Endret slik at all aksess av FagsakRepository skjer via FagsakService

---

src/main/kotlin/no/nav/familie/ef/sak/metrics/MålerService.kt
src/main/kotlin/no/nav/familie/ef/sak/metrics/domain/LøpendeBehandling.kt
src/main/kotlin/no/nav/familie/ef/sak/metrics/domain/MålerRepository.kt
src/test/kotlin/no/nav/familie/ef/sak/metrics/MålerRepositoryTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8191

Metric for å vise antall løpende saker, og beløp

---

src/main/kotlin/no/nav/familie/ef/sak/AuditLogger.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/sikkerhet/TilgangService.kt
src/test/kotlin/no/nav/familie/ef/sak/AuditLoggerTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7838
Tar med om man har tilgang eller ikke, og årsak til dette

Audit permit/deny

---

src/main/kotlin/no/nav/familie/ef/sak/vedtak/domain/Vedtak.kt

Frontend: https://github.com/navikt/familie-ef-sak-frontend/pull/994
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8203

Legg til periodetype "Ny periode for nytt barn"

---

src/main/kotlin/no/nav/familie/ef/sak/brev/VedtaksbrevService.kt

Kode - 6 skal ikke ha besluttersignatur

Besluttersignatur kode6 htmlbrev

---

src/main/kotlin/no/nav/familie/ef/sak/brev/VedtaksbrevService.kt

Co-authored-by: Mattis Janitz <mattis.janitz@nav.no>

Fjerner toggle for bruk av html ved generering av saksbehandlerbrev.

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/MigreringService.kt

Summerte perioder kan være en tom liste
Hvis Perioden allerede er opphørt så endres ikke opphørsdato
Så forenkler denne med å kun sjekke om opphørsdato mangler, eller om tom-dato er etter opphørsdato, hvis det er sånn så markeres den som ikke opphørt, og prøver på nytt

Forenkling av erOpphørtIInfotrygd

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/brev/FrittståendeBrevService.kt
src/test/kotlin/no/nav/familie/ef/sak/brev/FrittståendeBrevServiceTest.kt

Fikser https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8336
Kan merges etter https://github.com/navikt/familie-ef-iverksett/pull/375

Tar i bruk nye brevtyper for frittsående brev, og sender med stønadstype

---

src/main/resources/db/migration/V100__behandling_barn_ident_eller_termindato.sql
src/test/kotlin/no/nav/familie/ef/sak/barn/BarnRepositoryTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8300

BehandlingBarn må ha personIdent eller termindato

---

src/main/kotlin/no/nav/familie/ef/sak/vedtak/uttrekk/OpprettUttrekkArbeidssøkerTask.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/uttrekk/UttrekkArbeidssøkerServiceTest.kt

Payload ligger inne med formatet "YYYY-MM" i payload, som ble lagt inn fra en controller som opprettet den første tasken

Parser payload som inneholder YYYY-MM

---

src/main/kotlin/no/nav/familie/ef/sak/fagsak/SøkService.kt
src/test/kotlin/no/nav/familie/ef/sak/service/SøkServiceTest.kt
src/test/kotlin/testutil/PdlTestdataHelper.kt

Lagt til info om bostedsadressen i secureLogs

Sjekk på samme adresse kaster brukerfeil hvis søkeren har ukjent adresse

---

src/main/kotlin/no/nav/familie/ef/sak/vedtak/VedtakHistorikkBeregner.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/domeneparser/BasisDomeneParser.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/domeneparser/VedtakDomeneParser.kt
src/test/resources/no/nav/familie/ef/sak/sanksjon_mellom_to_perioder.feature

Sanksjon skal vises i vedtakshistorikken også når den ikke erstatter en periode

Sanksjon i vedtakshistorikken

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SendTilBeslutterSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/config/DatabaseConfiguration.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/VedtakService.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/domain/Vedtak.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SendTilBeslutterStegTest.kt

startDato burde blitt forbedret i forrige PR, men commiten ble aldri pushet :( 
Ellers fint å ikke bruke vedtak der vi ikke trenger å bruke det.

Bytt fra startDato til datoFra og bytt ut bruk av vedtak til vedtaksresultat

---

src/main/resources/db/migration/V106__legg_til_barnetilsyn_i_vedtak.sql

Script 103 satte denne til å øke med 5000 for hver fagsak, når vi kun skulle bumpe den med 5000

Skal øke ekstern_id med 1.

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/task/BehandlingsstatistikkTask.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/task/BehandlingsstatistikkTaskTest.kt

https://github.com/navikt/familie-ef-iverksett/pull/385

Send beslutterid til behandlingsstatistikk

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/task/BehandlingsstatistikkTask.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/task/BehandlingsstatistikkTaskTest.kt

Co-authored-by: Charlie Midtlyng <charlie.midtlyng@bekk.no>

Skal utlede begrunnelse for innvilgelse gitt stønadstype

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/blankett/BlankettService.kt

Co-authored-by: Charlie Midtlyng <charlie.midtlyng@bekk.no>

Skal kunne ferdigstille barnetilsynsbehandling

---

src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/BeregningBarnetilsynController.kt

Henter beregning gitt vedtak for barnetilsyn. Vi kan nok vurdere å hente fra tilkjente ytelser senere, men tenkte bare å få på plass noe før demo.

Skal hente beregning for barnetilsyn

---

.github/workflows/build-dev.yml
.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
pom.xml

Erstatter
* https://github.com/navikt/familie-ef-sak/pull/1401
* https://github.com/navikt/familie-ef-sak/pull/1400
* https://github.com/navikt/familie-ef-sak/pull/1398
* https://github.com/navikt/familie-ef-sak/pull/1397
* https://github.com/navikt/familie-ef-sak/pull/1396
* https://github.com/navikt/familie-ef-sak/pull/1395
* https://github.com/navikt/familie-ef-sak/pull/1394
* https://github.com/navikt/familie-ef-sak/pull/1393
* https://github.com/navikt/familie-ef-sak/pull/1392

Dependabot dependencies 20220419

---

src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/BeregningBarnetilsynService.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/BeregningBarnetilsynServiceTest.kt
src/test/resources/no/nav/familie/ef/sak/beregning_barnetilsyn_mangeperioder_maxbeløp_barn.feature

Har ikke tatt stilling til 0-beløp/hull. 
løser (deler av)
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8455

Valider fornuftige beløp

---

src/test/kotlin/no/nav/familie/ef/sak/cucumber/domeneparser/BasisDomeneParser.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/domeneparser/IdTIlUUIDHolder.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/domeneparser/SaksbehandlingDomeneParser.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/domeneparser/VedtakDomeneParser.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/steps/StepDefinitions.kt
src/test/resources/no/nav/familie/ef/sak/barnetilsyn/innvilge_vedtak.feature

Co-authored-by: Charlie Midtlyng <charlie.midtlyng@bekk.no>

Cucumbertester for tilkjente ytelser barnetilsyn

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/BeregningBarnetilsynService.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakBarnetilsynDto.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseStegBarnetilsynIntegrationTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/BeregningBarnetilsynControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/BeregningBarnetilsynServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/BeregningBarnetilsynUtilKtTest.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/steps/BeregningBarnetilsynStepDefinitions.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/LagreVedtakControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/VedtakDtoUtil.kt

Neste runde = Barnetilsynperiode?

Bruk heltall i bt request utgifter

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/TestSaksbehandlingController.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/GrunnlagsdataService.kt

Vil foreløpig feile på ` barnService.opprettBarnPåBehandlingMedSøknadsdata(...)`, men tenker fiksen av det tilhører en annen oppgave.

Skal kunne opprette dummybehandling for skolepenger

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/blankett/VedtaBlankettSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/VedtakHistorikkBeregner.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/VedtakService.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakBarnetilsynDto.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakDto.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtaksperiodeDto.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/VedtaBlankettStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/BeregningBarnetilsynControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/BeregningControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/VedtakServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/steps/StepDefinitions.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/VedtakDtoUtil.kt
src/test/resources/vedtak/SanksjonVedtakDto.json

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8492
Historikk kommer i egen PR

Lagt til håndtering for sanksjonert periode for Barnetilsyn

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingRepository.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakPersonRepository.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/VedtakController.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/VedtakService.kt

Inntektsendringer ytelseforbedringer

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/TestGOmregningController.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/grunnbelop/GOmregningService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/grunnbelop/GOmregningTask.kt

WIP
Kan fortsettes på når https://github.com/navikt/familie-ef-sak/pull/1429 er merget.

Opprettet task, service og test-controller for g-omregning.

---

src/main/kotlin/no/nav/familie/ef/sak/tilkjentytelse/TilkjentYtelseController.kt
src/main/kotlin/no/nav/familie/ef/sak/tilkjentytelse/TilkjentYtelseDto.kt
src/main/kotlin/no/nav/familie/ef/sak/tilkjentytelse/TilkjentYtelseService.kt

Siden returtypen endres skal jeg gjøre endringer i frontend før jeg merger denne PRen :)

Bt lopende stonad fix

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingRepository.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/grunnbelop/GOmregningService.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/BehandlingRepositoryTest.kt

Skal bare kunne benyttes av Mirja i dev til å starte med, dobbeltsjekk om featuretoggle er riktig her:
https://unleash.nais.io/#/features/strategies/familie.ef.sak.g-beregning

Feature toggle g beregning som behandling årsak

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/InfotrygdPeriodeValideringService.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8651

Åpner opp for å migrere åpne klagesaker

---

src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/AndelHistorikkBeregner.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/AndelHistorikkDto.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/VedtakHistorikkBeregner.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/domeneparser/BasisDomeneParser.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/domeneparser/VedtakDomeneParser.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/steps/StepDefinitions.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/historikk/AndelHistorikkBeregnerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/historikk/VedtakHistorikkBeregnerTest.kt
src/test/resources/no/nav/familie/ef/sak/barnetilsyn/sanksjon.feature
src/test/resources/no/nav/familie/ef/sak/sanksjon_mellom_to_perioder.feature

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8545
Feltet er allerede brukt i frontend, men manglet felt fra backend

Returnerer årsak til sanksjonering i vedtakshistorikk

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SendTilBeslutterSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/task/BehandlingsstatistikkTask.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakBarnetilsynDto.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakDto.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/LagreVedtakControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/VedtakDtoMapperTest.kt
src/test/resources/vedtak/BarnetilsynInnvilgetUtenUtbetalingVedtakDto.json

Skal kunne innvilge barnetilsyn, men få det til å fremstå som avslag/opphør for saksbehandler. Mulig det er mer som kreves av funksjonelle, men tror dette er minimumsendringer for å få lagret/hentet ut vedtak uten utbetaling
Hører sammen med [denne.](https://github.com/navikt/familie-ef-sak-frontend/pull/1159)

Bt innvilge uten utbetaling

---

pom.xml

Erstatter:
- https://github.com/navikt/familie-ef-sak/pull/1472
- https://github.com/navikt/familie-ef-sak/pull/1471
- https://github.com/navikt/familie-ef-sak/pull/1470
- https://github.com/navikt/familie-ef-sak/pull/1449
- https://github.com/navikt/familie-ef-sak/pull/1445
- https://github.com/navikt/familie-ef-sak/pull/1443
- https://github.com/navikt/familie-ef-sak/pull/1420
- https://github.com/navikt/familie-ef-sak/pull/1417
- https://github.com/navikt/familie-ef-sak/pull/1416

Dependabot oppdateringer 20220509-093820

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/BarnController.kt

Legger til tilgangskontroll av nye-eller-tidligere-fodte-barn for å kunne trigge kallet fra saksbehandling for å feilsøke oppgave som blitt opprettet som ikke gir mening. M kommer då kalle på endepunkten fra saksbehandling for å få liste på barn tilbake som er "nye"

Legger til tilgangskontroll av nye-barn i BarnController.

---

src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalpostClient.kt

Flere feil i loggen idag pga at de har brukt fnr når de søker etter journalpost
Kaster feil som logger warn i loggen og gir saksbehandlere litt bedre feilmelding

Kaster bad request hvis man ikke finner journalpost i fagarkivet

---

pom.xml

Erstatter:
- https://github.com/navikt/familie-ef-sak/pull/1490
- https://github.com/navikt/familie-ef-sak/pull/1489
- https://github.com/navikt/familie-ef-sak/pull/1488

Dependabot 20220516 110056

---

src/main/kotlin/no/nav/familie/ef/sak/ekstern/EksternBehandlingController.kt
src/main/kotlin/no/nav/familie/ef/sak/ekstern/EksternBehandlingService.kt
src/test/kotlin/no/nav/familie/ef/sak/ekstern/EksternBehandlingControllerTest.kt

Og ikke om den har hatt løpende stønad noen gang siste 12 måneder
- https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8576
- https://github.com/navikt/familie-ef-personhendelse/pull/169

Personhendelser skal kun opprette oppgave hvis personen har aktiv stønad

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/config/DatabaseConfiguration.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/domain/Vedtak.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakDto.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakSkolepengerDto.kt
src/main/resources/db/migration/V113__vedtak_skolepenger.sql
src/test/kotlin/no/nav/familie/ef/sak/beregning/VedtakServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/VedtakDtoMapperTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/VedtakDtoUtil.kt
src/test/resources/vedtak/SkolepengerInnvilgetVedtakDto.json

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8678
Modellen kan komme å endre seg, men nå så er dette en start

Skolepenger modell "utkast"

---

src/main/kotlin/no/nav/familie/ef/sak/vilkår/regler/vilkår/SamlivRegel.kt

Løser [denne oppgaven](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8666)

begrunnelse for inngangsvilkår om samliv skal være påkrevd

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingRepository.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/grunnbelop/GOmregningOppryddingService.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/VilkårsvurderingRepository.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/VilkårsvurderingRepositoryTest.kt

Vi burde ha kopiert søknad, barn og vilkår når vi utførte g-omregning

G omregning opprydding

---

src/test/kotlin/no/nav/familie/ef/sak/behandling/MigreringServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/steps/StepDefinitions.kt
src/test/kotlin/no/nav/familie/ef/sak/vilkår/regler/VilkårsregelTest.kt
src/test/resources/regler/INNTEKT.json

https://nav-it.slack.com/archives/G012YEK9YQ1/p1653995335640139

Fikset tester som feiler

---

.deploy/preprod.yaml
.deploy/prod.yaml

Oppfører bidrag-grunnlag som inbound application

---

src/main/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapper.kt
src/test/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapperTest.kt

* https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8893
* https://github.com/navikt/familie-ef-iverksett/pull/482

Mapper iverksetting av skolepenger

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt

* https://github.com/navikt/familie-ef-sak-frontend/pull/1282

Featuretoggler revurdering av skolepenger i frontend

---

.deploy/preprod.yaml
.deploy/prod.yaml

For å støtte https://doc.nais.io/persistence/postgres/#point-in-time-recovery
Testet i dev

Setter pointInTimeRecovery til true for databasen

---

src/main/kotlin/no/nav/familie/ef/sak/beregning/skolepenger/BeregningSkolepengerService.kt
src/main/kotlin/no/nav/familie/ef/sak/felles/util/DatoUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/skolepenger/BeregningSkolepengerServiceTest.kt

Tilbakemeldinger fra Charlie:
https://nav-it.slack.com/archives/C01087QRJ2U/p1655148478892159?thread_ts=1655126107.478759&cid=C01087QRJ2U
Favrooppgave på noen av de andre:
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8979

Forbedring av tekster for validering av skolepenger

---

src/main/kotlin/no/nav/familie/ef/sak/tilkjentytelse/domain/TilkjentYtelse.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8960

Dokumentasjon av startdato i tilkjent ytelse

---

src/test/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdPeriodeTestUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/InfotrygdReplikaMock.kt

Vil ha litt mer info på barnetilsyn-mockdata (fint å se forskjell på perioder/data)

Mock barnetilsyn infotrygd

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/beregning/skolepenger/BeregningSkolepengerService.kt
src/main/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapper.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/domain/Vedtak.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakSkolepengerDto.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/skolepenger/BeregningSkolepengerServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/domeneparser/VedtakDomeneParser.kt
src/test/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapperTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/VedtakDtoUtil.kt
src/test/resources/vedtak/SkolepengerInnvilgetVedtakDto.json
src/test/resources/vedtak/SkolepengerOpphørDto.json

Feedback fra brukertest var at den er forvirrende
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9060
https://github.com/navikt/familie-ef-iverksett/pull/501

Fjerner utgiftsperioder

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/InfotrygdPeriodeValideringService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/beregning/skolepenger/BeregningSkolepengerService.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakRepository.kt
src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdPerioderDto.kt
src/main/kotlin/no/nav/familie/ef/sak/infotrygd/PeriodeService.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/config/DatabaseConfiguration.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/migrering/InfotrygdPeriodeValideringServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/ekstern/bisys/BisysBarnetilsynServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/FagsakRepositoryTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/InsertUpdateRepositoryImplTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/VurderingServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/historikk/AndelHistorikkBeregnerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/økonomi/ØkonomiUtil.kt

Fjerner noen warnings
Tar i bruk riktig beløp i infotrygd
Fjerner unreachable kode

Div opprydding

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/RevurderingsController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt

Må merges etter denne: https://github.com/navikt/familie-ef-sak-frontend/pull/1327

Fjern featuretoggle for opprettelse av barn på revurdering

---

src/main/kotlin/no/nav/familie/ef/sak/beregning/skolepenger/BeregningSkolepengerService.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakDto.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakSkolepengerDto.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/skolepenger/BeregningSkolepengerServiceTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8965
Tidligere PR på opphør:
* https://github.com/navikt/familie-ef-sak/pull/1610

Opphør av skolepenger skal kunne endre delårsperioder

---

pom.xml

Erstatter:
- https://github.com/navikt/familie-ef-sak/pull/1648
- https://github.com/navikt/familie-ef-sak/pull/1647
- https://github.com/navikt/familie-ef-sak/pull/1631
- https://github.com/navikt/familie-ef-sak/pull/1630
- https://github.com/navikt/familie-ef-sak/pull/1628
- https://github.com/navikt/familie-ef-sak/pull/1626
- https://github.com/navikt/familie-ef-sak/pull/1625
- https://github.com/navikt/familie-ef-sak/pull/1624

Dependabot oppdateringer 20220704-093335

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseSteg.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/domeneparser/VedtakDomeneParser.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/steps/StepDefinitions.kt
src/test/resources/no/nav/familie/ef/sak/barnetilsyn/innvilget.feature
src/test/resources/no/nav/familie/ef/sak/skolepenger/opphør.feature

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8965
https://nav-it.slack.com/archives/C01087QRJ2U/p1657180928415169

Skal kunne opphøre alle perioder for skolepenger

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/dto/BehandlingDto.kt
src/test/kotlin/no/nav/familie/ef/sak/api/gui/BehandlingControllerTest.kt

Løser https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8088

Skal mappe henlagtårsak for behandlinger

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingController.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingRepository.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingService.kt
src/test/kotlin/ApplicationLocalPostgres.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/service/BehandlingServiceIntegrationTest.kt

[frontend](https://github.com/navikt/familie-ef-sak-frontend/pull/1394)
Løser delvis [dette kortet](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8506)
testing av feature-toggle er gjort i preprod

Gjenbruk inngangsvilkår

---

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/dto/PersonopplysningerDto.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/PersonopplysningerMapper.kt
src/test/resources/json/personopplysningerDto.json

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-4611

Vise alder personlinje

---

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/domene/GrunnlagsdataDomene.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/dto/PersonopplysningerDto.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/GrunnlagsdataMapper.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/PersonopplysningerMapper.kt
src/test/resources/json/grunnlagsdata_v2.json
src/test/resources/json/personopplysningerDto.json

Må mappe "omraader" ifm fullmakt, siden denne informasjonen trengs i frontend.

Mapper omraader til FullmaktDto

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/NullstillVedtakService.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/VedtakController.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/VedtakService.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/NullstillVedtakServiceTest.kt

For å støtte https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9024
Frontend: https://github.com/navikt/familie-ef-sak-frontend/pull/1437

Skal slette lagret vedtak

---

src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringService.kt
src/test/kotlin/no/nav/familie/ef/sak/service/JournalføringServiceTest.kt

Se beskrivelse på favro
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9211

Sjekk av infotrygdperioder ved journalføring av ny behandling for å sjekke om personen må bli migrert

---

src/main/kotlin/no/nav/familie/ef/sak/amelding/InntektController.kt
src/main/kotlin/no/nav/familie/ef/sak/amelding/InntektService.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9247

Endepunkt for å kunne generere url til a-inntekt med fagsakPersonId

---

src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveController.kt
src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveService.kt
src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveUtil.kt

…m en saksbehandler går inn på en oppgave som nettopp ble endret
Litt forbedringsforslag
Tenker det hadde vært fint å vite hvor lenge siden oppgaven ble endret, for å vite om saksbehandler som er inne på "feil" er inne på en nylig endret oppgave
Fortsetting på 
https://github.com/navikt/familie-ef-sak/pull/1697

Oppgave behandling logging tid siden endret

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8697

Featuretoggle for å vise legg til rad på vedtak for OS i frontend

---

pom.xml

Erstatter:
- https://github.com/navikt/familie-ef-sak/pull/1704
- https://github.com/navikt/familie-ef-sak/pull/1703
- https://github.com/navikt/familie-ef-sak/pull/1702
- https://github.com/navikt/familie-ef-sak/pull/1701
- https://github.com/navikt/familie-ef-sak/pull/1690

Dependabot oppdateringer 20220815-083100

---

src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringService.kt
src/main/kotlin/no/nav/familie/ef/sak/journalføring/dto/JournalføringRequest.kt

Endringen er bakåtkompatibel då frontend idag sender inn null eller PAPIRSØKNAD
Sånn att hvis den sender inn null, så blir det automatisk IKKE_VALGT
liten pre-PR for https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8145
Samt en liten fiks koblet til avsender, https://nav-it.slack.com/archives/C033WGAFAQ1/p1661414209093299?thread_ts=1661412726.322709&cid=C033WGAFAQ1

Journalføring ustrukturert dokumentasjon type

---

src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/SøkController.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/SøkService.kt
src/test/kotlin/no/nav/familie/ef/sak/api/gui/SøkControllerTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9278
* https://github.com/navikt/familie-ef-sak-frontend/pull/1550

Skal kunne søke etter person med eksternFagsakId

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/behandling/NyeBarnService.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakService.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/NyeBarnServiceIntegrationTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/NyeBarnServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/ekstern/journalføring/AutomatiskJournalføringControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/OppgaveServiceTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9399
Nå har denne dukket opp i prod også, slik at personhendelse ikke får lest flere hendelser før dette er rettet.

Finner nye eller tidligere fødte barn for alle stønader

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/RevurderingService.kt
src/test/kotlin/no/nav/familie/ef/sak/service/RevurderingServiceIntegrationTest.kt
src/test/kotlin/testutil/TestoppsettService.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9386

Kan kun opprette revurdering med årsak g-omregning for overgangsstønad

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/klage/KlageClient.kt
src/main/kotlin/no/nav/familie/ef/sak/klage/KlageController.kt
src/main/kotlin/no/nav/familie/ef/sak/klage/KlageService.kt
src/main/kotlin/no/nav/familie/ef/sak/klage/dto/OpprettKlageDto.kt
src/main/resources/application.yml
src/test/kotlin/ApplicationLocal.kt
src/test/kotlin/ApplicationLocalPostgres.kt
src/test/kotlin/no/nav/familie/ef/sak/klage/KlageClientMock.kt
src/test/kotlin/no/nav/familie/ef/sak/klage/KlageServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9405

Endepunkt for å opprette klage

---

src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdService.kt
src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdUtils.kt
src/main/kotlin/no/nav/familie/ef/sak/klage/KlageController.kt
src/main/kotlin/no/nav/familie/ef/sak/klage/KlageService.kt
src/main/kotlin/no/nav/familie/ef/sak/klage/dto/ÅpneKlagerDto.kt
src/test/kotlin/no/nav/familie/ef/sak/klage/KlageServiceTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9405

Endepunkt for å sjekke om det finnes åpne klager

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9405

Legger til featuretoggle for å vise toggle for opprett klage i frontend

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/klage/KlageClient.kt
src/main/kotlin/no/nav/familie/ef/sak/klage/KlageController.kt
src/main/kotlin/no/nav/familie/ef/sak/klage/KlageService.kt
src/main/kotlin/no/nav/familie/ef/sak/klage/dto/KlagebehandlingerDto.kt
src/test/kotlin/no/nav/familie/ef/sak/klage/KlageClientMock.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9293

Hent klagebehandlinger

---

src/main/kotlin/no/nav/familie/ef/sak/ekstern/bisys/BisysBarnetilsynService.kt
src/test/kotlin/no/nav/familie/ef/sak/ekstern/bisys/BisysBarnetilsynServiceTest.kt

Fant denne når jeg satt med 
https://github.com/navikt/familie-ef-sak/pull/1788

En avslått behandling har ikke tilkjent ytelse og denne hadde då feilet

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/TestSaksbehandlingController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/VurderingService.kt
src/test/kotlin/no/nav/familie/ef/sak/OppslagSpringRunnerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/TestSaksbehandlingControllerTest.kt

Frontend: https://github.com/navikt/familie-ef-sak-frontend/pull/1598

Automatisk utfylle alle vilkår i test

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/mapper/BarnMedSamværMapper.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/VurderingService.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/dto/BarnMedSamværDto.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/regler/Vilkårsregel.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/regler/vilkår/AleneomsorgRegel.kt
src/test/kotlin/no/nav/familie/ef/sak/api/gui/VurderingControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vilkår/VurderingServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vilkår/VurderingStegServiceTest.kt

Denne er featuretogglet og bare aktivert i preprod, slik at det kan testes ordentlig.
Verifisert i preprod :D

Initier automatisk vurderte nære boforhold

---

src/main/resources/db/migration/V120__konsistensavstemming_tidsplan_2023.sql

Lagt inn datoer for konsistensavstemming for 2023

---

src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveService.kt

Rettet at det ble feil oppgavetekst som følge av en refaktorering for oppfølgingsoppgavene.

Rettet oppgavetekst

---

.deploy/azure-ad-app-lokal.yaml
.deploy/preprod.yaml
.deploy/prod.yaml
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/config/RolleConfig.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/sikkerhet/SikkerhetContext.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/sikkerhet/TilgangService.kt
src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveClient.kt
src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveController.kt
src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveService.kt
src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveUtil.kt
src/main/resources/application-dev.yml
src/main/resources/application.yml
src/test/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/TilgangServiceTest.kt
src/test/resources/application-local.yml

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9717
Har kjørt apply på lokal-azureAdApp og testet lokalt

Skal ikke hente mapper for egen ansatt hvis man ikke har rollen

---

src/main/kotlin/no/nav/familie/ef/sak/vilkår/VurderingStegService.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/regler/Vilkårsregel.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/regler/evalutation/OppdaterVilkår.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/regler/vilkår/AlderPåBarnRegel.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/regler/vilkår/AleneomsorgRegel.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/regler/vilkår/SivilstandRegel.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/regler/vilkår/TidligareVedtaksperioderRegel.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/OmregningServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/RevurderingServiceIntegrationTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vilkår/VurderingServiceIntegratsjonsTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vilkår/VurderingServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vilkår/regler/GrafRendererTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vilkår/regler/evalutation/OppdaterVilkårTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vilkår/regler/evalutation/RegelValideringTest.kt

Sliter med å finne metoden mellom hver gang pga skrivefeilen 😅

Rename til initiere delvilkår (pluss linter-endringer)

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/InfotrygdPeriodeValideringService.kt

Etter diskusjon med Mirja og Hilde

Skal tillatere å migrere hvis det finnes anke i Infotrygd

---

src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9900

Fjerner featuretoggle for synkroniser personidenter

---

pom.xml

* https://github.com/navikt/familie-ef-sak/pull/1822
* https://github.com/navikt/familie-ef-sak/pull/1821
* https://github.com/navikt/familie-ef-sak/pull/1807
* https://github.com/navikt/familie-ef-sak/pull/1804
~* https://github.com/navikt/familie-ef-sak/pull/1803~

Oppdaterer avhengigheter

---

src/main/kotlin/no/nav/familie/ef/sak/brev/BrevMellomlagerController.kt
src/test/kotlin/no/nav/familie/ef/sak/brev/BrevMellomlagerControllerTest.kt

[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9928)

Skal kunne nullstille frittstående brev

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
src/main/kotlin/no/nav/familie/ef/sak/utestengelse/Utestengelse.kt
src/main/kotlin/no/nav/familie/ef/sak/utestengelse/UtestengelseController.kt
src/main/kotlin/no/nav/familie/ef/sak/utestengelse/UtestengelseDto.kt
src/main/kotlin/no/nav/familie/ef/sak/utestengelse/UtestengelseRepository.kt
src/main/kotlin/no/nav/familie/ef/sak/utestengelse/UtestengelseService.kt
src/main/resources/db/migration/V122__utestengelse.sql
src/test/kotlin/no/nav/familie/ef/sak/OppslagSpringRunnerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/utestengelse/UtestengelseRepositoryTest.kt
src/test/kotlin/no/nav/familie/ef/sak/utestengelse/UtestengelseServiceTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7802
Lagt til mulighet for å lagre, hente, og slette utestengelse.
* https://github.com/navikt/familie-ef-sak-frontend/pull/1637

Utestengelse

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/InfotrygdPeriodeValideringService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/MigreringService.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/MigreringController.kt
src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdPerioderDto.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/MigreringServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/PdlClientConfig.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10006
Kan ta en gjennomgang hvis det er ønskelig :) 
Vi har 22 idag som må migreres, kommer ikke lage noe i frontend for dette men la M bruke fetch :-)

Migrering barnetilsyn

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10006

Featuretoggle for migrering barnetilsyn

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/ekstern/EksternVedtakController.kt
src/main/kotlin/no/nav/familie/ef/sak/ekstern/EksternVedtakService.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/sikkerhet/TilgangService.kt
src/test/kotlin/no/nav/familie/ef/sak/ekstern/EksternVedtakControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/TilgangServiceTest.kt

For å tilgjengeliggjøre påklagbare vedtak for familie-klage.
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9970

Skal kunne hente behandlinger med vedtak gitt eksternFagsakId

---

src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalpostClient.kt

Journalpost tittel mangler ved fullfør

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/domain/Behandling.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakService.kt
src/main/resources/db/migration/V123__behandling_vedtakstidspunkt.sql
src/test/kotlin/no/nav/familie/ef/sak/service/BehandlingServiceTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10077
* Steg 1, denne PR: Legge til kolonne, og sette den
* Steg 2. populere kolonne med data, og ta i bruk den rundt om i koden
* 😃 
Charlie nevnte også noe om en teknisk-gjeld oppgave for dette men fant den ikke.

Behandling vedtakstidspunkt

---

.deploy/preprod.yaml
.deploy/prod.yaml
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/arbeidssøker/ArbeidssøkerClient.kt
src/main/resources/application.yml

Rettet context-path i url
Testet OK i preprod

Rettet properties arbeidssoker

---

pom.xml

Dependabot oppdateringer 20221031-080158
Erstatter:
- https://github.com/navikt/familie-ef-sak/pull/1856
- https://github.com/navikt/familie-ef-sak/pull/1855
- https://github.com/navikt/familie-ef-sak/pull/1846
- https://github.com/navikt/familie-ef-sak/pull/1845
- https://github.com/navikt/familie-ef-sak/pull/1844
- https://github.com/navikt/familie-ef-sak/pull/1822
- https://github.com/navikt/familie-ef-sak/pull/1821
- https://github.com/navikt/familie-ef-sak/pull/1807
- ~https://github.com/navikt/familie-ef-sak/pull/1803~

Dependabot 20221031 080158

---

src/main/kotlin/no/nav/familie/ef/sak/klage/KlageService.kt
src/test/kotlin/no/nav/familie/ef/sak/klage/KlageServiceTest.kt

Vedtaksdatoen i behandlingsoversikten skal ikke være satt før svar fra kabal foreligger (dersom klage er oversendt)
Kunne også gjort filtreringen i familie-klage, men tenker det er greit å sende med all dataen, og så får det være opp til fagsystemene å tolke/vise den som de vil.

Skal bruke vedtaksdato fra kabal dersom klagebehandling er oversendt

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/arbeidssøker/ArbeidssøkerClient.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/uttrekk/OpprettUttrekkArbeidssøkerTask.kt

https://nav-it.slack.com/archives/G012YEK9YQ1/p1667293396899579?thread_ts=1667291741.086169&cid=G012YEK9YQ1
Fjerner https://unleash.nais.io/#/features/strategies/familie.ef.sak.arbeidssoker-api.gcp etter denne er merget

Fjerner toggle av url for arbeidssøker og endrer error til warning

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/dto/BehandlingDto.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingshistorikk/BehandlingshistorikkRepository.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingshistorikk/BehandlingshistorikkService.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakService.kt
src/test/kotlin/no/nav/familie/ef/sak/service/BehandlingshistorikkServiceTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10077
Bygger videre på 
* https://github.com/navikt/familie-ef-sak/pull/1852

Bruk vedtakstidspunkt fra behandling i BehandlingDto

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringKlageService.kt
src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringService.kt
src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalpostController.kt
src/main/kotlin/no/nav/familie/ef/sak/journalføring/dto/JournalføringKlageRequest.kt
src/main/kotlin/no/nav/familie/ef/sak/journalføring/dto/JournalføringRequest.kt
src/main/kotlin/no/nav/familie/ef/sak/klage/KlageService.kt
src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/FamilieIntegrasjonerMock.kt
src/test/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringKlageServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/journalføring/JournalpostControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/klage/KlageServiceTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9309

Journalføring klage

---

src/main/kotlin/no/nav/familie/ef/sak/ekstern/EksternVedtakService.kt
src/test/kotlin/no/nav/familie/ef/sak/api/gui/SøkControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/ekstern/EksternVedtakControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/InfotrygdReplikaMock.kt
src/test/resources/json/simuleringsresultat_beriket.json

Bruker vedtakstidspunkt, den finnes alltid for ferdigstilt behandling

---

src/main/kotlin/no/nav/familie/ef/sak/ekstern/EksternVedtakService.kt
src/test/kotlin/no/nav/familie/ef/sak/ekstern/EksternVedtakControllerTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10302

Skal ikke ta med henlagte behandlinger ved henting av vedtak

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/behandling/RevurderingService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/Saksbehandling.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/MigreringService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SendTilBeslutterSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/VentePåStatusFraIverksett.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/MigreringServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/InfotrygdReplikaMock.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7888

Manuell behandling satsendring

---

pom.xml

Erstatter:
- https://github.com/navikt/familie-ef-sak/pull/1886
- https://github.com/navikt/familie-ef-sak/pull/1884
- https://github.com/navikt/familie-ef-sak/pull/1845
- https://github.com/navikt/familie-ef-sak/pull/1822

Dependabot 20221114 091455

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingController.kt

Forenkler hentGamleUferdigeBehandlinger

Fjerner resetSteg då den ikke lengre brukes

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/behandling/domain/ÅrsakRevurdering.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/dto/RevurderingsinformasjonDto.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/ÅrsakRevurderingSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapper.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/ÅrsakRevurderingServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/ÅrsakRevurderingsRepositoryTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/ÅrsakRevurderingStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapperTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt

- Flyttet årsak og kilde til kontrakter for å bruke tvers ef-sak og iverksett
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10431
Mappe til DVH kommer i egen PR

Sender årsak revurdering til iverksett.

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/ÅrsakRevurderingService.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/ÅrsakRevurderingServiceTest.kt

- Hvis man legger inn en ny årsak kommer testen feile for at man må ta stilling til om den årsaken skal valideres eller ikke
* https://github.com/navikt/familie-ef-sak/pull/1893#issuecomment-1320062104
* https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10445

ÅrsakRevurdering skal ikke valideres for gitte behandlingsårsaker

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/behandling/ÅrsakRevurderingService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/task/BehandlingsstatistikkTask.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/task/BehandlingsstatistikkTaskTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10431
Koblet til:
* https://github.com/navikt/familie-ef-iverksett/pull/621
Avhengig av:
* https://github.com/navikt/familie-kontrakter/pull/655

ÅrsakRevurdering skal sendes till behandlingsstatistikk

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/ekstern/EksternVedtakService.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakController.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/sikkerhet/TilgangService.kt
src/main/kotlin/no/nav/familie/ef/sak/tilbakekreving/TilbakekrevingClient.kt
src/test/kotlin/no/nav/familie/ef/sak/ekstern/EksternVedtakControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/ekstern/EksternVedtakServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/TilbakekrevingClientTestConfig.kt
src/test/kotlin/no/nav/familie/ef/sak/service/TilgangServiceTest.kt

- Returnerer tilbakekrevingsvedtak når når man henter eksterne vedtak
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10404
Koblet til:
* https://github.com/navikt/familie-tilbake/pull/933
Featuretogglet, så kan deployes uavhengig den pull requesten

Skal kunne klage på tilbakekrevinger

---

src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/BeregningBarnetilsynController.kt
src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/BeregningBarnetilsynRequest.kt
src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/BeregningBarnetilsynService.kt
src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/BeregningBarnetilsynUtil.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/PdlClient.kt
src/main/kotlin/no/nav/familie/ef/sak/tilkjentytelse/AndelsHistorikkService.kt
src/main/kotlin/no/nav/familie/ef/sak/tilkjentytelse/TilkjentYtelseMapper.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/AndelHistorikkBeregner.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/VedtakHistorikkBeregner.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/BeregningBarnetilsynServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/steps/BeregningBarnetilsynEnPeriodeStepDefinitions.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/steps/BeregningBarnetilsynStepDefinitions.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/steps/StepDefinitions.kt
src/test/kotlin/no/nav/familie/ef/sak/felles/util/FeatureToggleTestUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/KopierVedtakServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/historikk/AndelHistorikkBeregnerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/historikk/VedtakHistorikkBeregnerTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7888

Feature toggle satsendring for å ta i bruk nye satser i preprod

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SendTilBeslutterSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/ÅrsakRevurderingSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/MigreringServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SendTilBeslutterStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/ÅrsakRevurderingStegTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8647

Fjerner featuretoggle for årsak revurdering

---

README.md
doc/BarnetilsynSatsendring_README.md
src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/satsendring/BarnetilsynSatsendringScheduler.kt
src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/satsendring/BarnetilsynSatsendringService.kt
src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/satsendring/README.md
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/PdlSjekkController.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7888

Dokumentasjon manuell satsendring barnetilsyn

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/brev/dto/FrittståendeBrevKategori.kt
src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringService.kt
src/test/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringServiceTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10564

Brevkategori brev svartid

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/FørstegangsbehandlingService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/RevurderingService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/TestSaksbehandlingController.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/task/BehandlingsstatistikkTask.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/task/OpprettOppgaveForOpprettetBehandlingTask.kt
src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringService.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/FørstegangsbehandlingServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/task/OpprettOppgaveForOpprettetBehandlingTaskTest.kt
src/test/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringServiceTest.kt

Reverter https://github.com/navikt/familie-ef-sak/commit/75615b495de7f3f2b25fde0c4daba932258ed425
Som var en revert av https://github.com/navikt/familie-ef-sak/commit/a5f853bf730d096f39675f3adfb62c06a9e4873f
(dvs revertet feilet i master først, for å unngå at flere behandlinger ikke får opprettet oppgave direkte)
+ Fikser tasken med riktig type
+ Oppretter ikke oppgave hvis ikke behandlingen er under behandling
+ Legger til test

Opprett oppgave async fiks

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/ekstern/EksternBehandlingController.kt
src/main/kotlin/no/nav/familie/ef/sak/ekstern/EksternBehandlingService.kt
src/test/kotlin/no/nav/familie/ef/sak/ekstern/EksternBehandlingServiceTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10275
Det er ønskelig å vise en info-tekst når man klikker på ferdigstill som sier om en ny behandling kan opprettes eller ikke (se skisser)
* https://github.com/navikt/familie-klage/pull/214
* https://github.com/navikt/familie-klage-frontend/pull/263

Klage automatisk revurdering sjekk

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/TotrinnskontrollService.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/TotrinnskontrollStatusDto.kt
src/test/kotlin/no/nav/familie/ef/sak/api/gui/VedtakControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/TotrinnskontrollServiceTest.kt

Backend for https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10026
Frontend: https://github.com/navikt/familie-ef-sak-frontend/pull/1866

Skal støtte strukturerte årsaker til underkjent vedtak totrinnskontroll

---

src/main/kotlin/no/nav/familie/ef/sak/beregning/skolepenger/SkolepengerMaksbeløp.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/skolepenger/SkolepengerMaksbeløpTest.kt

https://nav-it.slack.com/archives/C01087QRJ2U/p1671524455261859

Beløp for skolepenger 2019 pga en sak som vært i trygderetten

---

pom.xml

Erstatter:
- https://github.com/navikt/familie-ef-sak/pull/1986
- https://github.com/navikt/familie-ef-sak/pull/1976
- https://github.com/navikt/familie-ef-sak/pull/1974

Dependabot 20230102 085749

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/TestSaksbehandlingController.kt

Koblet til 
https://github.com/navikt/familie-ef-sak/pull/1989

Skal ikke ha med barn over 18 i søkadsinformasjonen i testcontrollern

---

src/main/resources/application-dev.yml
src/main/resources/application.yml
src/test/resources/application-integrasjonstest.yaml
src/test/resources/application-local.yml

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10604

Endrer til å bruke q2

---

src/main/kotlin/no/nav/familie/ef/sak/vedtak/PatchPeriodetypeBarnetilsynController.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/domain/Vedtak.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakBarnetilsynDto.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakDto.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/domeneparser/VedtakDomeneParser.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/KopierVedtakServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/LagreVedtakControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/PatchPeriodetypeBarnetilsynControllerTest.kt

Steg 1 for å støtte [periodetype for barnetilsyn](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10523)
Tenker å teste i preprod før merge, og kjøre en dryrun først.

Skal patche barnetilsynsvedtak med nytt felt periodetype

---

src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/AndelHistorikkBeregner.kt

* sanksjonMedSammePerioder skal sjekke barnetilsyn også

Rydder opp litt i begrep og eventuelle småfeil

---

src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/AndelHistorikkBeregner.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/VedtakHistorikkBeregner.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/domeneparser/VedtakDomeneParser.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/historikk/VedtakHistorikkBeregnerTest.kt

Litt for å unngå å sende med stønadstype i lagSanksjonertPeriode
Litt mer opprydding, gjøres som en del av, og er for å ikke få for mye endringer i den PR'en som trengs for:
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7981

Ta i bruk egen perioe for sanksjon i VedtakHistorikkBeregner

---

src/main/kotlin/no/nav/familie/ef/sak/vedtak/PatchPeriodetypeBarnetilsynController.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/domain/Vedtak.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakBarnetilsynDto.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakDto.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/domeneparser/VedtakDomeneParser.kt
src/test/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapperTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/KopierVedtakServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/LagreVedtakControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/PatchPeriodetypeBarnetilsynControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/VedtakDtoUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/domain/VedtakTest.kt
src/test/resources/vedtak/BarnetilsynInnvilgetUtenUtbetalingVedtakDto.json
src/test/resources/vedtak/BarnetilsynInnvilgetVedtakDto.json

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10523

Skal legge til periodetype og aktivitetstype for barnetilsyn

---

pom.xml

* https://github.com/navikt/familie-kontrakter/pull/684
Tester med Halvor:
1. Deployer integrasjoner
2. tester
3. Deployer ef-sak
4. tester

Oppdaterer kontrakter, fjernet annotasjon som ikke er i bruk

---

src/main/kotlin/no/nav/familie/ef/sak/klage/KlageController.kt
src/main/kotlin/no/nav/familie/ef/sak/klage/KlageService.kt
src/test/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringKlageServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/klage/KlageServiceTest.kt

Eks når man skal klage på et vedtak fra infotrygd
https://nav-it.slack.com/archives/C01087QRJ2U/p1673531068414909
* https://github.com/navikt/familie-ef-sak-frontend/pull/1948

Opprett klage på fagsak uten ferdigstilt behandling

---

src/main/kotlin/no/nav/familie/ef/sak/blankett/BlankettPdfRequest.kt
src/main/kotlin/no/nav/familie/ef/sak/blankett/BlankettService.kt

For å støtte https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10526

Skal sende med årsakRevurdering til blankett

---

src/main/resources/db/migration/V128__behandling_unik_i_arbeid_på_vent.sql
src/test/kotlin/no/nav/familie/ef/sak/repository/BehandlingRepositoryTest.kt

Denne ble trukket ut fra https://github.com/navikt/familie-ef-sak/pull/2022 pga at den først feilet
Jeg tror kanskje feilet var pga `@parameterizedtest` inne i `@Nested`, men er usikker.. Nå virker det i hvert fall

Flere behandlinger samtidig database

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/OpprettBehandlingUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/felles/util/OpprettBehandlingUtilTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/BehandlingServiceIntegrationTest.kt

…ehandling på vent
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10514
Ble både unit og integrasjonstest på denne

Ny behandling når behandling er på vent

---

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/GrunnlagsdataService.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/PersonopplysningerService.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/domene/GrunnlagsdataDomene.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/dto/PersonopplysningerDto.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/PersonopplysningerMapper.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/VilkårGrunnlagService.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/dto/VilkårDto.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/migrering/OpprettOppgaveForMigrertFødtBarnTaskTest.kt
src/test/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapperTest.kt
src/test/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/PersonopplysningerMapperTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vilkår/VilkårTestUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/vilkår/gjenbruk/GjenbrukVilkårServiceTest.kt
src/test/resources/json/personopplysningerDto.json

Som en del i at diffe endringer i grunnlagsdata

Grunnlagsdata fjerner felt som ikke er brukt

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/domain/Vedtak.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakBarnetilsynDto.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/VedtakHistorikkBeregner.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/VedtakHistorikkService.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseStegBarnetilsynIntegrationTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/BeregningBarnetilsynControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/domeneparser/VedtakDomeneParser.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/LagreVedtakControllerTest.kt
src/test/resources/no/nav/familie/ef/sak/barnetilsyn/sanksjon_revurdering.feature

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10612
* **Koblet til:** https://github.com/navikt/familie-ef-sak-frontend/pull/1972
* **Litt liknende revurder med sanksjon for OS** https://github.com/navikt/familie-ef-sak/pull/1946
* **Bygger videre på** https://github.com/navikt/familie-ef-sak/pull/2036

Skal kunne revurdere sanksjoner for barnetilsyn

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt

Merges når https://github.com/navikt/familie-ef-sak-frontend/pull/1985 har vært ute en stund.

Fjerner featuretoggle for automatiske flettefelt

---

src/test/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/endringer/UtledEndringerUtilTest.kt
src/test/resources/json/endringer-personopplysninger/endringer.json

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-11013

Legger til tilfelle der et barn får en forelder

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/VedtakHistorikkService.kt

Merges etter
https://github.com/navikt/familie-ef-sak-frontend/pull/2019

Fjerner toggle for revurder fra for barnetilsyn

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/ByEnvironmentStrategy.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/ByUserIdStrategy.kt

**Test i dev**
familie.ef.sak.frontend-angre-send-til-beslutter
Skrudd av:
Skrudd på:

Bytt unleash client

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/brev/dto/FrittståendeBrevKategori.kt

For å støtte https://github.com/navikt/familie-ef-sak-frontend/pull/2029

Skal støtte ny frittstående brevmal for trukket søknad

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/sikkerhet/TilgangService.kt

Vil ikke sende personIdent til frontend. Fjerner derfor de stedene vi legger denne inn i ManglerTilgang melding.

Vil ikke legge personIdent melding når vi kaster ManglerTilgang feil.

---

src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalpostClient.kt

https://nav-it.slack.com/archives/G012YEK9YQ1/p1676970669440219

Fjerner trailing slash fra url mot integrasjoner

---

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/mapper/BarnMedSamværMapper.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/AdresseHjelper.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/AndelHistorikkBeregner.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/VilkårGrunnlagService.kt
src/test/kotlin/no/nav/familie/ef/sak/mapper/AdresseHjelperTest.kt
src/test/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/PersonopplysningerMapperTest.kt

Denne endringen ble ikke pushet i forrige PR ifm delt bosted : https://github.com/navikt/familie-ef-sak/pull/2103/files#r1114253836

Endrer variabelnavn til grunnlagsdataOpprettet

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/MigreringService.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/MigreringServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/felles/util/BehandlingOppsettUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/felles/util/OpprettBehandlingUtilTest.kt

https://nav-it.slack.com/archives/G012YEK9YQ1/p1677491156619709
Får ikke testet denne i dev pga Q2, men får testet i prod :-)

Skal kunne migrere hvis det kun finnes henlagte behandlinger

---

src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/BeregningBarnetilsynUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/BeregningBarnetilsynUtilKtTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12063
Det er behov for å innvilge en stønad bak til 2017 etter en klagesak
https://lovdata.no/nav/rundskriv/v7-15-00

Lagt inn beløp for barnetilsyn bak til 2016

---

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/PersonService.kt

7 dager virker litt lang tid
Kom med her
* https://github.com/navikt/familie-ef-sak/pull/2010/commits/21a1f17ad06fca7237ab7bb78f717fb4355880f0

Bruker default cache for hentPersonidenter som er 60m

---

.deploy/preprod.yaml
src/main/resources/application-dev.yml

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-11924
* https://github.com/navikt/familie-ef-sak-frontend/pull/2168

Erstatter dev.intern med intern.dev ingress

---

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/PdlPersonSøkHjelper.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/pdl/PdlPersonRequestVariables.kt
src/test/kotlin/no/nav/familie/ef/sak/felles/integration/PdlPersonSøkHjelperTest.kt

Setter exists = false hvis et verdi mangler, sånn at man ikke får opp personer som har eks bruksenhetsnummer når det mangler på brukeren
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12069

Bedre treff mot søk person for se beboer

---

.deploy/azure-ad-app-lokal.yaml
.deploy/preprod.yaml
.deploy/prod.yaml
src/main/resources/application-dev.yml
src/main/resources/application.yml
src/test/resources/application-local.yml

https://nav-it.slack.com/archives/CJN0STWB0/p1678778738017379

Ny rolle for å behandle egen ansatt

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SaksbehandlingsblankettSteg.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SaksbehandlingsblankettStegTest.kt

For å fikse prodfeil: https://familie-prosessering.intern.nav.no/service/familie-ef-sak/gruppert?statusFilter=MANUELL_OPPF%C3%98LGING&callId=0952caa9-a912-4bfb-b0da-bae3c050e3c5
Hvis noe feiler ved journalføring av blankett, men Joark likevel rakk å journalføre dokumentet vil vi få 409 Conflict når tasken/steget rekjøres. Da skal vi ikke trenge å journalføre på nytt, men må heller sette denne journalposten på behandlingen og fortsette stegflyten

Skal håndtere 409 Conflict ved journalføring av blankett

---

src/main/kotlin/no/nav/familie/ef/sak/sigrun/SigrunService.kt
src/test/kotlin/no/nav/familie/ef/sak/sigrun/SigrunServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vilkår/VurderingServiceTest.kt

Trenger å hente opplysninger om pensjonsgivende inntekt for person og næring fra Svalbard fra Sigrunn ([FAVRO](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-8724))

Beregnet skatt svalbard

---

.deploy/preprod.yaml
.deploy/prod.yaml
src/main/kotlin/no/nav/familie/ef/sak/kontantstøtte/KontantstøtteClient.kt
src/main/kotlin/no/nav/familie/ef/sak/kontantstøtte/KontantstøtteController.kt
src/main/kotlin/no/nav/familie/ef/sak/kontantstøtte/KontantstøtteService.kt
src/main/resources/application.yml
src/test/kotlin/no/nav/familie/ef/sak/kontantstøtte/KontantstøtteClientTest.kt

I vedtak og beregning for innvilget barnetilsyn, skal det vises om bruker mottar eller har mottatt kontantstøtte.

Nytt endepunkt for å hente ut kontantstøtte barnetilsyn.

---

src/test/kotlin/no/nav/familie/ef/sak/service/RevurderingServiceIntegrationTest.kt

Søknaden for første behandling inneholder nå de samme barnen som PDL sånn at man ikke oppretter flere nye vilkår

Fikset test som feilet sporadiskt

---

pom.xml

Hadde ikke fått meg med denne i ef-sak
https://github.com/navikt/familie-integrasjoner/pull/794#discussion_r1118689593

Oppdaterer til nyere versjon av springdoc

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/InfotrygdPeriodeValideringService.kt
src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringKlageService.kt
src/main/kotlin/no/nav/familie/ef/sak/journalføring/OppdaterOppgaveTilÅGjeldeTilbakekrevingTask.kt
src/main/kotlin/no/nav/familie/ef/sak/journalføring/dto/JournalføringKlageRequest.kt
src/main/kotlin/no/nav/familie/ef/sak/klage/KlageService.kt
src/main/kotlin/no/nav/familie/ef/sak/oppgave/dto/OppgaveEfDto.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/VedtakHistorikkBeregner.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/VedtakHistorikkService.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/gjenbruk/GjenbrukVilkårService.kt
src/test/kotlin/no/nav/familie/ef/sak/barn/BarnServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/NyeBarnServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/migrering/InfotrygdPeriodeValideringServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/ÅrsakRevurderingServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/ÅrsakRevurderingStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/ValiderOmregningServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/skolepenger/BeregningSkolepengerServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/ekstern/EksternBehandlingServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/felles/util/DatoUtilTest.kt
src/test/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/BehandlingServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/utestengelse/UtestengelseServiceTest.kt

Testklasser feilet pga `Class or object name should start with an uppercase letter and use camel case (standard:class naming)` så har fikset de :)

ktlint 0.49.0

---

src/main/kotlin/no/nav/familie/ef/sak/tilbakekreving/TilbakekrevingClient.kt
src/test/kotlin/no/nav/familie/ef/sak/tilbakekreving/TilbakekrevingClientTest.kt

Samme sak som https://github.com/navikt/familie-ef-iverksett/pull/687/files#r1118476333

Må encode norske tegn i url etter oppgradering av spring

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/oppgavekontroll/BehandlingsoppgaveService.kt
src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveService.kt

Bugfix - limit for lav, fikk ikke hentet alle oppgaver.

Limit på hent oppgave

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/oppgavekontroll/ÅpneBehandlingerUtenOppgaveScheduler.kt

Ønsker å bruke scheduler som kjører hver mandag klokken 0800

Benhandling oppgave scheduler

---

src/main/kotlin/no/nav/familie/ef/sak/beregning/Beregning.kt
src/main/kotlin/no/nav/familie/ef/sak/felles/util/DatoUtil.kt
src/main/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapper.kt
src/test/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapperTest.kt

Vi vil unngå at behandlinger blir iverksatt med utdatert grunnbeløp. Legger derfor til validering av dette. Setter foreløpig frist til 15. juni, men vi kan justere denne.

Skal validere grunnbeløp ved iverksetting

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/oppgaveforopprettelse/OppgaverForOpprettelseService.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/config/FeatureToggleConfig.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/oppgaveforopprettelse/OppgaverForOpprettelseServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/mapper/SøknadsskjemaMapperTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vilkår/VilkårGrunnlagServiceTest.kt

**Hvorfor?** 
Ønsker å fjerne litt unødvendig kode og kjøre linter. 
- Vil fjerne unødvendig if (unleash.environment == "local"). Behov dekkes nå av mock-featuretoggle.
- Kjørt ktlint
Her er toggles hentet ut til sak-frontend på localhost:

Liten opprydding

---

src/test/kotlin/no/nav/familie/ef/sak/beregning/OmregningServiceTest.kt

Tenker vi lager nye tester når ny G for 2023 kommer.

Skal bruke G/beregning fra 2022 så tester ikke brekker ved ny G.

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
src/main/kotlin/no/nav/familie/ef/sak/karakterutskrift/AutomatiskBrevInnhentingKarakterutskriftController.kt
src/main/kotlin/no/nav/familie/ef/sak/karakterutskrift/AutomatiskBrevInnhentingKarakterutskriftService.kt
src/main/kotlin/no/nav/familie/ef/sak/karakterutskrift/KarakterutskriftBrevTask.kt
src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveUtil.kt

Begynner på [automatisk innhenting av karakterutskrift](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-8258)
Setter opp et skall med controller, service og task for automatisk innhenting av karakterutskrift. Dette er featuretogglet så skal gå fint å ha det i prod selv om det ikke er ferdig implementert.
Vi ønsker å kjører en dryRun i prod for å verifisere at vi finner de riktige oppgavene - derfor lager vi PR nå.

Skall for automatisk brev innhenting karakterutskrift

---

src/main/kotlin/no/nav/familie/ef/sak/karakterutskrift/AutomatiskBrevInnhentingKarakterutskriftController.kt

Vil åpne opp endepunktet, men toggle skal være påskrudd for ar liveRun skal funke i prod.

Karakterutskriftbrev - Skal kunne gjøre dryRun i prod

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
pom.xml

https://doc.nais.io/security/salsa/salsa/
Dev:
https://salsa.dev-gcp.nav.cloud.nais.io/projects/ffac79b2-2086-4103-bfd1-1099749fd00b (login med openid)
Prod
https://salsa.prod-gcp.nav.cloud.nais.io/
`#nais-announcements` 
https://nav-it.slack.com/archives/C01DE3M9YBV/p1686213842792209
Virker som at bygging av docker-image går fra 15 til 60s
https://github.com/navikt/familie-ef-sak/actions/runs/5219504825/jobs/9421412620

Legger til Supply Chain Levels for Software Artifacts (SLSA) 

---

src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/BeregningBarnetilsynUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/BeregningBarnetilsynUtilKtTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/RevurderingServiceIntegrationTest.kt

Skal vedtas i løpet av dagen, men merger nok på mandag

Nye maks-satser barnetilsyn fra 1. juli.

---

src/main/kotlin/no/nav/familie/ef/sak/vedlegg/DokumentinfoDto.kt
src/main/kotlin/no/nav/familie/ef/sak/vedlegg/VedleggService.kt

**Hvorfor?**
I [dokumentoversikt 2.0](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-11499) skal vi vise distribusjonsinformasjon om journalposter.

Skal sende med utsendingsinfo om journalpost til frontend

---

src/main/kotlin/no/nav/familie/ef/sak/vedlegg/DokumentinfoDto.kt
src/main/kotlin/no/nav/familie/ef/sak/vedlegg/VedleggService.kt

**Hvorfor?**
Dokumentets tema skal vises i dokumentoversikten
[Dokumentoversikt v2](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-11499)

Legg til tema for visning i frontend

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt

https://unleash.nais.io/#/features/strategies/familie.ef.sak.frontend.dokumentoversikt-link-til-dokument
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-11499)

Featuretoggle: Skal gi Mirja tilgang til å se dokumenter i prod for å sjekke at tilgangsstyring virker i dokumentoversikt

---

src/main/kotlin/no/nav/familie/ef/sak/AuditLogger.kt
src/test/kotlin/no/nav/familie/ef/sak/AuditLoggerTest.kt

Endringen er testet i preprod i familie-klage.
Endringen er gjort på forespørsel fra Roger Dybdal: https://nav-it.slack.com/archives/CH4NLKAR0/p1689077799460959

Auditlogger: Logg navn på produktområde slik at det er mer forståelig for bruker

---

src/main/kotlin/no/nav/familie/ef/sak/AuditLogger.kt
src/test/kotlin/no/nav/familie/ef/sak/AuditLoggerTest.kt

Ref: https://nav-it.slack.com/archives/CH4NLKAR0/p1689237228023819?thread_ts=1689077799.460959&cid=CH4NLKAR0

Bugfix: Fjerner en header som ikke lenger skal være med etter det ble lagt til navn på PO

---

pom.xml

Snyk har meldt om noen sårbarheter på avhengighetene, blant annet kotlin-versjonen

Oppdater avhengigheter

---

pom.xml

Vil oppdatere avhengigheter 
-> tester om alt flyr i preprod før evt. merging.

Vil oppdatere pom

---

pom.xml

Oppdater:
springdoc.version
mockk.version
prosessering.version
kontrakter.version
nav.security.version
Vil ikke henge etter.

Oppdater dependencies:

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseSteg.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseStegTest.kt

Vil rette skrivefeil og gjøre feilmelding litt lettere å lese.

Vil rette skrivefeil og gjøre feilmelding litt lettere å lese.

---

.deploy/unleash-apitoken-preprod.yaml

My-application er ikke et optimalt navn

Rettet navn på app i apitoken yaml

---

pom.xml

Kjørt: mvn versions:update-properties
Vil oppdatere pom

Kjørt: mvn versions:update-properties

---

pom.xml

Lagt til ny enum i årsak på avslag.

---

pom.xml

Oppdater versjon for:
- spring-boot
- kotlin
- kontrakter
- sonar-maven-plugin

Oppdater dependencies

---

src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdController.kt
src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdReplikaClient.kt
src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdService.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt

Ønsker å legge til endepunkt for å hente ut åpne saker så vi slipper hente ut data direkte fra db hver gang vi trenger disse tallene. 
infotrygd:
https://github.com/navikt/familie-ef-infotrygd/pull/20
test fra preprod:

Infotrygd rapport

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/vilkår/VurderingService.kt

Skal bruke riktig toggle for gjenbruk av vilkår på tvers av behandlinger

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt

klargjøring av nytt journalføringsbilde: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-3990

skal støtte toggling av visning for nytt journalføringsbilde

---

src/main/resources/db/migration/V141__konsistensavstemming_tidsplan_2024.sql

Datoer for konsistensavstemming 2024.
Slacktråd: https://nav-it.slack.com/archives/C01EH16LAD9/p1700809236086379

Datoer for konsistensavstemming 2024

---

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/søknad/domain/Søknadsverdier.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/SøknadsskjemaOvergangsstønadRepositoryTest.kt

[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-15811)

Må mappe verdien for dato påbegynt søknad - for alle tre stønader

---

src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/satsendring/BarnetilsynSatsendringScheduler.kt

Trenger å aktivere scheduler for logging av personer med makssatser. 
https://github.com/navikt/familie-ef-sak/blob/master/doc/BarnetilsynSatsendring_README.md
https://github.com/navikt/familie-ef-sak/pull/2474
https://github.com/navikt/familie-ef-sak/pull/2473
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-16102

Aktiverer scheduler for barnetilsynsatser

---

src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/satsendring/BarnetilsynSatsendringScheduler.kt
src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/satsendring/BarnetilsynSatsendringService.kt

Problemet er at payload alltid er lik. Bare fjerne sjekk om task finnes og alltid opprette task ?

Oppretter task uavhengig om den finnes fra før

---

src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/satsendring/BarnetilsynSatsendringScheduler.kt
src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/satsendring/BarnetilsynSatsendringService.kt
src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/satsendring/BarnetilsynSatsendringTask.kt

Fjerner leader-client sjekk, og legger til unik payload

---

src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/satsendring/BarnetilsynSatsendringService.kt

Fjerner LeaderClient

---

src/main/kotlin/no/nav/familie/ef/sak/brev/BrevClient.kt

Skal ta i bruk ny url mot familie-brev for generering av blankett. 
Henger sammen med PR i familie-brev:
* https://github.com/navikt/familie-brev/pull/586
Testet i preprod ✅

skal ta i bruk ny url mot familie-brev for generering av blankett

---

.github/workflows/codeql-analysis.yml
src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakPersonService.kt
src/main/kotlin/no/nav/familie/ef/sak/forvaltning/MinsideForvaltningsController.kt
src/main/kotlin/no/nav/familie/ef/sak/minside/MikrofrontendEnableBrukereTask.kt

Trenger å sende over alle nåværende personer i ef-sak over til kafka-kø for minside.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-17429

Skal sende over alle tidligere personer til kafka-kø for minside

---

.deploy/azure-ad-app-lokal.yaml
.deploy/preprod.yaml
.deploy/prod.yaml
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/config/SwaggerDocumentationConfig.kt
src/main/resources/application-dev.yml
src/main/resources/application.yml
src/test/resources/application-integrasjonstest.yaml
src/test/resources/application-local.yml

Swagger
Ønsker å kunne logge inn med sso 
Ønsker å kunne filtrere på forvaltnings endepunkt (andre?):
Testet i preprod:

Swaggerforbedringer

---

src/main/resources/application.yml

Vil beholde autentisering ved refresh av swagger-side (f.eks. ved bruk av filter)

Vil beholde autentisering ved refresh av swagger-side

---

.github/dependabot.yml

Vil bytte ut personlig token med READER_TOKEN

Bytt ut personlig nøkkel med READER_TOKEN

---

.deploy/preprod.yaml

Senker cpu-behovet for preprod

---

.deploy/preprod.yaml
.deploy/prod.yaml
src/main/kotlin/no/nav/familie/ef/sak/ekstern/minside/EksternMinsideController.kt
src/main/kotlin/no/nav/familie/ef/sak/ekstern/minside/EksternMinsideService.kt
src/main/kotlin/no/nav/familie/ef/sak/ekstern/minside/MineStønader.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/sikkerhet/SikkerhetContext.kt
src/main/resources/application.yml
src/test/kotlin/no/nav/familie/ef/sak/OppslagSpringRunnerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/ekstern/minside/EksternMinsideControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/felles/util/TokenUtil.kt
src/test/resources/application-integrasjonstest.yaml
src/test/resources/application-local.yml

Søknad-api skal ha tilgang til å hente ut utbetalingsperioder (stønadsperioder) for innlogget bruker på vegne av familie-ef-minside

Minside controller

---

Dockerfile

Det virker unødvendig å ha egen distro inkludert i docker image, da dette er overflødig og gir potensielt mange sikkerhetshull.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-16237

Distroless

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/RevurderingsController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/VurderingService.kt
src/test/kotlin/no/nav/familie/ef/sak/vilkår/VurderingServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vilkår/VurderingStegServiceTest.kt

Må merge [frontend](https://github.com/navikt/familie-ef-sak-frontend/pull/2707) før backend 
Viktig å rydde opp etter oss!

Skal fjerne toggles som ikke er i bruk

---

src/main/kotlin/no/nav/familie/ef/sak/vedlegg/VedleggController.kt

Ikke i bruk. Bør ikke tas i bruk.

Vil slette deprecated endepunkt med personident i url

---

.deploy/preprod.yaml
.deploy/prod.yaml

Justere cpu og minnebehov

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/sikkerhet/SikkerhetContext.kt
src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalpostClient.kt
src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveClient.kt
src/main/kotlin/no/nav/familie/ef/sak/oppgave/TilordnetRessursService.kt
src/test/kotlin/no/nav/familie/ef/sak/felles/integration/JournalpostClientTest.kt
src/test/kotlin/no/nav/familie/ef/sak/oppgave/TilordnetRessursServiceTest.kt

Reverts navikt/familie-ef-sak#2569

Revert "Ta bort ersaksbehandler deprecated"

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/ByUserIdStrategy.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/sikkerhet/SikkerhetContext.kt
src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalpostClient.kt
src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveClient.kt
src/main/kotlin/no/nav/familie/ef/sak/oppgave/TilordnetRessursService.kt
src/test/kotlin/no/nav/familie/ef/sak/felles/integration/JournalpostClientTest.kt
src/test/kotlin/no/nav/familie/ef/sak/oppgave/TilordnetRessursServiceTest.kt

Reverts navikt/familie-ef-sak#2574
Må sjekke om systembruker gjør kall i `ByUserIdStrategy` og isåfall returnere false

Revert "Revert "Ta bort ersaksbehandler deprecated""

---

.github/workflows/delete_packages.yml

Vil slette gamle pakker - vil teste med bare workflow_dispatch i starten
https://github.com/navikt/familie-ef-sak/pkgs/container/familie-ef-sak%2Ffamilie-ef-sak

Legg til workflow for å slette gamle images

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SendTilBeslutterSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/tilbakekreving/TilbakekrevingClient.kt
src/main/kotlin/no/nav/familie/ef/sak/tilbakekreving/TilbakekrevingController.kt
src/main/kotlin/no/nav/familie/ef/sak/tilbakekreving/TilbakekrevingService.kt
src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/TilbakekrevingClientTestConfig.kt
src/test/kotlin/no/nav/familie/ef/sak/tilbakekreving/TilbakekrevingServiceTest.kt

Rettet noen skrivefeil

---

src/main/kotlin/no/nav/familie/ef/sak/forvaltning/OppgaveOppryddingForvaltningsTask.kt

Må ha riktig sjekk på oppgavetype-enum - bruke value og ikke name

---

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/GrunnlagsdataPeriodeHistorikkOvergangsstønad.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/TidligereVedtaksperioderService.kt
src/main/kotlin/no/nav/familie/ef/sak/vilkår/dto/TidligereVedtaksperioderDto.kt
src/test/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/TidligereVedtaksperioderServiceTest.kt
src/test/resources/json/grunnlagsdata_v2.json

Det er mer nyttig å vise samordningsfradrag i stedet for aktivitet.
[Brukes i frontend her](https://github.com/navikt/familie-ef-sak-frontend/pull/2764#issuecomment-2127003595)

Siste periode med overgangsstønad

---

src/main/kotlin/no/nav/familie/ef/sak/beregning/Beregning.kt

Fordi folk skal få pengene sine :) 
Ref denne: https://www.regjeringen.no/no/aktuelt/okte-pensjoner-og-trygdeytelser/id3040388/#:~:text=Ny%20gjennomsnittlig%20G%20for%202024,%C3%B8kning%20blir%204%2C58%20prosent.

Skal ta i bruk nytt grunnbeløp

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/grunnbelop/dok/G-omregning-README.md

Oppdatert etterarbeidsliste for g-omregning

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/grunnbelop/dok/G-omregning-README.md

Oppdatere readme med sanksjonshåndtering

---

src/main/kotlin/no/nav/familie/ef/sak/vedtak/domain/Vedtak.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-20812

Skal ha eøs-familieytelse som en ekstra opsjon for samordningsfradrag

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
pom.xml
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/config/ApplicationConfig.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/config/WebConfig.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/sikkerhet/SikkerhetContext.kt
src/main/resources/application.yml
src/test/kotlin/no/nav/familie/ef/sak/OppslagSpringRunnerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/ekstern/minside/EksternMinsideControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/felles/util/TokenUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/OAuth2AccessTokenTestConfig.kt
src/test/resources/application-integrasjonstest.yaml
src/test/resources/application-local.yml

Vil oppdatere til spring-boot 3.3.0
Testet raskt i preprod - familie-ef-sak (behandlet og iverksatte sak). Testet min side - se periodere. 
Ps. Ikke sett på tokendings/kjøring lokalt.

Vil oppdatere til spring-boot 3.3.0

---

src/main/kotlin/no/nav/familie/ef/sak/beregning/skolepenger/SkolepengerMaksbeløp.kt

0 kr vises som makssats ved innvilgelse av skolepenger:
https://nav-it.slack.com/archives/C01087QRJ2U/p1717416173898299
Kan legge inn en enhetstest så fort jeg vet når på året disse satsene blir vedtatt

Legger inn makssats for skolepenger for 2024

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SendTilBeslutterSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/domain/Vedtak.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SendTilBeslutterStegTest.kt

- Sender med beslutterIdent i opprettGodkjennVedtakOppgave slik at samme beslutter som underkjente settes som ansvarlig for oppgaven
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-21182

Skal sende til samme beslutter som underkjente

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SendTilBeslutterSteg.kt

Skal ikke sette sette saksbehandler som beslutter.

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingPåVentService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/MigreringService.kt
src/main/kotlin/no/nav/familie/ef/sak/ekstern/EksternBehandlingController.kt

Ser litt på forslag fra sonar på ef-sak. Fikser noen småting.

La til const for "<ingen>" (ingen mappe) - hardkodet mange ganger

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/oppgave/dto/FinnOppgaveRequestDto.kt
src/test/kotlin/no/nav/familie/ef/sak/oppgave/FinnOppgaveRequestDtoTest.kt

Endrer sortering på oppgavesøk - samt setter limit til 300

---

pom.xml

Skal oppdatere kontrakter for å få med kreditorposteringer

---

src/main/resources/pdl/pdl-api-schema.graphql

Oppdaterer skjema (generert nytt) 
`{
"name": "pdl-api",
"schemaPath": "pdl-api-schema.graphql",
"extensions": {
"endpoints": {
"PDL GraphQL Endpoint": {
"url": "https://pdl-api.dev.adeo.no/graphql",
"headers": {
"user-agent": "familie-ef-sak"
},
"introspect": false
}
}
}
}`

Oppdaterer schema for graphql

---

src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakService.kt
src/test/kotlin/no/nav/familie/ef/sak/api/gui/SøkControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/InfotrygdReplikaMock.kt

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-22399
**Frontend PR**
https://github.com/navikt/familie-ef-sak-frontend/pull/2912

Sende brev uten fagsak

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringKlageService.kt
src/main/kotlin/no/nav/familie/ef/sak/klage/KlageController.kt
src/main/kotlin/no/nav/familie/ef/sak/klage/KlageService.kt
src/main/kotlin/no/nav/familie/ef/sak/klage/dto/OpprettKlageDto.kt
src/test/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringKlageServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/klage/KlageServiceTest.kt

Skal kunne sende med behandlingsårsak ved opprettelse av klagebehandling, dersom man har tilgang via feature-toggle.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-22595)

Klage uten brev

---

src/main/kotlin/no/nav/familie/ef/sak/forvaltning/AutomatiskMigreringController.kt
src/main/kotlin/no/nav/familie/ef/sak/forvaltning/ManuellGOmregningController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/migrering/InfotrygdPeriodeValideringServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/FeatureToggleMock.kt

Skal rydde vekk toggles som enten alltid har vært på, ikke er i bruk lenger eller er uaktuelle pga annen sjekk.

Opprydding av toggles som ikke er i bruk

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt

Fjern release-toggle. Ikke lenger i bruk.

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/InfotrygdPeriodeValideringService.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/migrering/InfotrygdPeriodeValideringServiceTest.kt

Reverts navikt/familie-ef-sak#2707

Revert "Skal tillate at Mirja migrerer saker tilbake til 2009"

---

src/main/kotlin/no/nav/familie/ef/sak/fagsak/SøkService.kt
src/main/kotlin/no/nav/familie/ef/sak/fagsak/dto/Søkeresultat.kt
src/test/kotlin/no/nav/familie/ef/sak/service/SøkServiceTest.kt

NB! pull request - ikke til master, men til branch [beboer-info-med-fagsak-person](https://github.com/navikt/familie-ef-sak/tree/beboer-info-med-fagsak-person)
Kanskje litt lettere å lese? 
Legger til lokal BarnAvBrukerDto for å slippe List<Pair<
Legger hentAllePersonerPåAdresse i en funksjon

Forslag til refaktorering??? 

---

src/main/kotlin/no/nav/familie/ef/sak/brev/BrevsignaturService.kt
src/main/kotlin/no/nav/familie/ef/sak/brev/FrittståendeBrevService.kt

[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-23146)

Generiske besluttersignaturer skal ha Nav og ikke NAV

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringHelper.kt
src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalpostController.kt
src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalpostService.kt
src/main/kotlin/no/nav/familie/ef/sak/journalføring/dto/OppdaterJournalpostMedDokumenterRequest.kt
src/test/kotlin/no/nav/familie/ef/sak/journalføring/JournalpostControllerTest.kt

[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-22633)
Oppretter et nytt endepunkt som lar oss oppdatere titler på et eller flere dokumenter tilknyttet en journalpost.
Man har også muligheten til å oppdatere logiske vedlegg på et eller flere dokumenter.

Endre dokumenttittel

---

src/main/kotlin/no/nav/familie/ef/sak/selvstendig/NæringsinntektKontrollService.kt

Mangler logging av antall måneder med vedtak.

Logg antall måneder med vedtak

---

src/main/kotlin/no/nav/familie/ef/sak/selvstendig/NæringsinntektDataForBeregningService.kt
src/main/kotlin/no/nav/familie/ef/sak/selvstendig/NæringsinntektKontrollForOppgaveTask.kt
src/main/kotlin/no/nav/familie/ef/sak/selvstendig/NæringsinntektKontrollScheduler.kt
src/main/kotlin/no/nav/familie/ef/sak/selvstendig/NæringsinntektKontrollService.kt
src/test/kotlin/no/nav/familie/ef/sak/selvstendig/NæringsinntektKontrollServiceTest.kt

Det ble poengtert i forrige PR at dette burde kjøre i tasks, i tilfelle noe feiler underveis: https://github.com/navikt/familie-ef-sak/pull/2742#discussion_r1892251970

Kontroll av næringsinntekt: Lag én task per oppgave slik at de kan kjøre uavhengig av hverandre

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt

skal permission toggle for visning av samværskalkulator

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/MigreringService.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/config/DatabaseConfiguration.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/KopierVedtakService.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/domain/Vedtak.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakBarnetilsynDto.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakDto.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/VedtakHistorikkService.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseStegBarnetilsynIntegrationTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseStegTest.kt
src/test/kotlin/no/nav/familie/ef/sak/beregning/BeregningBarnetilsynControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/domeneparser/VedtakDomeneParser.kt
src/test/kotlin/no/nav/familie/ef/sak/cucumber/steps/StepDefinitions.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/KopierVedtakServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/LagreVedtakControllerTest.kt
src/test/kotlin/no/nav/familie/ef/sak/vedtak/VedtakDtoUtil.kt
src/test/resources/vedtak/BarnetilsynInnvilgetUtenUtbetalingVedtakDto.json

[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-22026)
Har tidligere vært tilknyttet et spørsmål som har utgått og skal fjernes. Null verdi blir nå brukt til å identifisere om det er en behandlig opprettet i gammelt eller nytt format.

Endret slik at harTillegstønad er nullable

---

.deploy/prod.yaml

la til tilbakekreving-backend i outbound rules

---

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SendTilBeslutterSteg.kt
src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/SendTilBeslutterDto.kt
src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SendTilBeslutterStegTest.kt

[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-23750)
Skal oppdatere beskrivelse på godkjenne vedtak oppgave med merker fra frontend hvis det blir sendt med.

Merke godkjenne vedtak

---

src/main/kotlin/no/nav/familie/ef/sak/samværsavtale/SamværsavtaleService.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/samværsavtale/SamværsavtaleServiceTest.kt

Skal legge til Service-tester for SamværsavtaleService

Chore/tester samværsavtale

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/felles/util/DatoUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/iverksett/oppgaveforbarn/AktivitetspliktigAlderTest.kt
src/test/kotlin/no/nav/familie/ef/sak/iverksett/oppgaveforbarn/BarnFyllerÅrOppfølgingsoppgaveServiceTest.kt

Vil fjerne Jacoco - brukes ikke.

---

pom.xml

Oppdaterer prosessering for å unngå errors i prod

Får errors på task-endepunkt som ikke eksisterer etter en endring i prosessering

---

src/main/kotlin/no/nav/familie/ef/sak/samværsavtale/SamværsavtaleHelper.kt
src/main/kotlin/no/nav/familie/ef/sak/samværsavtale/SamværsavtaleService.kt
src/main/kotlin/no/nav/familie/ef/sak/samværsavtale/dto/JournalførBeregnetSamværRequest.kt
src/main/kotlin/no/nav/familie/ef/sak/samværsavtale/dto/SamværsavtaleDto.kt
src/test/kotlin/no/nav/familie/ef/sak/samværsavtale/SamværsavtaleHelperTest.kt
src/test/kotlin/no/nav/familie/ef/sak/samværsavtale/SamværsavtaleServiceTest.kt

Legger til oppsumering og notat med i journalføring for samvær. Endret på visningstekst for ukedager til å også ha med sum av samvær og "og" før siste samværs.visningsnavn.

Legge til notat og oppsumering i samvarsjournal

---

src/main/kotlin/no/nav/familie/ef/sak/brev/dto/FritekstBrevRequestMedSignatur.kt
src/main/kotlin/no/nav/familie/ef/sak/samværsavtale/SamværsavtaleService.kt
src/main/kotlin/no/nav/familie/ef/sak/samværsavtale/dto/JournalførBeregnetSamværRequest.kt

dokument for journalføring av samværsberegning skal ha annen signatur

---

src/main/kotlin/no/nav/familie/ef/sak/forvaltning/FerdigstillOppgavetypePåBehandlingTask.kt
src/main/kotlin/no/nav/familie/ef/sak/forvaltning/OppgaveforvaltningsController.kt

- Bruker path variabel i controller slik at man enkelt kan velge den aktuelle oppgavetypen i gui til swagger
- Oppgave skal feilregistreses i gosys, ikke ferdigstilles

Path variabel pa endepunkt og feilregistrering

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingController.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTask.kt

Endrer litt på koden som håndterer identer sendt fra ef-personhendelse. Prøver å holde logikk det samme, men bare litt mindre kode. 
Denne PRen er en del av en bredre oppgave og depender på denne → [PRen](https://github.com/navikt/familie-ef-personhendelse/pull/590).
Har ikke testet i prod, men dette gjøres snart.

Refaktorering av forsøk oppretting av behandle inntektsendring task

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/søknad/domain/SøknadsskjemaSkolepenger.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/søknad/mapper/DokumentasjonMapper.kt
src/main/kotlin/no/nav/familie/ef/sak/opplysninger/søknad/mapper/SøknadsskjemaMapper.kt
src/main/resources/db/migration/V154__utdanning_dokumentasjon.sql

Setter utdanningstilbud med data fra db

Mappe utdanning dokumentasjon

---

src/main/kotlin/no/nav/familie/ef/sak/amelding/InntektResponse.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingServiceTest.kt

lagt på filter for å fjerne ef ytelser på summering

---

.deploy/preprod.yaml
src/main/kotlin/no/nav/familie/ef/sak/FamilieAutentiseringTestController.kt

Jobber med å teste Texas 🤠  tokenbytte, samt rolle validering. Dette er en del av en generell implementasjon som sikkert forsvinner på sikt.

Autentisering token validering for testing

---

src/main/kotlin/no/nav/familie/ef/sak/FamilieAutentiseringTestController.kt

skal ta i mot request i test autentisering controller

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/behandling/OppgaveBeskrivelse.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/henlegg/HenleggBehandlingController.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/henlegg/HenleggService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/henlegg/SendTrukketSøknadHenleggelsesbrevTask.kt
src/main/kotlin/no/nav/familie/ef/sak/brev/BrevsignaturService.kt
src/main/kotlin/no/nav/familie/ef/sak/brev/FrittståendeBrevService.kt
src/main/kotlin/no/nav/familie/ef/sak/næringsinntektskontroll/NæringsinntektKontrollBrev.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/HenleggServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/brev/BrevsignaturServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/service/VedtaksbrevServiceTest.kt

Reverts navikt/familie-ef-sak#2839

Revert "Oppdatere brevsignaturer"

---

pom.xml
src/main/kotlin/no/nav/familie/ef/sak/behandling/OppgaveBeskrivelse.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/henlegg/HenleggBehandlingController.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/henlegg/HenleggService.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/henlegg/SendTrukketSøknadHenleggelsesbrevTask.kt
src/main/kotlin/no/nav/familie/ef/sak/brev/BrevClient.kt
src/main/kotlin/no/nav/familie/ef/sak/brev/BrevsignaturService.kt
src/main/kotlin/no/nav/familie/ef/sak/brev/FrittståendeBrevService.kt
src/main/kotlin/no/nav/familie/ef/sak/brev/VedtaksbrevService.kt
src/main/kotlin/no/nav/familie/ef/sak/næringsinntektskontroll/NæringsinntektKontrollBrev.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/HenleggServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/brev/BrevsignaturServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/BrevClientMock.kt
src/test/kotlin/no/nav/familie/ef/sak/klage/KlageServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt
src/test/kotlin/no/nav/familie/ef/sak/service/VedtaksbrevServiceTest.kt

Reverts navikt/familie-ef-sak#2841

Oppdatere brevsignaturer v2

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/RevurderingService.kt

Merkes ved testing at tasker ikke blir opprettet

Bugfix: Fjern leader-sjekk som kan hindre oppretting av task

---

.github/workflows/build-dev.yml
.github/workflows/codeql-analysis.yml
.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-unleash-api-token-preprod.yaml
.github/workflows/deploy-unleash-api-token-prod.yaml

Vil pinne actions med ratchet

---

.deploy/preprod.yaml

Vil legge til veilarbportefolje i inbound i dev.

---

.deploy/preprod.yaml
.deploy/prod.yaml

Vil legge til observability

---

src/main/kotlin/no/nav/familie/ef/sak/beregning/Beregning.kt

Vil legge inn ny G for 2025.

---

src/main/kotlin/no/nav/familie/ef/sak/beregning/Beregning.kt

https://www.nav.no/grunnbelopet

Fix - korrekt beløp gjennomsnittPerÅr på nytt grunnbeløp.

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTask.kt

Det var ikke oppdatert med rett kode for den delen som skal skje dersom featuretoggle for automatisk revurdering er av

Bugfix i logging-delen av automatisk revurdering

---

src/main/kotlin/no/nav/familie/ef/sak/amelding/ekstern/AMeldingInntektClient.kt

Feilet ved henting av inntekt i prod

Hent inntekt gjennom proxy igjen

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTask.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingEtterGOmregningTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt
src/test/kotlin/testutil/GOmregningsperiodeHelper.kt

Skiller nå mellom forventet inntekt før og etter g omregning i tekst for automatisk inntektsendring

---

src/main/kotlin/no/nav/familie/ef/sak/amelding/InntektResponse.kt
src/test/kotlin/no/nav/familie/ef/sak/amelding/InntektResponseTest.kt
src/test/kotlin/no/nav/familie/ef/sak/amelding/InntektServiceTest.kt
src/test/resources/json/inntekt/InntektFastlønnMedEnMånedMedKunFeriepenger.json
src/test/resources/json/inntekt/InntektGenerellResponse.json

[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-25531)

Ved beregning av forventet inntekt skal hovedsaklig ikke feriepenger tas med

---

.github/workflows/deploy-prod.yml

Fikser en bug fra forrige merge

Bugfix: deploy prod

---

.github/workflows/deploy-prod.yml

Tror referanse til steps i stedet for needs burde kunne fikse det.

Forsøker på bugfix: Build er ikke lenger i "needs" i prod-deploy steget og er trolig årsak til feil ved deploy til prod.

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTask.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingEtterGOmregningTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTaskTest.kt

[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-25150)

Lagt til funksjon for å sammenslå inntektsperioder med lik inntekt, rettet opp i feilende tester

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTask.kt
src/main/kotlin/no/nav/familie/ef/sak/næringsinntektskontroll/NæringsinntektKontrollService.kt

Logger likt som kjøringen av automatisk revurdering av inntekt

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTask.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingEtterGOmregningTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/GOmregningTestUtil.kt

Bruk nyeste inntektsperiode der fom-dato er lik.

Håndterer at to siste vedtak har samme fra og med dato. 

---

src/main/kotlin/no/nav/familie/ef/sak/amelding/InntektResponse.kt

Det må avklares om dette er godt nok når funksjonelle er tilbake fra ferie. Det kan hende at introduksjonsstønaden må medberegnes hvis det finnes tilfeller av brukere med inntekt ved siden av introduksjonsstønaden.

Introduksjonsstønad skal ikke redusere utbetaling av OS

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/henlegg/HenleggService.kt
src/main/kotlin/no/nav/familie/ef/sak/forvaltning/OppgaveforvaltningsController.kt
src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveRepository.kt
src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveService.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/HenleggServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/service/OppgaveServiceTest.kt

Fikser feil i prod hvor en behandling ikke er i synk med oppgavesystemet.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-25801)

Nytt forvaltningsendepunkt som synkroniserer oppgaver i oppgavesystemet basert på behandlingens status

---

src/main/kotlin/no/nav/familie/ef/sak/forvaltning/OppgaveforvaltningsController.kt
src/main/kotlin/no/nav/familie/ef/sak/forvaltning/SynkOppgaveForBehandlingTask.kt

Oppfølging til kommentar: https://github.com/navikt/familie-ef-sak/pull/2973#discussion_r2253537653
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-25801)

Synk oppgave må gjøres som task for å få rettigheter til å kalle oppgave-systemet med maskin-token

---

src/main/kotlin/no/nav/familie/ef/sak/forvaltning/SynkOppgaveForBehandlingTask.kt

task skal initialiseres med riktig behandlingId

---

src/main/kotlin/no/nav/familie/ef/sak/forvaltning/OppgaveforvaltningsController.kt

Vil legge til beskrivelse på forvaltningsendepunkt - logg oppgave.

---

src/main/kotlin/no/nav/familie/ef/sak/forvaltning/IverksettProxyTaskForvaltningController.kt

Hack for å kunne kalle på iverksett forvaltningsrutine på en enkel måte med forvaltning-rolle

Iverksett forvaltning proxy

---

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt
src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt

Legger til toggle for å vise beregningsskjema i frontend

---

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTask.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/RevurderingService.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingEtterGOmregningTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTaskTest.kt

[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-26136)

Endret taskpayload for BehandleAutomatiskInntektsendringTask til å ta årMåned istendenfor ukeÅr

---

src/main/kotlin/no/nav/familie/ef/sak/amelding/InntektResponse.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingInntektsbegrunnelse.kt
src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTask.kt
src/test/kotlin/no/nav/familie/ef/sak/amelding/InntektResponseTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingEtterGOmregningTest.kt
src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingServiceTest.kt
src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt

Erstatter PR https://github.com/navikt/familie-ef-sak/pull/3018 da jeg fikk problemer med at noen commits ikke var verified.

Tar ikke med styrehonorar ved beregning av FI.
