navikt/familie-ef-sak

src/main/kotlin/no/nav/familie/ef/sak/api/PersonInfoController.kt, src/main/kotlin/no/nav/familie/ef/sak/config/IntegrasjonerConfig.kt, src/main/kotlin/no/nav/familie/ef/sak/integration/FamilieIntegrasjonerClient.kt, src/main/kotlin/no/nav/familie/ef/sak/integration/dto/personopplysning/relasjon/Familierelasjon.kt, src/main/kotlin/no/nav/familie/ef/sak/service/PersonService.kt, src/main/resources/application.yml, src/test/kotlin/no/nav/familie/ef/sak/api/PersonInfoControllerTest.kt, src/test/kotlin/no/nav/familie/ef/sak/config/FamilieIntegrasjonerMock.kt
PR = forslag. 
Bruker Ressurs i controller (personinfo). Vil gjerne snakke om dette. Forenkler arbeid i frontend. 
ResponseEntity<Ressurs<PersonhistorikkInfo>>, eller <Ressurs<PersonhistorikkInfo>>, eller <PersonhistorikkInfo> -> hva med error handler? 
La på fomDato og tomDato -> 5år siden til nå. Er dette nok? Vil foreslå en endring til familie-integrasjoner, men løser det slik her. 
Endringene med Ressurs og requestparams i client fører også til endringer endringer i tester og mock
=> Ressurs test

src/main/kotlin/no/nav/familie/ef/sak/api/dto/PersonIdent.kt, src/main/kotlin/no/nav/familie/ef/sak/api/gui/PersonInfoController.kt, src/main/kotlin/no/nav/familie/ef/sak/validering/Persontilgang.kt, src/main/kotlin/no/nav/familie/ef/sak/validering/Persontilgang2.kt, src/main/kotlin/no/nav/familie/ef/sak/validering/PersontilgangConstraint.kt, src/test/kotlin/no/nav/familie/ef/sak/validering/PersontilgangTest.kt
ba-sak bruker `personIdent` i body, muligens vi burde bruke noe annet? Hva tenker dere? 
Det er nog mulig å endre PersonIdentDto til å være ett interface og bruke på flere olike DTO's
=> Bruk body istedet for header når man skal sende inn personident

pom.xml, src/main/kotlin/no/nav/familie/ef/sak/config/IntegrasjonerConfig.kt, src/main/kotlin/no/nav/familie/ef/sak/integration/FamilieIntegrasjonerClient.kt, src/test/kotlin/no/nav/familie/ef/sak/api/PersonInfoControllerTest.kt, src/test/kotlin/no/nav/familie/ef/sak/config/IntegrasjonerConfigTest.kt
Tatt i bruk endepunkter som er endret fra get til post med personidenten som body i stedet for som request-header.
=> Oppdatert mot nye endepunkter for å hente personinfo i integrasjoner.

src/main/kotlin/no/nav/familie/ef/sak/api/gui/VurderingController.kt, src/main/kotlin/no/nav/familie/ef/sak/service/BehandlingService.kt, src/main/kotlin/no/nav/familie/ef/sak/service/VurderingService.kt, src/main/kotlin/no/nav/familie/ef/sak/service/steg/InngangsvilkårSteg.kt, src/main/kotlin/no/nav/familie/ef/sak/service/steg/StegService.kt, src/test/kotlin/ApplicationLocal.kt, src/test/kotlin/no/nav/familie/ef/sak/api/TestSakController.kt, src/test/kotlin/no/nav/familie/ef/sak/api/gui/VurderingControllerTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/VurderingServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/steg/InngangsvilkårStegTest.kt
Satt opp validering av inngangsvilkår som gir feil dersom det finnes inngangsvilkår som ikke er vurdert eller hvis det er inngangsvilkår som ikke har noen vurdering. Kobler det på stegservicen, så det er litt herk her med å få behandlingen i riktig steg før inngangsvilkår-steget kjører. Lagt inn en todo for det, så får vi se på registrering av personopplysninger ganske snart tenker jeg. 
Er nok behov for å utvide Ressurs med en "Valideringsfeil"-status + exception som ikke trigger alarmer, ref [denne slack-tråden](https://nav-it.slack.com/archives/CJN0STWB0/p1602052711069000). Men det får bli en "del 2" da det krever oppdatering av fellesbibliotek.
=> Validering av inngangsvilkår

src/main/kotlin/no/nav/familie/ef/sak/api/dto/InngangsvilkårDto.kt, src/main/kotlin/no/nav/familie/ef/sak/api/dto/SivilstandInngangsvilkårDto.kt, src/main/kotlin/no/nav/familie/ef/sak/mapper/SivilstandMapper.kt, src/main/kotlin/no/nav/familie/ef/sak/service/VurderingService.kt
**Innhold:**
- Legger til mapper og Dto for å kunne hente ut og vise data i `ef-sak-frontend`. Er en del av [denne](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-2195) oppgaven.
- Fjernet ÅrsakEnslig siden vi ikke trengte det i første omgang ref diskusjon på [Slack](https://nav-it.slack.com/archives/C01087QRJ2U/p1605533030088300)
=> Legg til Sivilstand inngangsvilkår mapper og Dto

src/main/kotlin/no/nav/familie/ef/sak/config/DatabaseConfiguration.kt, src/main/kotlin/no/nav/familie/ef/sak/mapper/SøknadsskjemaMapper.kt, src/main/kotlin/no/nav/familie/ef/sak/repository/domain/søknad/Aktivitet.kt, src/main/kotlin/no/nav/familie/ef/sak/repository/domain/søknad/UnderUtdanning.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/SøknadsskjemaOvergangsstønadRepositoryTest.kt
Embedded nullable db-objekter som inneholder collections vil smelle i deserialisering. Dette fordi collections blir en tom liste/set og derfor er ikke objektet null og "Kotlin blir sinna". Vi må følgelig trekke ut `tidligereUtdanning´ fra `UnderUtdanning` for at sistnevnte skal oppføre seg som vi ønsker mtp null/ikke-null. 
Samme utfordring finnes i Barnepass, men der er årsak nullable og vi får deserialisert Barnepass som et objekt med tom liste av banepassordninger og null i årsak. Ikke helt riktig oppførsel, men det smeller ikke. 
Andre/bedre løsningsforslag tas imot hvis noen brenner inne med en god idé.
=> Bug/deserialisering av søknad feiler

pom.xml, src/test/kotlin/no/nav/familie/ef/sak/integration/InfotrygdFeedClientTest.kt
Infotrygd ønsker att vi oppretter hendelser for alle identer til en person. Kommer en PR i ef-infotrygd-feed og
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-3344
https://github.com/navikt/familie-kontrakter/pull/264
=> Kontraktoppdatering - feedhendelser med liste av personens alle identer

src/main/kotlin/no/nav/familie/ef/sak/mapper/PersonopplysningerMapper.kt, src/test/kotlin/no/nav/familie/ef/sak/mapper/PersonopplysningerMapperTest.kt
Har lagt til sortering av adresser i PersonopplysningerMapper.
Oppdatert 'mapper pdlsøker til PersonopplysningerDto' test slik at rekkefølge på adresser blir også testet.
=> lagt til sortering av adresser

.deploy/nais.yaml
Dette gjør det mulig for applikasjonen å bruke mer CPU hvis det trengs, hvilket den trenger spesielt ved oppstart, ellers ligger den relativt lågt på ca 200m.
Hvis applikasjonen ikke får tilsrekkelig CPU blir den throttled, og blir langsammere, man kan se denne throttle på https://grafana.adeo.no/d/mWq3qJwMz/familie-ef-sak-svarstider?orgId=1&from=now-3h&to=now
```
Apr 6, 2021 @ 11:41:28.893 | Started ApplicationKt in 25.197 seconds (JVM running for 26.385)
-- | --
  | Apr 6, 2021 @ 11:41:17.273 | Started ApplicationKt in 28.638 seconds (JVM running for 30.048)
  | Apr 6, 2021 @ 11:40:00.421 | Started ApplicationKt in 23.36 seconds (JVM running for 24.571)
  | Apr 6, 2021 @ 11:35:21.681 | Started ApplicationKt in 41.422 seconds (JVM running for 43.654)
  | Apr 6, 2021 @ 11:34:20.919 | …
```
=> Endrer cpu limits til 1.5 CPU for raskere oppstart

src/main/kotlin/no/nav/familie/ef/sak/regler/evalutation/OppdaterVilkår.kt, src/main/kotlin/no/nav/familie/ef/sak/service/VurderingService.kt, src/test/kotlin/no/nav/familie/ef/sak/regler/evalutation/OppdaterVilkårTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/VurderingServiceTest.kt
Del av https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-3886
Handler om att for å kunne gå til neste steg, så må vi se på resultatet av alle vilkår. 
Då må resultatet for alle vilkår for aleneomsorg håndteres separat, dvs nesten en reduce for vilkårsresultat for aleneomsorg
https://www.figma.com/file/JEmXg4WqG0DFItNGpoX696/Skisser-EF-sak?node-id=3592%3A88776
=> Lagt til funksjonalitet for å utlede resultat for aleneomsorg

src/main/kotlin/no/nav/familie/ef/sak/api/beregning/Beregning.kt, src/main/kotlin/no/nav/familie/ef/sak/api/beregning/BeregningService.kt, src/main/kotlin/no/nav/familie/ef/sak/api/beregning/BeregningUtils.kt, src/main/kotlin/no/nav/familie/ef/sak/service/steg/BeregnYtelseSteg.kt, src/main/kotlin/no/nav/familie/ef/sak/util/Periode.kt, src/test/kotlin/no/nav/familie/ef/sak/api/beregning/BeregningServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/api/beregning/BeregningTest.kt, src/test/kotlin/no/nav/familie/ef/sak/api/beregning/BeregningUtilsTest.kt
Tar i bruk Periode i Beløpsperiode
Omskrivning av finnStartDatoOgSluttDatoForBeløpsperiode gjennom å ta i bruk metoderne definert for `Periode`
Laget tester for finnStartDatoOgSluttDatoForBeløpsperiode
=> Refaktorering av finnStartDatoOgSluttDatoForBeløpsperiode

src/main/kotlin/no/nav/familie/ef/sak/arena/ArenaPeriodeUtil.kt, src/main/kotlin/no/nav/familie/ef/sak/repository/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/service/BehandlingService.kt, src/main/kotlin/no/nav/familie/ef/sak/service/StønadsperioderService.kt, src/test/kotlin/no/nav/familie/ef/sak/arena/ArenaPeriodeUtilTest.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/BehandlingRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/StønadsperioderServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/økonomi/ØkonomiUtil.kt
Litt den samme query som Alexa la inn i https://github.com/navikt/familie-ef-sak/pull/713
Ble litt oppsplitting av periodeservice og ArenaPeriodeUtil, med flytt av de samme testene til ArenaPeriodeUtil
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-3307
=> Legger til uthenting av perioder fra vår base til arena

src/main/kotlin/no/nav/familie/ef/sak/api/beregning/VedtakService.kt, src/main/kotlin/no/nav/familie/ef/sak/repository/domain/Vedtak.kt, src/main/kotlin/no/nav/familie/ef/sak/service/steg/BeslutteVedtakSteg.kt, src/main/kotlin/no/nav/familie/ef/sak/service/steg/SendTilBeslutterSteg.kt, src/main/resources/db/migration/V51__saksbehandler_og_beslutter_ident_vedtak.sql, src/main/resources/db/migration/V52__migrer_vedtak_uten_saksbehandler_og_beslutter_ident.sql, src/test/kotlin/ApplicationLocal.kt, src/test/kotlin/no/nav/familie/ef/sak/service/steg/BeslutteVedtakStegTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/steg/SendTilBeslutterStegTest.kt
Vi har pr. nå ingen god måte å sjekke hvem som står som saksbehandler eller beslutter på et vedtak, uten å utlede det fra behandlingsshistorikk. Legger derfor til to felter på vedtaket for å ha dette eksplisitt. 
Dette skal bl.a. brukes for å vise brev uten å generere beslutter-signatur først.
=> Lagre saksbehandler og beslutter på vedtak

src/main/kotlin/no/nav/familie/ef/sak/api/gui/VedtaksbrevController.kt, src/main/kotlin/no/nav/familie/ef/sak/service/VedtaksbrevService.kt
Hent brev:
Hvis beslutterbrev er generert vis fram dette. Hvis beslutterbrev ikke er lagret - bruk opprinnelig saksbehandler request, lag brev, vis fram.
Dette for at saksbehandler 1, eller andre saksbehandlere uten beslutter-rolle skal kunne se hele behandlingen, inkludert brevet som er laget, også før beslutter har laget det endelige brevet.
=> "Hent brev" skal hente brev for saksbehandlere uten beslutterrolle 

src/main/kotlin/no/nav/familie/ef/sak/iverksett/SimuleringDto.kt, src/main/kotlin/no/nav/familie/ef/sak/iverksett/SimuleringService.kt, src/main/kotlin/no/nav/familie/ef/sak/service/BehandlingService.kt, src/test/kotlin/no/nav/familie/ef/sak/iverksett/SimuleringServiceTest.kt
Endrer kode til å sende simuleringDto med forrigeBehandlingId. 
Har oppdatert behandlingService med hentForrigeBehandlingId slik at vi kunne kalle service i stedet for repository
=> bruker forrigebehandlingId i simuleringDto

src/main/kotlin/no/nav/familie/ef/sak/service/BehandlingService.kt, src/main/kotlin/no/nav/familie/ef/sak/service/steg/FerdigstillBehandlingSteg.kt, src/main/resources/db/migration/V53__sett_behandlingsresultat_innvilget.sql, src/test/kotlin/no/nav/familie/ef/sak/service/BehandlingServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/steg/FerdigstillBehandlingStegTest.kt
Løser den lättare delen av denne [Vise korrekt behandlingsresultat](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-5360) som går ut på att oppdatere behandlingsresultat til `Innvilget` for alle behandlinger som har status `Ferdigstillt`og vedtaksresultat  `Innvilge`
=> Sett behandlingsresultat til Innvilget

src/main/kotlin/no/nav/familie/ef/sak/mapper/IverksettingDtoMapper.kt, src/main/kotlin/no/nav/familie/ef/sak/repository/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/repository/domain/Behandling.kt, src/main/kotlin/no/nav/familie/ef/sak/service/BehandlingService.kt, src/main/kotlin/no/nav/familie/ef/sak/service/RevurderingService.kt, src/main/kotlin/no/nav/familie/ef/sak/service/steg/BeregnYtelseSteg.kt, src/main/kotlin/no/nav/familie/ef/sak/simulering/SimuleringService.kt, src/main/kotlin/no/nav/familie/ef/sak/task/BehandlingsstatistikkTask.kt, src/main/kotlin/no/nav/familie/ef/sak/util/OpprettBehandlingUtil.kt, src/main/resources/db/migration/V59__behandling_forrige_behandling_id.sql, src/test/kotlin/no/nav/familie/ef/sak/iverksett/SimuleringServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/BehandlingRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt, src/test/kotlin/no/nav/familie/ef/sak/service/RevurderingServiceIntegrationTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/steg/BeregnYtelseStegTest.kt, src/test/kotlin/no/nav/familie/ef/sak/util/BehandlingOppsettUtil.kt, src/test/kotlin/no/nav/familie/ef/sak/util/OpprettBehandlingUtilTest.kt
Setter forrigeBehandlingId på en behandling for å ikke hente den fra databasen hele tiden. Kan også være fint for feilsøking hvis det er behov for det.
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-6285
noen typos blir fikset i https://github.com/navikt/familie-ef-sak/pull/827/files
Denne trenger en update i databasen etter merge. SQL kommer
=> Behandling forrige behandling

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseSteg.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/MellomlagringBrevService.kt, src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseStegTest.kt
For at vi skal få de nyeste verdiene i brevet sletter vi mellomlagring ved nye beregninger.
=> Skal slette mellomlagret brev ved lagring av nytt vedtak

src/main/kotlin/no/nav/familie/ef/sak/arbeidsfordeling/ArbeidsfordelingService.kt, src/main/kotlin/no/nav/familie/ef/sak/ekstern/arena/ArenaStønadsperioderService.kt, src/main/kotlin/no/nav/familie/ef/sak/felles/integration/FamilieIntegrasjonerClient.kt, src/main/kotlin/no/nav/familie/ef/sak/felles/kodeverk/CachedKodeverkService.kt, src/main/kotlin/no/nav/familie/ef/sak/felles/kodeverk/KodeverkClient.kt, src/main/kotlin/no/nav/familie/ef/sak/felles/kodeverk/KodeverkService.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/health/FamilieIntegrasjonHealth.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/sikkerhet/TilgangService.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/GrunnlagsdataService.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/PersonopplysningerIntegrasjonerClient.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/PersonopplysningerService.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/AdresseMapper.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/PersonopplysningerMapper.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/StatsborgerskapMapper.kt, src/main/kotlin/no/nav/familie/ef/sak/vilkår/MedlemskapMapper.kt, src/test/kotlin/ApplicationLocalPostgres.kt, src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/KodeverkServiceMock.kt, src/test/kotlin/no/nav/familie/ef/sak/mapper/StatsborgerskapMapperTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/ArbeidsfordelingServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/ArenaStønadsperioderServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/CachedKodeverkServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/GrunnlagsdataServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/KodeverkServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/PersonopplysningerServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/TilgangServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/VilkårGrunnlagServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/VurderingServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/VurderingStegServiceTest.kt
- Flytter koderverkkall fra FamilieIntegrasjonerClient til ny KodeverkClient i felles-pakken
- Flytter perosnopplysningskall fra FamilieIntegrasjonerClient til ny PersonopplysningerIntegrasjonerClient
=> Refaktorering pakkestruktur

src/main/kotlin/no/nav/familie/ef/sak/brev/BrevMellomlagerController.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/MellomlagerFritekstbrevRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/MellomlagringBrevService.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/domain/MellomlagretFritekstbrev.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/dto/MellomlagretBrevResponse.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/dto/MellomlagretBrevResponseDto.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/config/DatabaseConfiguration.kt, src/main/resources/db/migration/V69__mellomlagring_fritekstbrev.sql, src/test/kotlin/no/nav/familie/ef/sak/OppslagSpringRunnerTest.kt, src/test/kotlin/no/nav/familie/ef/sak/brev/MellomlagerFritekstbrevRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/MellomlagringBrevServiceTest.kt
Er nå to forskjellige endepunkt for mellomlagring av brev. Et for fritekstbrev og et for sanitybrev.
Men bruker fremdeles samme endepunkt for henting av mellomlagret brev. Det returnerer bl.a. en enum som er forskjellig for de to brevtypene.
=> Mellomlagring fritekstbrev

src/main/kotlin/no/nav/familie/ef/sak/brev/dto/FrittståendeBrevDto.kt
Forhåndsutfylte avsnitt, f.eks. avslutningstekst i fritekstbrevet burde ikke vises i brevbyggeren.
Knyttet til https://github.com/navikt/familie-ef-sak-frontend/pull/621
=> Legger til felt for å indikere om avsnitt skal skjules i brevbygger.

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/exception/ApiExceptionHandler.kt
Alternativt kan man logge packagename med første bokstaven i hver del, men tenker vi likevel har stacktrace i securelogs så det trengs ikke
=> Trenger ikke å logge packagename for className ved feil

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/AdresseHjelper.kt
Vi hadde noen tilfeller der en adresse uten noe dato kom først, som ble litt rart
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-4719
=> Skal sortere adresser uten datoer sist

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/GrunnlagsdataRegisterService.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/PersonopplysningerService.kt
Når vi oppdaterer vilkår med registergrunnlag må vi hente de på nytt, uten å bruke cacheade verdier.
Når vi henter personopplysinger til fagsak-siden så brukes cache sånn att vi ikke henter de unødvendig mange ganger
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7604
=> Flytter cache for personopplysninger.

pom.xml, src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/task/BehandlingsstatistikkTask.kt
Sender ekstern Id til iverksett for å kunne sende denne til dvh. Vi er ikke konsistente i Id-bruk mot dvh, og må sørge for at alle id-er er de eksterne.
=> Lagt til ekstern id for oversending til dhv.

src/main/kotlin/no/nav/familie/ef/sak/behandling/MigreringService.kt, src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/VentePåStatusFraIverksett.kt, src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/task/SjekkMigrertStatusIInfotrygdTask.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/MigreringServiceTest.kt
Oppretter en task som kjøres uavhengig av selve "behandlings-flytet", men som verifiserer att behandlinger er markert som opphørt i Infotrygd.
=> Migrering sjekk opphørt i infotrygd

src/main/kotlin/no/nav/familie/ef/sak/ekstern/arena/ArenaPeriodeUtil.kt, src/main/kotlin/no/nav/familie/ef/sak/ekstern/arena/ArenaStønadsperioderService.kt, src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdReplikaClient.kt, src/main/kotlin/no/nav/familie/ef/sak/infotrygd/PeriodeService.kt, src/test/kotlin/no/nav/familie/ef/sak/ekstern/arena/ArenaPeriodeUtilTest.kt, src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/InfotrygdReplikaMock.kt, src/test/kotlin/no/nav/familie/ef/sak/service/ArenaStønadsperioderServiceTest.kt
Først slåes de sammen for hvert type stønad, og senere slås de sammen tvers stønadstype.
Tar med perioder som har 0 i beløp, etter diskusjon med arena
https://nav-it.slack.com/archives/C01JAJ7HCBF/p1643199210010900
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7846
Dette blir bare logget i en første runde. Men har ikke så mye å si
=> Slår sammen perioder fra infotrygd og ny løsning.

src/main/kotlin/no/nav/familie/ef/sak/vedlegg/DokumentinfoDto.kt, src/main/kotlin/no/nav/familie/ef/sak/vedlegg/VedleggService.kt, src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/FamilieIntegrasjonerMock.kt
Manuelt skannede dokumenter bruker logiske vedlegg for å beskrive innholdet i det sammensatte dokumentet
=> Vil at logiske vedlegg skal sendes med dokumentinfo

.deploy/preprod.yaml, .deploy/prod.yaml, src/main/kotlin/no/nav/familie/ef/sak/brev/BrevClient.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/BrevsignaturService.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/FamilieDokumentClient.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/FrittståendeBrevService.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/VedtaksbrevService.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/domain/Vedtaksbrev.kt, src/main/resources/application.yml, src/main/resources/db/migration/V98__html_i_vedtaksbrev.sql, src/test/kotlin/no/nav/familie/ef/sak/OppslagSpringRunnerTest.kt, src/test/kotlin/no/nav/familie/ef/sak/brev/BrevsignaturServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/BrevClientMock.kt, src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/FamilieDokumentClientMock.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/VedtaksbrevRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/VedtaksbrevServiceTest.kt, src/test/resources/application-local.yml
Plan:
1. (Denne PR) Lagrer html av saksbehandlerbrev, lager pdf av html mot familie-dokument og bruker dette i besluttersteget.
2. Fullføre samme flyt for fritekstbrev
3. Vente til alle gamle brev er ute av loop (ferdig besluttet) 
4. Fjerne lagring av brevRequest (ikke lenger nødvendig) 
5. Forbedring av kode (flytte en del logikk ut av client til service, bedre validering i kontroller rett steg/status for forskjellige endepunkt) 
```mermaid
sequenceDiagram
sak-frontend->>sak-backend: saksbehandlerbrev(request): flettefelter, valgfelt, osv...
loop
sak-backend->>sak-backend: lag saksbehandler signatur
end
sak-backend->>familie-brev: brevrequest med signatur
loop
familie-brev-->>familie-brev: lag html med saksbehandlersignatur og placeholder for beslutter
end
familie-brev-->>sak-backend: …
```
=> Vil ikke regenerere brev fra saksbehnalder i besluttersteg.

src/main/kotlin/no/nav/familie/ef/sak/brev/BrevClient.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/VedtaksbrevService.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/domain/Vedtaksbrev.kt, src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakStegTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SendTilBeslutterStegTest.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/VedtaksbrevRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/VedtaksbrevServiceTest.kt
Opprydding etter ny brevflyt. https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8174
**VI har sjekket prod der ingen "gamle" vedtaksbrev ligger til beslutting**
Vi bruker nå feltet `saksbehandleHtml` istedenfor `saksbehandlerBrevrequest` og kan dermed fjerne feltet og koden som bruker dette.
Vi fjerner saksbehandlerBrevrequest fra databasen i egen PR.
=> Brevflyt opprydding

src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InternPeriode.kt, src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InternPeriodeUtil.kt, src/main/kotlin/no/nav/familie/ef/sak/infotrygd/PeriodeService.kt, src/test/kotlin/no/nav/familie/ef/sak/infotrygd/PeriodeServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt
Hvis ikke blir perioder som eventuellt blitt opphørt hos oss med, hvis saken er migrert
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8396
https://nav-it.slack.com/archives/G012YEK9YQ1/p1648627442859329
Hvis en person har blitt migrert fra Infotrygd , og då eks har perioder
01.2021 - 05.2021
Så blir den migrert, vi tar over 05.2021
Så blir 05.2021 opphørt
Då settes startdato i tilkjent ytelse til 05.2021, og vi har ingen andeler hos oss
Når man då henter perioder fra oss + infotrygd så avkortet vi tidligere ikke periodene fra 04.2021, men fikk med siste måneden.
=> Skal bruke startdato når man avkorter perioder fra infotrygd.

src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/MigreringService.kt, src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseSteg.kt, src/main/kotlin/no/nav/familie/ef/sak/beregning/BeregningController.kt, src/main/kotlin/no/nav/familie/ef/sak/blankett/VedtaBlankettSteg.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/config/ObjectMapperProvider.kt, src/main/kotlin/no/nav/familie/ef/sak/simulering/BlankettSimuleringsService.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakDto.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/MigreringServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseStegIntegrationTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseStegTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/StegServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/VedtaBlankettStegTest.kt, src/test/kotlin/no/nav/familie/ef/sak/beregning/BeregningControllerTest.kt, src/test/kotlin/no/nav/familie/ef/sak/beregning/VedtakServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/iverksett/SimuleringServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vedtak/VedtakDtoMapperTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vedtak/uttrekk/UttrekkArbeidssøkerServiceTest.kt, src/test/resources/vedtak/AvslåVedtakDto.json, src/test/resources/vedtak/OpphørVedtakDto.json, src/test/resources/vedtak/OvergangsstønadInnvilgetVedtakDto.json, src/test/resources/vedtak/SanksjonVedtakDto.json
Enhetstester på serialisering av forskjellige VedtakDto-klasser
Renaming til InnvilgelseOvergangsstønad som subclass av VedtakDto
Tanken er å ta i bruk 
```kotlin
/*@JsonTypeInfo(use = JsonTypeInfo.Id.NAME,
include = JsonTypeInfo.As.PROPERTY,
property = "_type")*/
```
Som kommer erstatte `VedtakDtoDeserializer` som idag serialisererer/deserialiserer basert på resultattype, som ikke er mulig når vi sen har flere ulike Innvilge (InnvilgelseOvergangsstønad/InnvilgelseBarnetilsyn), og alle er av samme `resultattype = ResultatType.INNVILGE`
=> Tar med _type i konstruktøren til VedtakDto.

.deploy/prod.yaml
Dette øker antall connections og, som idag er maks 25, og vi kan maks bruke 20-24 av disse
Pga att vi har en del transactions, som låser en connection og gjør eksterne kall så holder vi iblant på en connection litt lenge
Prodsettes etter arbeidstid då vi får nedetid vid endringer i databasen
=> Endrer til dedikert cpu og mer minne for databasen i prod.

src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/BeregningBarnetilsynService.kt, src/main/kotlin/no/nav/familie/ef/sak/felles/dto/Periode.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakBarnetilsynDto.kt, src/test/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/BeregningBarnetilsynServiceTest.kt
* Ingen utgiftsperioder
* Urelevant reduksjonsperiode (tilegg/kontantstøtte)
* Overlappende utgiftsperioder
* Overlappende kontantstøttePerioder
* Overlappende tilleggsstønadsperioder
Spørsmål:
Refaktorerte - flyttet ut datoer som ble brukt av alle testmetoder (BeregningBarnetilsynServiceTest). Beklager - dette kunne jeg gjort i en egen PR - skal jeg splitte? 
Skal jeg legge på @Nested  i BeregningBarnetilsynServiceTest, eller går det greit? Ganske mange tester der nå.
=> Kast brukerfeil hvis:

pom.xml, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/søknad/mapper/SøknadsskjemaMapper.kt
Oppdaterer kontrakt - fjern telefonnummer fra personalia fra søknad. 
Opprydding - (vi får ikke inn telefonnummer fra søknad - denne er fjernet fra kontrakter)
Versjon 1 - neste PR fjerner kolonne i db?
Spørsmål - beholde telefonnummer i database, eller fjerne? Vi bruker det ikke og kommer ikke til å få inn nye (etter mars 22).
=> Fjerner telefonnummer fra søknad

src/main/kotlin/no/nav/familie/ef/sak/tilbakekreving/TilbakekrevingService.kt
Denne kreves av tilbakekrving for å kunne vise vedlegg til varselbrev
=> Lagt til behandlingId på ForhåndsvisVarselbrevRequest.

src/main/kotlin/no/nav/familie/ef/sak/brev/VedtaksbrevService.kt, src/test/kotlin/no/nav/familie/ef/sak/service/VedtaksbrevServiceTest.kt
Som då er kode 6/7, då har man allerede fjernet placeholdern når man lager brevet
=> Skal ikke signere brev hvis det er skjulBeslutter

src/main/kotlin/no/nav/familie/ef/sak/ekstern/bisys/BisysBarnetilsynService.kt, src/test/kotlin/no/nav/familie/ef/sak/ekstern/bisys/BisysBarnetilsynServiceTest.kt
Fjerner unntak når det ikke finnes fagsak for person i ef, og returnerer tom liste i stedet, for å evt kunne hente bare infotrygdperioder
=> Fjerner unntak når det ikke finnes fagsak for person i ef

pom.xml
Erstatter:
- https://github.com/navikt/familie-ef-sak/pull/1563
- https://github.com/navikt/familie-ef-sak/pull/1562
- https://github.com/navikt/familie-ef-sak/pull/1561
- https://github.com/navikt/familie-ef-sak/pull/1560
- https://github.com/navikt/familie-ef-sak/pull/1540
- https://github.com/navikt/familie-ef-sak/pull/1516
- https://github.com/navikt/familie-ef-sak/pull/1515
- https://github.com/navikt/familie-ef-sak/pull/1514
Notere at spring-versjonen ble rullet tilbake, ønsker ikke x.x.0 versjonen nå
=> Dependabot oppdateringer 20220607-154731

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
=> Fjerner familie.ef.sak.frontend-vis-tilbakekreving. Ikke lenger i bruk.

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/ef/sak/ekstern/EksternBehandlingService.kt, src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringService.kt, src/test/kotlin/no/nav/familie/ef/sak/beregning/OmregningServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/ekstern/EksternBehandlingControllerTest.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/BehandlingRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/BehandlingServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/JournalføringServiceTest.kt
Fjerner finnSisteBehandling og erstatter med existsByFagsak for å ta ned antall komplekse queries
Det begynte som en opprydding av `harFørstegangsbehandlingEllerRevurderingFraFør` etter fjerning av blankett
=> BehandlingRepository - Fjerner queries som ikke er i bruk.

src/main/kotlin/no/nav/familie/ef/sak/vedtak/NullstillVedtakService.kt, src/test/kotlin/no/nav/familie/ef/sak/vedtak/NullstillVedtakServiceTest.kt
Etter at man har nullstilt vedtak A og deretter lagret et nytt vedtak B kommer brevet som ble startet på i vedtak A opp på brevsiden. Dett er ikke ønskelig og vi sletter derfor mellomlagring ved nullstilling av vedtak.
=> Vil slette mellomlagret brev nulstilling av vedtak.

pom.xml
Erstatter:
- https://github.com/navikt/familie-ef-sak/pull/1714
- https://github.com/navikt/familie-ef-sak/pull/1713
- ~https://github.com/navikt/familie-ef-sak/pull/1704~
- ~https://github.com/navikt/familie-ef-sak/pull/1703~
- ~https://github.com/navikt/familie-ef-sak/pull/1701~
- ~https://github.com/navikt/familie-ef-sak/pull/1690~
Flere av disse var allerede tatt inn, men der pr ikke var lukket
=> Dependabot oppdateringer 20220822-084839

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/mapper/BarnMatcher.kt
Ingen direkt endring på funksjonalitet, men liten forenkling og andre navn
```kotlin
barnMap.entries.firstOrNull { entry -> it.personIdent == entry.key }
```
blir til 
```kotlin
val matchetBarnPåFnr = grunnlagsbarnPåIdent[it.personIdent]
```
=> Barn matcher forenkling

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/mapper/BarnMedSamværMapper.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/pdl/PdlPerson.kt, src/main/kotlin/no/nav/familie/ef/sak/vilkår/dto/BarnMedSamværDto.kt, src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/PdlClientConfig.kt, src/test/kotlin/no/nav/familie/ef/sak/klage/KlageServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/pdl/PdlTestdata.kt, src/test/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/pdl/VegadresseTest.kt
Kan kalkulere alt i UTM-sone 32 med riktige verdier. Nord for dette krever vi avstand i nord-retningen på 1000 meter for at det skal bli ☑️
=> Kode for nære boforhold

src/main/kotlin/no/nav/familie/ef/sak/iverksett/oppgaveforbarn/GjeldendeBarnRepository.kt, src/test/kotlin/no/nav/familie/ef/sak/iverksett/oppgaveforbarn/GjeldendeBarnRepositoryTest.kt
Det har blitt etterlyst noen oppgaver som skulle vært opprettet på barn som har fylt 6 mnd og 1 år. Det viste seg at det ikke har blitt opprettet oppgaver dersom noen har kun andeler med 0-beløp. Ifølge Mirja var det interessant å få oppgaver selv om alle andeler har beløp 0.
=> Oppfølgingsoppgaver for behandlinger med andeler med 0-beløp

.deploy/azure-ad-app-lokal.yaml, .deploy/preprod.yaml, .deploy/prod.yaml, src/test/kotlin/ApplicationLocalPostgres.kt, src/test/resources/application-local.yml
Fungerer kun å kjøre lokalt dersom #FAMILIE_EF_IVERKSETT_URL: http://localhost:8094 er kommentert ut. 
Vi får vurdere å bytte port på en av appene dersom vi har behov for begge. Akkurat nå tenker jeg vi kan åpne for å kjøre klage?
=> Inbound outbound klage lokal

src/main/kotlin/no/nav/familie/ef/sak/ekstern/EksternVedtakController.kt
Då vi ikke har denne dataen lagret ned må saksbehandlingsblanketten hente informasjonen på nytt, som den gjør i en task
=> KlageBlankett kaller på endepunkt med maskintoken

src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/MigreringService.kt, src/main/kotlin/no/nav/familie/ef/sak/fagsak/MigreringController.kt, src/main/kotlin/no/nav/familie/ef/sak/fagsak/dto/MigreringInfo.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/MigreringServiceTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10254
Saksbehandleren kommer få opp en checkbox som den må godkjenne når en migrering feiler pga etterbetaling.
Koblet til draft (som mangler tekst):
* https://github.com/navikt/familie-ef-sak-frontend/pull/1712
=> Migrering ignorer etterbetaling

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/dto/PersonopplysningerDto.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/AdresseHjelper.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/AdresseMapper.kt, src/test/kotlin/no/nav/familie/ef/sak/mapper/AdresseHjelperTest.kt, src/test/resources/json/personopplysningerDto.json
- Kun bostedsadresse mapper erGjeldende, dette fordi vi ikke henter historisk på kontaktadresse og det viktigste er at vi viser hvilken bostedsadresse som er gjeldende, for å kunne vite hvor personen bor
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10403
=> Legger til erGjeldende på adresser

src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveClient.kt, src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveService.kt, src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/OppgaveClientMock.kt, src/test/kotlin/no/nav/familie/ef/sak/service/OppgaveServiceTest.kt, src/test/resources/json/simuleringsresultat_beriket.json
Tilretteleggjing for å fjerne toQueryParams-metoden, som fører med seg mykje unødig kompleksitet
Legg til rette for https://github.com/navikt/familie-kontrakter/pull/684
=> Definerer eksplisitt dei query-params som faktisk blir sendt inn for finnMappeRequest

src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/BeregningBarnetilsynUtil.kt
Vil ta i bruk nye max-satser for barnetilsyn. Nye maxsatser vil da bli brukt for alle nye vedtak med perioder i 2023 -> 
Skal ikke merges før vi har tatt ut rapport på gamle saker med innvilget barnetilsyn som treffer maxsats i januar 2023. Disse sakene må satsreguleres før januar. 
Nye max-satser står i Favro-oppgaven: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7888
=> Vil oppdatere max-satser for barnetilsyn for 2023 som nå er vedtatt.

src/main/kotlin/no/nav/familie/ef/sak/vedtak/PatchSanksjonController.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/VedtakRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/domain/Vedtak.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakDto.kt, src/test/kotlin/no/nav/familie/ef/sak/vedtak/PatchSanksjonControllerTest.kt
Lagt til patch for tidligere vedtak
Dette er noen av stegene som må gjøres (oppdateres i favro)
- Legge inn sanksjonsårsak i vedtaksperiode
- Patche data i ef-sak
~- Oppdatere domenemodell i iverksett~
~- Patche data i iverksett (forsiktig med periode-datoer her)~
~- Oppdatere kontrakter mot iverksett~
- Ta i bruk sanksjonsårsak fra vedtaksperiode
- Fjerne sanksjonsårsak fra vedtak
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8055
=> Lagrer sanksjonsårsak i vedtaksperioder

src/main/kotlin/no/nav/familie/ef/sak/iverksett/IverksettClient.kt, src/main/kotlin/no/nav/familie/ef/sak/iverksett/oppgaveterminbarn/ForberedOppgaverTerminbarnService.kt, src/main/kotlin/no/nav/familie/ef/sak/iverksett/oppgaveterminbarn/OpprettOppgaverTerminbarnService.kt
Liten småfiks på https://github.com/navikt/familie-ef-sak/pull/1945
Tenker det kan være fint å ikke sende med mappeId her, men å bruke enheten basert på dokumentasjonstypen
=> Oppgave terminbarn småfiks

README.md, doc/BarnetilsynSatsendring_README.md, src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/BeregningBarnetilsynUtil.kt, src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/satsendring/BarnetilsynSatsendringScheduler.kt, src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/satsendring/BarnetilsynSatsendringService.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/PdlSjekkController.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/KopierVedtakService.kt, src/test/kotlin/no/nav/familie/ef/sak/beregning/BeregningBarnetilsynUtilKtTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vedtak/KopierVedtakServiceTest.kt
Før det skal kjøres manuelle satsendringer i prod må det testes litt, og lages test caser som er virkelighetsnære med gamle satser. Denne PR'n gjør at det kan featuretoggles mellom gamle og nye satser i preprod for at det skal bli lett å teste.
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7888
=> Gammel sats som ikke-vedtatt for testing i preprod (er togglet)

pom.xml, src/main/kotlin/no/nav/familie/ef/sak/ekstern/EksternBehandlingController.kt, src/main/kotlin/no/nav/familie/ef/sak/ekstern/EksternVedtakService.kt, src/test/kotlin/no/nav/familie/ef/sak/ekstern/EksternVedtakServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/TilbakekrevingClientTestConfig.kt
En start på [denne oppgaven](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10592)
Tar i bruk `VedtakType` fra kontrakter, som kan være `SANKSJON_1_MND`
Har også tatt i bruk kontrakter i `familie-tilbake` og `familie-klage`:
* https://github.com/navikt/familie-tilbake/pull/959
* https://github.com/navikt/familie-klage/pull/218
=> fagsystemvedtak skal kunne vite om vedtakstypen er en sanksjon

src/main/kotlin/no/nav/familie/ef/sak/barn/BarnService.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/NyeBarnService.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/TestSaksbehandlingController.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt, src/test/kotlin/no/nav/familie/ef/sak/barn/BarnServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/NyeBarnServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/cucumber/steps/StepDefinitions.kt, src/test/kotlin/no/nav/familie/ef/sak/iverksett/oppgaveterminbarn/ForberedOppgaverTerminbarnServiceTest.kt
Jeg tenkte først at det var tilstrekkelig å kun ta med registerbarnen i https://github.com/navikt/familie-ef-sak/compare/skal-ikke-filtrere-vekk-barn-over-18?expand=1
Tenkte det hadde gjort koden mye enklere. 
Men så fikk jeg då selvfølgelig ikke med terminbarnen, så måtte gå for å endre eksisterende kode. Mulig det går å gjøre noen forenklinger senere
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9733
=> Ska ta med barn over 18 når man oppretter en ny behandling

.deploy/preprod.yaml, .deploy/prod.yaml, src/main/resources/application.yml
FAMILIE_INTEGRASJONER_SCOPE i application.yml blir overskrevet fra felles secrets, selv 
Vi har ikke behov for den, så tenker vi går bort fra den
=> Felles secrets skriver over properties vi har definiert

src/main/kotlin/no/nav/familie/ef/sak/behandling/domain/Behandling.kt, src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakSteg.kt, src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/StegService.kt, src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakStegTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/StegServiceTest.kt
Når status på behandlingen ikke samsvarer med aksjon får vi feil. 
f.eks: 
saksbehandler vil beslutte et vedtak som allerede er sendt til iverksett 
saksbehandler får feilmelding at hen "mangler rolle for å..." - som er helt riktig (skulle hatt systemrolle for å gjøre mer med denne) 
Nå ønsker vi gjøre sjekk av behandlingsstatus mot stegtype før rolle-sjekk for å få litt bedre feilmeldinger. 
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10757
=> Bedre feilmelding til saksbehandler når behandlingsvalidering feiler 

src/main/kotlin/no/nav/familie/ef/sak/behandling/domain/Behandling.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/domain/BehandlingStatusTest.kt
Del 1 for å kunne ha flere behandlinger åpne samtidig er å kunne sette en behandling på vent, og at denne ses som en låst behandling
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10514
=> Behandling skal være låst hvis status er satt på vent

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingController.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingPåVentService.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/dto/TaAvVentStatusDto.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/BehandlingPåVentServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/BehandlingServiceTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10514
All funksjonalitet er ikke klar, men et steg på veien
* Databasen tillater behandling PÅ_VENT og utredes samtidig (denne ble fjernet fra denne branch og blir egen PR)
* Hvis man må oppdatere forrigeBehandlingId så feiler det, dette håndteres i egen PR
Litt koblet til frontend-PR uten at vi ennå synket
* https://github.com/navikt/familie-ef-sak-frontend/pull/1951
=> Kan ta av vent

src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/AndelHistorikkBeregner.kt, src/test/resources/no/nav/familie/ef/sak/revurder_innvilg_med_sanksjon.feature, src/test/resources/no/nav/familie/ef/sak/sanksjon.feature
Oppgave [Tea-10708](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10708)
Tidligere ble revurderte sanksjonsperioder overskrevet og markert som fjernet. I historikken ble sanksjonen opprettet på nytt og fikk vedtaksdatoen til revurderingen.
=> Ikke fjern sanksjon i historikk om sanksjon fortsatt er gjeldende

docker-compose.yaml, src/test/kotlin/no/nav/familie/ef/sak/database/DbContainerInitializer.kt
```bash
docker-compose exec postgres pg_dumpall -U postgres > dump.sql
docker-compose down
docker volume rm familie-ef-sak_familie-ef-sak-data
docker-compose-up
echo "alter user postgres with password 'test';" >> dump.sql
docker-compose exec -T postgres psql -U postgres -d familie-ef-sak < dump.sql
```
=> Tar i bruk postgres v14 i tester

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
Kan merges etter https://github.com/navikt/familie-ef-sak-frontend/pull/2025 og https://github.com/navikt/familie-ef-sak-frontend/pull/2026 har vært ute en stund
=> Fjerner toggles som ikke lengre skal være i bruk

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/StegService.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/AngreSendTilBeslutterService.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/TotrinnskontrollService.kt, src/test/kotlin/no/nav/familie/ef/sak/service/TotrinnskontrollServiceTest.kt
Hvis man trykker på "angre send til beslutter" for fort etter at man har sendt behandlingen har ikke oppgaven blitt laget enda (typ hvis man trykker etter 2 sek). Derfor returneres det en litt mer spesifikk feilmelding til saksbehandler.
=> Oppdater feilmelding dersom godkjenne vedtak oppgave ikke finnes

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/domene/GrunnlagsdataDomene.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/dto/PersonopplysningerDto.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/GrunnlagsdataMapper.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/PersonopplysningerMapper.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/pdl/PdlPerson.kt, src/main/resources/pdl/søker.graphql, src/test/kotlin/no/nav/familie/ef/sak/felles/util/GrunnlagsdataUtil.kt, src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/PdlClientConfig.kt, src/test/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/endringer/UtledEndringerUtilTest.kt, src/test/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/pdl/PdlTestdata.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt, src/test/kotlin/testutil/PdlTestdataHelper.kt, src/test/resources/json/grunnlagsdata_v2.json, src/test/resources/json/personopplysningerDto.json, src/test/resources/json/søker.json
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10864
* https://github.com/navikt/familie-ef-sak-frontend/pull/2060
Hvis vi skal fjerne telefonnummer fra databasen så kan man kjøre
```sql
update grunnlagsdata set data = (data::jsonb #- '{søker, telefonnummer}');
```
=> Fjerner telefonnummer fra grunnlagsdata og fra data vi henter fra pdl

src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveClient.kt, src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveController.kt, src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveService.kt, src/test/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveControllerTest.kt
Oppgave [TEA-11403](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-11403)
Unngå at feil oppstår fordi SB ikke har den nyeste versjonen av en oppgave. 
Henger sammen med [PR-2089](https://github.com/navikt/familie-ef-sak-frontend/pull/2089) i ef-sak-frontend og [PR-788](https://github.com/navikt/familie-integrasjoner/pull/788) i familie-integrasjoner. 
- Gjør det mulig å sende inn versjon til endepunkter for fordeling og tilbakestilling
- Sender egen feilmelding dersom kall feiler pga. versjon 
- Fjernet logging av bytte av saksbehandler på oppgave. Denne informasjonen skal senere legges inn i beskrivelse (egen oppgave)
=> Oppgaver versjonshåndtering

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/AdresseHjelper.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/AndelHistorikkBeregner.kt, src/main/kotlin/no/nav/familie/ef/sak/vilkår/VurderingService.kt, src/main/kotlin/no/nav/familie/ef/sak/vilkår/dto/TidligereVedtaksperioderDto.kt, src/main/kotlin/no/nav/familie/ef/sak/vilkår/regler/Vilkårsregel.kt, src/main/kotlin/no/nav/familie/ef/sak/vilkår/regler/vilkår/NyttBarnSammePartnerRegel.kt, src/test/kotlin/no/nav/familie/ef/sak/beregning/OmregningServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/mapper/AdresseHjelperTest.kt, src/test/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/PersonopplysningerMapperTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/RevurderingServiceIntegrationTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/VurderingServiceIntegrasjonsTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/VurderingServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/VurderingStegServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/regler/GrafRendererTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/regler/evalutation/OppdaterVilkårTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/regler/vilkår/NyttBarnSammePartnerRegelTest.kt, src/test/resources/omregning/expectedIverksettDto.json
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-11396
Etter ny runde med avklaringer med funksjonelle, ble denne forenklet, da det kan være flere edge caser som kan være ganske omfattende å ta hensyn til. Blant annet personer som har hatt et registrert relasjon til barn, som ikke finnes lenger pga adopsjon. Denne PR'n er mer defensiv enn forrige PR, inntil det avklares av funksjonelle hvordan edge caser skal håndteres.
Forrige PR som nå er lukket: https://github.com/navikt/familie-ef-sak/pull/2101
=> MVP: Automatisk vurdering av Nytt barn samme partner.

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/mapper/BarnMedSamværMapper.kt, src/main/kotlin/no/nav/familie/ef/sak/vilkår/regler/vilkår/NyttBarnSammePartnerRegel.kt, src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/PdlClientConfig.kt, src/test/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/endringer/UtledEndringerUtilTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/regler/vilkår/NyttBarnSammePartnerRegelTest.kt
- 1 barn skal godkjennes
- Ikke ta hensyn til annen forelder for terminbarn, kun annen forelder på registerbarn
Testcaser skissert her: https://www.figma.com/file/U2lKxgydWDSpDTMVQDwuPH/Skisser-EF-Sak-2023?node-id=398%3A21880&t=b6h60rSa9xqkcQyr-0
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-11396
=> Støtte automatisk vurdering av flere caser:

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/PersonopplysningerMapper.kt, src/main/resources/pdl/forelder_barn.graphql
**Endring: deltBosted (historikk: true) ** 
Hent delt bosted som har historisk = true fra pdl. 
relatert til
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-10042
**Spørsmål jeg vil diskutere:** 
Jeg tror dette skal gå helt greit, men: Vil dette få noen sideeffekter jeg ikke ser? 
Grunnlagsdata fra behandlinger som allerede er opprettet ville fått en "endring har skjedd" dersom denne funksjonaliteten var skrudd på i prod?
Det likevel være liten sannsynlighet for at dette skulle skje (ikke sa mange saker som har delt bosted) 
Andre ting?  
**Hvorfor endring:** 
Etter mye fram og tilbake har vi bestemt oss for å vise fram historisk data her (kan være interessant for saksbehandler som f.eks skal revurdere bakover i tid) 
Det hjelper ikke å vise fram …
=> Hent historisk bosted fra pdl

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt, src/main/kotlin/no/nav/familie/ef/sak/vilkår/Vilkårsvurdering.kt, src/main/kotlin/no/nav/familie/ef/sak/vilkår/VurderingService.kt, src/main/kotlin/no/nav/familie/ef/sak/vilkår/VurderingStegService.kt, src/main/kotlin/no/nav/familie/ef/sak/vilkår/dto/VilkårsvurderingDto.kt, src/main/kotlin/no/nav/familie/ef/sak/vilkår/gjenbruk/GjenbrukVilkårService.kt, src/main/kotlin/no/nav/familie/ef/sak/vilkår/regler/evalutation/OppdaterVilkår.kt, src/main/resources/db/migration/V132__vilkårsvurdering_gjenbruk.sql, src/test/kotlin/no/nav/familie/ef/sak/beregning/OmregningServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/VilkårsvurderingRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/VilkårsvurderingTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/RevurderingServiceIntegrationTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/VurderingServiceIntegrasjonsTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/VurderingServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/VurderingStegServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/gjenbruk/GjenbrukVilkårServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/regler/evalutation/OppdaterVilkårTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-9688
Når vi gjenbruker et vilkår, både vid manuell revurdering og ved gjenbruk inngangsvilkår så skal vi ha en peker til den opprinnelige behandlinger som vilkåret ble kopiert fra.
Når man nullstiller eller endrer vilkåret så skal gjenbrukt nullstilles.
https://github.com/navikt/familie-ef-sak-frontend/pull/2159
=> Vilkårsvurdering gjenbruk

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/iverksett/IverksettClient.kt, src/main/kotlin/no/nav/familie/ef/sak/iverksett/arbeidsoppfolging/PatchArbeidsoppfølgingController.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/pdl/PdlPersonRequestVariables.kt, src/test/kotlin/no/nav/familie/ef/sak/iverksett/arbeidsoppfolging/PatchSendTilArbeidsoppfølgingTaskTest.kt
Opprettet patch-endepunkt som oppretter en task pr behandling med aktivt vedtak for overgangsstønad. Sender dette til iverksett som henter ut iverksettdata i sin database basert på behandlingId, og mapper og sender dette på topic til arbeidsoppfølging. Det trengs ingen filtrering på meldinger på personer med aktiv stønad som allerede er sendt, fordi de håndterer duplikate meldinger.
PR for endepunktet som blir kalt: https://github.com/navikt/familie-ef-iverksett/pull/696
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12219
=> Patch for å sende alle aktive vedtak til arbeidsoppfølging.

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/mapper/SivilstandMapper.kt, src/main/kotlin/no/nav/familie/ef/sak/vilkår/dto/SivilstandInngangsvilkårDto.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/VurderingServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/VurderingStegServiceTest.kt
Hvorfor er dette nødvendig? ✨ 
Trenger fødselsnummer for å kunne lenke brukers relasjon sin personoversikt, som er ønskelig i [favro-oppgave](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12152).
Henger sammen med [PR i ef-sak-frontend](https://github.com/navikt/familie-ef-sak-frontend/pull/2215)
=> Skal sende med fødselsnummer i sivilstandsregistergrunnlag

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/PersonopplysningerController.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/dto/PersonopplysningerDto.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/PersonopplysningerMapper.kt, src/test/kotlin/no/nav/familie/ef/sak/api/gui/PersonopplysningerControllerTest.kt, src/test/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/endringer/UtledEndringerUtilTest.kt, src/test/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/PersonopplysningerMapperTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/PersonopplysningerServiceTest.kt, src/test/resources/json/personopplysningerDto.json
- Fjerner endepunkter fra personopplysninger som ikke blir brukt
- Fjerner navEnhet (saksbehandlerenhet) fra PersonopplysningerDto som ikke blir brukt. 
[PR for å fjerne navenhet i frontend](https://github.com/navikt/familie-ef-sak-frontend/pull/2226)
[Opprydning som forarbeid til forbedring av uthenting av personopplysninger](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-7323)
=> Personopplysninger opprydding

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/task/OpprettOppgaveTask.kt, src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/task/OpprettOppgaveTaskTest.kt
[FAVRO](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12353)
Dersom man trykker på "Send til beslutter" raskt etter at man har angret har det blitt opprettet en task for å lage en behandleSakOppgave, men oppgaven er ikke laget enda. Dette gjør at oppgaven aldri blir lukket. 
Lagt inn en sjekk på behandlingsstatus dersom oppgavetype = behandle sak
=> Skal ikke opprette behandle sak oppgave dersom behandling er låst for videre redigering

src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/AndelHistorikkUtil.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/VedtakHistorikkBeregner.kt, src/test/kotlin/no/nav/familie/ef/sak/cucumber/steps/StepDefinitions.kt, src/test/resources/no/nav/familie/ef/sak/midlertidig_opphør.feature, src/test/resources/no/nav/familie/ef/sak/opphør.feature, src/test/resources/no/nav/familie/ef/sak/vedtak_fra_gitt_dato/vedtak_fra_dato.feature
* Revurderinger som begynner med midlertidig opphør har inntekt fra perioden etter opphøret, dvs man har ett hull av inntekt
* Vedtaksgrunnlaget blir ikke splittet når det vært g-omregning, sånn at sjekk på sammenhengende perioder må gjøres på andelen
https://nav-it.slack.com/archives/C033WGAFAQ1/p1681714431072339?thread_ts=1681710687.393229&cid=C033WGAFAQ1
Det begynte med at en saksbehandler fikk denne feilen når man gikk inn på vedtakshistorikken
> "Feil: Forventer å inneholde minimum en inntektsperiode som overlapper",
https://ensligmorellerfar.intern.nav.no/person/e0e26abb-f378-432e-9165-566f52bdf70e/vedtak
Det som feilet var att i https://github.com/navikt/familie-ef-sak/pull/2147 så splittes vedtaksperiodene opp mot inntektsperiodene, for å kunne få med riktige inntekter for dagsats …
=> Fikser feil koblet til å legge inn vedtaksgrunnlag i andelshistorikk

src/main/kotlin/no/nav/familie/ef/sak/fagsak/FagsakRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringKlageService.kt, src/main/kotlin/no/nav/familie/ef/sak/journalføring/OppdaterOppgaveTilÅGjeldeTilbakekrevingTask.kt, src/main/kotlin/no/nav/familie/ef/sak/journalføring/dto/JournalføringKlageRequest.kt, src/main/kotlin/no/nav/familie/ef/sak/klage/KlageService.kt, src/main/kotlin/no/nav/familie/ef/sak/oppgave/dto/OppgaveEfDto.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/VedtakHistorikkBeregner.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/historikk/VedtakHistorikkService.kt, src/test/kotlin/no/nav/familie/ef/sak/beregning/OmregningServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/FagsakRepositoryTest.kt
Opprettet ny test som viser at tilkjent ytelse med 0 beløp får oppdatert G
Pr nå er det 193 fagsaker med samordningsfradrag med utdatert G, fordi de ikke behandles i G-omregningen. Med denne endringen blir det ikke lenger opprettet G-omregning tasks for disse.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12348)
=> G-Omregning: Ikke lag tasks for fagsaker med samordningsfradrag

src/main/kotlin/no/nav/familie/ef/sak/vedtak/NullstillVedtakService.kt, src/test/kotlin/no/nav/familie/ef/sak/vedtak/NullstillVedtakServiceTest.kt
Ved "ta av vent", så kan vedtaket evt nullstilles , og derfor må også et mulig innslag av fremleggsoppgave slettes.
=> Slett innslag av fremleggsoppgave hvis vedtaket nullstilles

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingController.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/oppgavekontroll/BehandlingUtenOppgaveTask.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/oppgavekontroll/BehandlingsoppgaveService.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/oppgavekontroll/ÅpneBehandlingerUtenOppgaveScheduler.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt, src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveService.kt, src/main/kotlin/no/nav/familie/ef/sak/oppgave/dto/OppgaveEfDto.kt, src/main/resources/application.yml, src/test/kotlin/no/nav/familie/ef/sak/behandling/oppgavekontroll/BehandlingsoppgaveServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/BehandlingRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/FagsakRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/sak/tilbakekreving/TilbakekrevingClientTest.kt
Ønsker å finne åpne behandlinger uten oppgave. 
Løsning: 
Sjekker alle behandlinger som har vært åpne i mer enn to uker. Henter alle "behandle sak oppgaver" (BehandleSak,BehandleUderkjentVedtak,GodkjenneVedtak) og sjekker om det er noen av våre åpne behandlinger som ikke har en tilsvarende eksternid lagret i saksreferanse på en av oppgavene vi har hentet ut.  
Kjøres hver mandag med en ny task. 
Tasken vil feile dersom toggle er skrudd på og vi finner behandling uten oppgave.
=> Gamle åpne behandlinger uten oppgave

src/test/kotlin/no/nav/familie/ef/sak/service/RevurderingServiceIntegrationTest.kt
Ser i PR at test feilet uten at relevant kode er endret: https://github.com/navikt/familie-ef-sak/pull/2187
Det kan se ut til at db noen ganger returnerer barn nr 2 som første element i lista noen ganger. Lager en fix som filtrerer på hvilket barn som hentes ut.
=> Forsøk på å fikse test som feiler av og til

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingPåVentService.kt, src/test/resources/no/nav/familie/ef/sak/settPåVent/sett_behanlding_på_vent.feature
Når oppgave oppdateres via Sett på vent i EF Sak, må tekstbeskrivelsen legge seg før endringsinnslag i beskrivelseshistorikken. Til nå har endringsinnslagene kommet før saksbehandler beskrivelse
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12404)
=> Rekkefølge oppgavebeskrivelse ved sett på vent

src/main/kotlin/no/nav/familie/ef/sak/behandling/grunnbelop/GOmregningTask.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/grunnbelop/GOmregningTaskTest.kt
✨ **Hvorfor gjøres dette?** ✨ 
I teorien kan det være en g-omregning task som har blitt gjort for en fagsak rett før ny g-beregning. Siden fullførte tasks lever i tre mnd i db før de slettes, så kan det allerede finnes en task med samme fagsak i payload, og det vil dermed ikke g-omregnes fordi tasken allerede finnes. I denne PR'n legges nyeste grunnbeløpsmåned til i payload for at task blir ulik mellom hver g-omregning.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12360)
=> Oppretter task med nyeste grunnbeløpsmåned i payload for å sikre ulikhet på tasks ved ny g-omregning.

src/main/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapper.kt, src/test/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapperTest.kt
**Hvorfor gjør vi dette?**
Det er meldt inn en feil på teams der saksbehandler ikke fikk besluttet/iverksatt en behandling pga. utdatert G-måned. Behandlingen var et opphør og TilkjentYtelse var derfor ikke oppdatert med den nyeste G-måned. G-Måned/grunnbeløp brukes ikke til noen ting ved opphør, og det gir derfor ikke mening å oppdatere G-måned. Derfor velger vi å ikke validere G-måned dersom vedtaksresultatet er OPPHØRT.
=> Skal ikke validere G ved iverksetting av opphør

src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/InfotrygdPeriodeValideringService.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt, src/test/kotlin/ApplicationLocal.kt, src/test/kotlin/ApplicationLocalPostgres.kt, src/test/kotlin/no/nav/familie/ef/sak/OppslagSpringRunnerTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/migrering/InfotrygdPeriodeValideringServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/FeatureToggleMock.kt
**Hvorfor?** 
Vi har en sak i prod som saksbehandlere ønsker å revurdere (opphøre) hvor siste periode er mer enn 3 år gammel. Vi antar også at det kan komme flere slike med eøs. 
Vi ønsker derfor å åpne for at saksbehandlere på "toggle-liste" kan migrere slike 
https://unleash.nais.io/#/features/strategies/familie.ef.sak.tillat-migrering-5-ar-tilbake
Nå kun M. på denne lista.
Setter til 5 år etter diskusjon mer funksjonelle. 
Vil legge til rette for migrering av saker der infotrygd-periode mer enn 3 år bak i tid. Vil med denne endringen tillate opp til 5 år hvis saksbehandler i liste (toggle) hvor dette er tillatt.
Favro:
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12461
=> Vil legge til rette for migrering hvor siste periode i infotrygd er mer enn 3 år siden.

src/main/kotlin/no/nav/familie/ef/sak/behandling/grunnbelop/GOmregningTask.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/grunnbelop/GOmregningTaskService.kt, src/main/kotlin/no/nav/familie/ef/sak/beregning/Beregning.kt, src/main/kotlin/no/nav/familie/ef/sak/beregning/BeregningUtils.kt, src/main/kotlin/no/nav/familie/ef/sak/beregning/OmregningService.kt, src/main/kotlin/no/nav/familie/ef/sak/beregning/ValiderOmregningService.kt, src/main/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapper.kt, src/main/kotlin/no/nav/familie/ef/sak/tilkjentytelse/domain/TilkjentYtelse.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/grunnbelop/GOmregningTaskTest.kt, src/test/kotlin/no/nav/familie/ef/sak/beregning/BeregningTest.kt, src/test/kotlin/no/nav/familie/ef/sak/beregning/BeregningUtilsTest.kt, src/test/kotlin/no/nav/familie/ef/sak/beregning/GrunnbeløpsperioderTest.kt, src/test/kotlin/no/nav/familie/ef/sak/beregning/GrunnbeløpstestTest.kt, src/test/kotlin/no/nav/familie/ef/sak/beregning/OmregningServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/beregning/ValiderOmregningServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/økonomi/ØkonomiUtil.kt
**Hvorfor?**
Noen av testene våre vil feile når vi legger inn nytt grunnbeløp. Vi ønsker derfor å kunne mocke gjeldende/nyeste grunnbeløp i noen av testene våre. Med denne endringen kan vi gjøre:
```
mockObject(Grunnbeløpsperioder)
every {Grunnbeløpsperioder.nyesteGrunnbeløp } returns GrunnbeløpFor2021 // Kjør test
unmockObject(Grunnbeløpsperioder)
```
=> Refaktorering. Skal trekke ut grunnbeløp i eget objekt for å kunne mocke i tester

src/main/kotlin/no/nav/familie/ef/sak/behandlingshistorikk/domain/Behandlingshistorikk.kt, src/main/kotlin/no/nav/familie/ef/sak/vilkår/VurderingStegService.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/VurderingStegServiceTest.kt
Hilde ønsker at vi skal finne en måte å måle saksbehandlingstiden i ef-sak, og for å klare dette må vi vite når en behandling starter og slutter. I første omgang skal det ses på tiden fra SB "plukker" oppgaven, til den sendes til beslutter. Ettersom plukking av oppgaver ikke er så lett å måle har vi etter mye diskusjoner valgt "første vilkårsvurdering" som start og "sendt til beslutter" som slutt. 
OBS: dette er ikke målinger, bare data som skal samles inn for å kunne lage målinger.
Behandlingshistorikk inneholder nesten informasjonen som trengs, men mangler definisjonen av start for førstegangsbehandlinger fordi vi har kun informasjon om når behandlingen ble opprettet og når SB er ferdig med vilkårsvurderingen. Det er derfor lagt til et historikkinnslag for å få med tiden SB bruker på …
=> Skal lage historikkinnslag for å logge når utredning av behandling starter

src/test/resources/no/nav/familie/ef/sak/periode2_begynner_samtidig_som_forrige_første_periode.feature
**Hvorfor:** 
Uten endring feiler testene når vi får nye perioder etter innføring av ny G (mai-23, mai-24).
Vurderte å legge til forventede perioder gitt splitt i 23 og sette april 24 som stopp istedenfor 25.  
Det ville fungert, men det ble veldig fort mange perioder og tester ble vanskeligere å lese/forstå. 
Jeg mener vi fortsatt tester det vi ønsket å teste med april 2023 som "sisteperiode" her. 
Eksempel på stoppdato etter mai 2023: (første test)
I test 2 som nå har 6 historierader ville vi fått 16 (?)   
Testet lokalt med ny hypotetisk g for mai 23. Testene fungerer fint.
=> Vil at tester skal fungere etter at vi legger til ny G for mai 2023.

src/main/kotlin/no/nav/familie/ef/sak/karakterutskrift/AutomatiskBrevInnhentingKarakterutskriftService.kt, src/main/kotlin/no/nav/familie/ef/sak/karakterutskrift/KarakterutskriftBrevTask.kt, src/test/kotlin/no/nav/familie/ef/sak/karakterutskrift/KarakterutskriftBrevTaskTest.kt
Fortsettelse på [automatisk utsending av brev for innhenting av karakterutskrift](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-8258)
**Hvorfor denne endringen?**
Gjorde en dryRun i prod og fant 0 oppgaver i søket vårt 😢 Etter å se sett på oppgavelisten i prod med Mirja fant vi ut at vi ikke skal søke på behandlingstema skolepenger. De fleste oppgavene i mappen hadde tema overgangsstønad, og noen hadde ikke tema. Skal derfor bare søke etter alle oppgaver i mappen med riktig frist. Fjerner derfor også validering av at person har fagsak/ behandling på skolepenger.
=> Skal ikke bare søke etter oppgaver med behandlingstema skolepenger

src/test/kotlin/no/nav/familie/ef/sak/beregning/OmregningServiceTest.kt, src/test/kotlin/testutil/GOmregningsperiodeHelper.kt, src/test/resources/no/nav/familie/ef/sak/gomregning-av-løpende.feature
Skal bruke cucumber-testen til å sjekke med funksjonelle om de er enige i beregningen
=> Endret G-omregning tester til å bruke reell grunnbeløp for 2023

src/main/kotlin/no/nav/familie/ef/sak/karakterutskrift/AutomatiskBrevInnhentingKarakterutskriftController.kt, src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/OppgaveClientMock.kt, src/test/kotlin/no/nav/familie/ef/sak/karakterutskrift/AutomatiskBrevInnhentingKarakterutskriftControllerTest.kt
**Hvorfor?**
Legger til tester relatert til [automatisk utsending av karakterutskriftsbrev](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-8258).
Vil verifisere at tasks for utsending av karakterutskriftsbrev ikke blir opprettet når `liveRun = false`.
Fordi mapper/oppgaver er mocket gir det ikke så mye verdi å se på innholdet i de forskjellige taskene. Dette er hovedsaklig en ekstra sikkerthet mtp. liveRun/dryRun-logikk.
Oppdaget også en liten bug i validering av brevtype som fikses.
Kommer flere tester på service-nivå etter hvert 🤠
=> Controllertest av utsending av karakterutskriftsbrev

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/domene/GrunnlagsdataDomene.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/mapper/GrunnlagsdataMapper.kt, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/pdl/PdlPerson.kt, src/main/resources/pdl/pdl-api-schema.graphql, src/main/resources/pdl/søker.graphql, src/test/kotlin/no/nav/familie/ef/sak/felles/util/GrunnlagsdataUtil.kt, src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/PdlClientConfig.kt, src/test/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/pdl/PdlTestdata.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt, src/test/kotlin/testutil/PdlTestdataHelper.kt, src/test/resources/json/grunnlagsdata_v2.json, src/test/resources/json/søker.json
Hvorfor ? 
Feltet tilrettelagtKommunikasjon er ikke i bruk og bør derfor ikke hentes fra pdl. 
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12517
=> Fjerner felt for tilrettelagtKommunikasjon siden denne ikke er i bruk

src/main/kotlin/no/nav/familie/ef/sak/karakterutskrift/AutomatiskBrevInnhentingKarakterutskriftService.kt, src/main/kotlin/no/nav/familie/ef/sak/karakterutskrift/SendKarakterutskriftBrevTilIverksettTask.kt, src/test/kotlin/no/nav/familie/ef/sak/karakterutskrift/AutomatiskBrevInnhentingKarakterutskriftControllerTest.kt
Bugfix relatert til [utsending av karakterutskriftsbrev](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-8258)
**Hvorfor?**
Uten denne endringen vil alle tasker opprettet gjennom karakterutskriftcontrolleren ha samme callId. callId bør være unik for hver av av SendKarakterutskriftBrevTilIverksettTask'ene våre for å kunne spore en enkelt taskflyt gjennom sak/iverksett. Default oppførsel til Task er at den plukker ut callId fra log4j/mdc, og setter denne på tasken,  uavhengig av hva som sendes inn som properties. Derfor må denne verdien settes etter at tasken er opprettet.
=> Må sette callId på task etter task er opprettet for at denne ikke overskrives

src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/InfotrygdPeriodeValideringService.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/migrering/InfotrygdPeriodeValideringServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/FeatureToggleMock.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12828)
Identen til Mirja har behov for å få tilgang til å migrere en sak sju år tilbake i tid. 
```Saksbehandler har en sak fra 2017 som skal migreres. Vi har diskutert tidligere at vi ikke utvider tilgangen for alle ennå, men at Mirja migrerer de sakene.```
Lenke til ny feature toggle: 
https://unleash.nais.io/#/features/strategies/familie.ef.sak.tillat-migrering-7-ar-tilbake
=> identen til vår fagressurs skal kunne migrere saker sju år tilbake i tid

src/main/kotlin/no/nav/familie/ef/sak/karakterutskrift/AutomatiskBrevInnhentingKarakterutskriftService.kt, src/main/kotlin/no/nav/familie/ef/sak/karakterutskrift/SendKarakterutskriftBrevTilIverksettTask.kt, src/test/kotlin/no/nav/familie/ef/sak/karakterutskrift/AutomatiskBrevInnhentingKarakterutskriftControllerTest.kt, src/test/kotlin/no/nav/familie/ef/sak/karakterutskrift/AutomatiskBrevInnhentingKarakterutskriftServiceTest.kt
**Hvorfor?**
Vi har en unikhetsconstraint i task-tabellen på feltene ´oppgaveId´, ´brevtype´ og `gjeldendeÅr`. Derfor vil opprettelse av task feile dersom vi tidligere har opprettet for samme oppgave. Dette kan f.eks. skje dersom noen har verge, eller noe annet feiler i utsendelsflyten. Derfor vil vi sjekke om task er opprettet tidligere, sånn at den kan fortsette å opprette for de resterende oppgavene uten å feile først.
=> Skal sjekke om task allerede er opprettet for utsending av karakterutskriftsbrev

src/test/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapperTest.kt
**Hvorfor?**
2 Tester i master feiler fordi vi bruker grunnbeløp fra 2022 ved iverksetting.
=> Validering av grunnbeløp skal ikke feile i tester etter 14. juni

src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/satsendring/BarnetilsynSatsendringRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/satsendring/BarnetilsynSatsendringScheduler.kt, src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/satsendring/BarnetilsynSatsendringService.kt
**Hvorfor gjøres dette**
Første steg i satsendring er å finne kandidater til manuell satsendring, altså de sakene som har beløp over makssats. 
Ved første sjekk med spørring, ser det ut til at det ikke er noen aktuelle kandidater som gjelder fra 1. juli. Tasken som opprettes med denne endringen vil kunne finne kandidater nøyere enn med nevnte sql. Dersom tasken finner kandidater, vil disse gås gjennom med Mirja når hun er tilbake, og eventuelt satsendres manuelt.
Rutine for satsendring er beskrevet i readme: BarnetilsynSatsendring_README.md
=> Opprett task som finner fagsaker som er kandidater for satsendring

pom.xml, src/main/kotlin/no/nav/familie/ef/sak/brev/FrittståendeBrevService.kt, src/test/kotlin/no/nav/familie/ef/sak/brev/FrittståendeBrevServiceTest.kt
**Hvorfor?**
[Ved overgangen til frittstående sanitybrev](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12119) øsnker vi å kunne sende med brevtittel fra sanity, istedenfor å mappe om til en enum/brevtype. Dette gjør at Mirja kan kontrollere hva brevene skal hete i dokumentoversikten.
=> Skal sende med brevtittel ved utsending av frittstående brev

src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/BeregningBarnetilsynUtil.kt, src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/satsendring/BarnetilsynSatsendringService.kt, src/test/kotlin/no/nav/familie/ef/sak/cucumber/steps/StepDefinitions.kt, src/test/kotlin/no/nav/familie/ef/sak/felles/util/FeatureToggleTestUtil.kt, src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/FeatureToggleMock.kt
**Hvorfor?**
Slik at beregningen av ny andelshistorikk kan bruke nye satser til å sjekke om det er en diff mot gjeldende beløp. 
Resultatet av kjøringen som var uten denne endringen telte med alle barnetilsynsaker som var aktive i juli og fremover (44 stk) selv om alle var under maks-sats
=> Nytt forsøk: Sett sats som mest sannsynligvis vedtas i morgen i ikke gjeldende sats

src/main/kotlin/no/nav/familie/ef/sak/brev/BrevClient.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/BrevMellomlagerController.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/FrittståendeBrevController.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/FrittståendeBrevService.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/MellomlagerFritekstbrevRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/MellomlagerFrittståendeBrevRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/MellomlagerFrittståendeSanitybrevRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/MellomlagringBrevService.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/domain/MellomlagretFritekstbrev.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/domain/MellomlagretFrittståendeBrev.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/domain/MellomlagretFrittståendeSanitybrev.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/dto/FritekstBrevDto.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/dto/FritekstBrevKategori.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/dto/FrittståendeBrevDto.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/dto/FrittståendeBrevKategori.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/dto/FrittståendeBrevRequestDto.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/dto/FrittståendeSanitybrevDto.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/dto/MellomlagretBrevResponse.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/dto/VedtaksbrevFritekstDto.kt, src/main/resources/db/migration/V136__mellomlagring_frittstående_sanitybrev.sql, src/test/kotlin/no/nav/familie/ef/sak/OppslagSpringRunnerTest.kt, src/test/kotlin/no/nav/familie/ef/sak/brev/BrevMellomlagerControllerTest.kt, src/test/kotlin/no/nav/familie/ef/sak/brev/FrittståendeBrevServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/brev/MellomlagerFrittståendeSanitybrevRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/MellomlagringBrevServiceTest.kt
**Hvorfor?**
[Vi skal gå over til å bruke sanity for våre frittstående brev](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12119). Denne branchen legger til støtte for generering/forhåndvisning , utsending og mellomlagring av denne type brev.
PR på frontend kommer snart ⚡ 
**Hva gjenstår?**
- https://github.com/navikt/familie-ef-iverksett/pull/774 Må merges
- Endepunkter for lagring/henting av brevmottakere. Disse sendes  pr. np med ved utsending, men mellomlagres ikke.
- Slette gammel fritekst/frittstående-kode
=> Frittstående sanitybrev 💌 

src/main/kotlin/no/nav/familie/ef/sak/brev/BrevmottakereController.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/BrevmottakereService.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/FrittståendeBrevService.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/FrittståendeBrevmottakereRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/brev/domain/MellomlagretFrittståendeBrev.kt, src/main/resources/db/migration/V137__brevmottakere_frittstående_brev.sql, src/test/kotlin/no/nav/familie/ef/sak/OppslagSpringRunnerTest.kt, src/test/kotlin/no/nav/familie/ef/sak/brev/BrevmottakereServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/brev/FrittståendeBrevServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/brev/FrittståendeBrevmottakereRepositoryTest.kt
Hvis saksbehandler velger brevmottakere skal dette lagres, og ligge der også neste gang de åpner brevfanen. Dette var tidligere håndtert som en del av mellomlagringen av frittstående brev, men nå som vi går over til sanitybrev trenger vi egen funksjonalitet for dette.
=> Skal kunne lagre og hente brevmottakere for frittstående brev

src/main/kotlin/no/nav/familie/ef/sak/beregning/skolepenger/SkolepengerMaksbeløp.kt, src/test/kotlin/no/nav/familie/ef/sak/beregning/skolepenger/SkolepengerMaksbeløpTest.kt
Hvorfor? 
Nye maks-satser for skolepenger 23/24: 
Beløp må verifiseres av fag før vi prodsetter.
=> Skolepenger makssats2023

src/main/kotlin/no/nav/familie/ef/sak/beregning/skolepenger/SkolepengerMaksbeløp.kt, src/test/kotlin/no/nav/familie/ef/sak/beregning/skolepenger/SkolepengerMaksbeløpTest.kt
Hvorfor? 
Testene for skolepenger makssats ble litt dårligere etter at vi oppdaterte maks-sats for 2023. Prøver å legge inn nye tester for "neste år" som også skal fungere i årene som kommer. 
Vil også teste at vi oppdaterer makssats årlig og at vi oppdaterer både høyskole/universitet og videregående når vi nye år legges inn.
=> Skolepenge maks-sats tester

src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveClient.kt
**Hvorfor?**
Ved oppdatering av oppgaver, f.eks. når saksbehandler setter en behandling på vent, kan det feile mot oppgavesystemet fordi saksbehandler har en gammel versjon av oppgaven. Saksbehandler bør få beskjed om dette så de kan laste siden på nytt. Tidligere har vi bare vist "Uventet feil", og saksbehandler har da prøvd mange ganger uten å skjønne hva som går galt.
=> Skal gi feilmelding om versjonskonflikt ved oppdatering av oppgave

src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdService.kt
`hentSammenslåttePerioder` i familie-ef-infotrygd returnerer `BadRequest` dersom det ikke sendes med noen identer. Ettersom `pdlClient.hentPersonidenter` kun logger at man ikke finner personidenter må vi selv sjekke om identene som sendes til`infotrygdReplikaClient` ikke er tom.
=> Skal kaste feilmelding dersom ingen identer returneres fra PDL for henting av sammenslåtte perioder

.deploy/preprod.yaml, .deploy/prod.yaml
Anbefaling fra NAIS om at CPU throttle fjernes fra pod, men beholdes for requests: https://nav-it.slack.com/archives/C01DE3M9YBV/p1680172494569329
Artikkelen som det refereres til i meldingen fra NAIS beskriver godt hvorfor: 
https://home.robusta.dev/blog/stop-using-cpu-limits
Ser det har vært snakk om å bare fjerne dette for de største appene som det har mest å si for (ved oppstart), men tenker jeg gjør dette for alle appene når jeg først er i gang, da det er en såpass tydelig anbefaling fra nais-plattform.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12306)
=> Fjerner CPU throttle for pods, skal bare ha CPU limits for requests.

pom.xml, src/main/kotlin/no/nav/familie/ef/sak/beregning/skolepenger/BeregningSkolepengerService.kt, src/main/kotlin/no/nav/familie/ef/sak/beregning/skolepenger/BeregningSkoleårDtoer.kt, src/main/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapper.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/domain/Vedtak.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakSkolepengerDto.kt, src/test/kotlin/no/nav/familie/ef/sak/api/gui/VedtakControllerTest.kt, src/test/kotlin/no/nav/familie/ef/sak/beregning/skolepenger/BeregningSkolepengerServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapperTest.kt
**Hvorfor?**
Ved overgang til nytt UI skal saksbehandlere ikke lengre oppgi utgifter for skolepenger, bare stønadsbeløp. Vi må støtte nytt og gammelt UI samtidig så feltet kan derfor ikke fjernes.
[Favro oppgave](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12239)
**PS:** kan ikke merges før https://github.com/navikt/familie-ef-iverksett/pull/786 er merget
=> Utgifter for skolepenger skal være nullable og ikke sendes med til iverksetting/statistikk

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingPåVentService.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/BehandlingPåVentServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/OppgaveClientMock.kt
Skal oppdatere oppgaven med gjeldende saksbehandler som ansvarlig når en behandling tas av vent. 
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-13714)
Må deployes samtidig som https://github.com/navikt/familie-ef-sak-frontend/pull/2449
=> Ta av vent - sett saksbehandler på oppgave

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseSteg.kt, src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeregnYtelseStegTest.kt
For å unngå at saksbehandlere gjør feil i vedtak
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12792)
=> Skal validere vedtak ikke kan ha mer enn 4 måneder med periodetypen PERIODE_FØR_FØDSEL

src/main/kotlin/no/nav/familie/ef/sak/vilkår/regler/evalutation/OppdaterVilkår.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/regler/evalutation/OppdaterVilkårTest.kt
Dette blir spesielt relevant når man før inn saker for utenlandske borgere hvor barna ikke finnes i PDL og det skal gis avslag på andre grunnlag enn barna. Da er det ikke nødvendigvis ønskelig å rekvirere D-nr for noen som ikke skal ha en tilknytning til NAV og Norge
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-14251)
=> Skal tillate å avslå en behandling selv om det ikke finnes barn på behandlingen

doc/Nullstill_preprod_etter_datalast_README.md
Hvert halvår kjøres det datalast i q1 og vi må nullstille vår database. 
Legger inn script som sørger for å slette behandlinger med tilhørende data
=> Readme for script som kan kjøres etter datalast i preprod

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
Togglen brukes ikke her, eller i frontend.
=> Skal fjerne toggle for frittstånde brev som ikke er i bruk

src/main/kotlin/no/nav/familie/ef/sak/brev/BrevMellomlagerController.kt
Nyeste versjon av frontend skal ikke bruke dette endepunktet.
Kan merges om noen dager, når alle saksbehandlere har fått oppdatert versjon av frontend.
=> Skal fjerne deprecated endepunkt som ikke skal være i bruk

src/main/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapper.kt
Etter diskusjon med @ma10s. For å begrense antall behandlinger som må gomregnes forkorter vi tidsrommet vi tillater iverksetting med gammel G. Har også beskrevet denne valideringen litt mer i GOmregning-readme'en https://github.com/navikt/familie-ef-sak/commit/098fd19be5c883c406d30e97dd02c3c424ca8ec6
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-13587)
=> Skal ha strengere frist for gomregning for åpne behandlinger

src/main/resources/db/migration/V140__slett_mellomlager_frittstående_brev.sql
Frittstående brev er erstattet av sanitybrev, og koden som brukte denne tabellen er slettet i https://github.com/navikt/familie-ef-sak/pull/2328 🗑️
=> Slett tabell for deprecated mellomlagret frittstående brev

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingRepository.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/BehandlingRepositoryTest.kt
Vil ikke flagge behandling som "mangler oppgave" hvis oppgave for behandling er opprettet nylig. 
Vi prøver å finne åpne behandlinger som ikke har oppgave. 
Nåsituasjon:
Når vi sjekker dette i dag henter vi alle våre gamle behandlinger og alle gamle "behandle sak" oppgaver og sammenlikner. Dersom det nylig er laget en ny oppgave for behandlingen vil behandlingen bli flagget. Vi henter ikke "nyere" oppgaver.  
Ved f.eks: underkjent av beslutter lager vi ny BehandleSak oppgave. Disse finner ikke vi pga begrensninger i søk etter oppgaver. 
Vi ønsker å luke bort falske positive: behandlinger som er gamle, men hvor det er laget "ny" oppgave.   
Alternativ 1:
Vi beholder finn gamle behandlinger som i dag, men før vi flagger manglende oppgave sjekker vi konkret oppgave mot gosys. (Vi regner ikke …
=> Vil ikke flagge behandling som "mangler oppgave" hvis oppgave for behandling er opprettet nylig. 

src/main/kotlin/no/nav/familie/ef/sak/journalføring/dto/JournalføringRequest.kt
Det er ikke noen åpenbar grunn til at dette IKKE skal være tillatt. 
[Frontend](https://github.com/navikt/familie-ef-sak-frontend/pull/2506)
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-14609)
=> Skal tillate å journalføre ppapirsøknader på eksisterende behandlinger

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt, src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalpostClient.kt, src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveClient.kt, src/test/kotlin/no/nav/familie/ef/sak/felles/integration/JournalpostClientTest.kt
Featuretoggle for å feile internt i ef-sak dersom en utvikler prøver å hente ut informasjon fra joark eller oppgave. Dette for å unngå at kallene går videre og feiler med forbidden i de løsningene.
I produksjon har vi veiledertilgang til vår egen løsning, men ikke tilgang til oppgave, dokarkiv og andre omkringliggende løsninger. Derfor er det bedre at vi feiler på innsiden av vår løsning i disse tilfellene.
Alle med veilederrolle i prod bør inn i lista [her](https://unleash.nais.io/#/features/strategies/familie.ef.sak.utviklere-med-veilederrolle)
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-14379)
=> Feil ved uthenting av oppgave/journalpost for utviklere i prod

src/main/kotlin/no/nav/familie/ef/sak/ekstern/EksternBehandlingController.kt
familie-ef-personhendelse bruker endepunktet har-loepende-barnetilsyn, og vi ønsker å wrappe personidenten
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd
=> Trenger å wrappe personidenten for å unngå at den omsluttes av fnutter

src/main/kotlin/no/nav/familie/ef/sak/tilkjentytelse/AndelsHistorikkService.kt, src/main/kotlin/no/nav/familie/ef/sak/vilkår/VurderingService.kt, src/test/kotlin/no/nav/familie/ef/sak/tilkjentytelse/AndelsHistorikkServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/VurderingServiceIntegrasjonsTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/VurderingServiceTest.kt
Splittet refaktorering og PR - periodehistorikk i behandling. 
Flyttet aktivitetArbeidForBehandlingIds fra vurderingsservice til AndelsHistorikkService for å unngå dependency-loop.  
Vil bruke AndlesHistorikkService i TidligereVedtaksperioderService. Da vil det bli dependency-loop via Vurderingsservice som via omveier bruker TidligereVedtaksperioderService.
=> Flyttet aktivitetArbeidForBehandlingIds fra vurderingsservice 

src/main/kotlin/no/nav/familie/ef/sak/behandling/oppgavekontroll/BehandlingUtenOppgaveTask.kt, src/main/kotlin/no/nav/familie/ef/sak/beregning/ValiderOmregningService.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt, src/main/kotlin/no/nav/familie/ef/sak/vilkår/VurderingService.kt, src/main/kotlin/no/nav/familie/ef/sak/vilkår/gjenbruk/GjenbrukVilkårService.kt, src/test/kotlin/no/nav/familie/ef/sak/beregning/ValiderOmregningServiceTest.kt
Skal fjerne unødvendige toggles: 
- vilkaar-gjenruk (Denne har vært true veldig lenge og trengs ikke)
- revurder-g-omregning-hopp-over-valider-tidligere-vedtaks (Denne har aldri vært skrudd på, slik jeg ser det - og kan følgelig fjernes "as is")
- kast-feil-hvis-oppgave-mangler-pa-apen-behandling (Denne har vært true siden vi begynte å kjøre oppgave-sjekken - og det er fint)
Husk å slette toggles fra unleash etter deploy!
=> Rydd toggles

src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringService.kt, src/main/kotlin/no/nav/familie/ef/sak/journalføring/dto/JournalføringRequest.kt, src/test/kotlin/no/nav/familie/ef/sak/journalføring/JournalføringServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/BehandlingRepositoryTest.kt
Skal sette behandlingsstatus til UTREDES og behandlingssteg til BEREGNE_YTELSE dersom journalføringen tilsier at vilkår blir kopiert. Uten dette vil saksbehandler ikke kunne velge Innvilgelse/avslag/opphør uten å først endre på et vilkår - dét er bakvendtland :) 
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-15345)
=> Oppdater behandlingsstatus og steg ved journalføring når vilkår kopieres

src/main/kotlin/no/nav/familie/ef/sak/vedtak/domain/Vedtak.kt, src/test/kotlin/no/nav/familie/ef/sak/api/gui/VedtakControllerTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakStegTest.kt
Ønsker at avslagsgrunn ikke skal ha totrinnskontroll, har derfor fjernet dette.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-15340
=> Avslagsgrunn kortvarig avbrudd jobb

pom.xml, src/main/kotlin/no/nav/familie/ef/sak/behandling/Saksbehandling.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/ÅrsakRevurderingServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/BeslutteVedtakStegTest.kt
Ønsker et nytt alternativ når saksbehandler kun skal registrere vedtak hvor bruker har fått vedtak fra KS, uten å sende brev.
Frontend: https://github.com/navikt/familie-ef-sak-frontend/pull/2528
Kontrakter: https://github.com/navikt/familie-kontrakter/pull/834
Favro:https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-15499
=> Alternativ revurdering iverksette ka vedtak uten brev

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
Ønsker å kunne bruke toggle for alternativ til revurdering ka vedtak uten brev.
=> Toggle ka vedtak årsak

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/CustonUnleashStrategies.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt, src/test/kotlin/ApplicationLocalPostgres.kt, src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/FeatureToggleMock.kt, src/test/resources/application-integrasjonstest.yaml, src/test/resources/application-local.yml
Trenger å rette på konfigurasjon ifm mocking av Unleash Next. Legger til en negering av profile i faktisk FeatureToggleConfig. Bedre forslag til hvordan vi kan bønne opp kun defaultUnleashService i FeatureToggleMock ? 
Update : Å bønne opp UnleashService i FeatureToggleConfig blir jo feil, siden dette skal gjøres i felles. Det er jo litt av poenget. Fjerner derfor det meste av configen, utenom strategies.
=> Retter på local config ifm Unleash Next

src/main/kotlin/no/nav/familie/ef/sak/sigrun/SigrunService.kt, src/test/kotlin/no/nav/familie/ef/sak/sigrun/SigrunServiceTest.kt
Det viser seg at skatteetaten ikke tilbyr data lenger tilbake enn til 2017 😞 
https://nav-it.slack.com/archives/C01087QRJ2U/p1695982975164769
=> Bare hent inntekt tilbake til 2017

.github/dependabot.yml
Samler alle oppdateringer av avhengigheter i en PR
=> Grupperer dependabot PRs

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/VedtakController.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/VedtakService.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/BehandlingRepositoryTest.kt
Det er ønskelig for saksbehandlere å se på inntektsuttrekk som går over 3 mnd. Det er personhendelse som bruker dette endepunktet: https://github.com/navikt/familie-ef-personhendelse/pull/441
Det er ikke lagd favro-oppgave på dette.
=> Returner inntekt tre måneder tilbake for personhendelse

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/VedtakController.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/VedtakService.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/BehandlingRepositoryTest.kt
Skal gjøre et nytt uttrekk med to måneder bare og med beløp. Burde egentlig gjort antall måneder tilbake til en parameter, men har litt dårlig tid til å fikse det ordentlig til møtet i morgen, så gjør bare en revert enn sålenge. Fikser det så fort det blir tid.
Hører til denne: https://github.com/navikt/familie-ef-personhendelse/pull/442
=> Reverter forrige endring fordi det skal kjøres nytt inntektsuttrekk på 2 måneder med beløp

src/main/kotlin/no/nav/familie/ef/sak/beregning/Beregning.kt, src/main/kotlin/no/nav/familie/ef/sak/beregning/BeregningController.kt, src/main/kotlin/no/nav/familie/ef/sak/beregning/BeregningService.kt
Har laget et endepunkt for å hente grunnbeløp. Det er for å minimere antall stedet vi må lagre og oppdatere grunnbeløp. Nå er det kun behov for å oppdatere det i ef-sak, vi kan derfor slutte å gjøre det i ef-sak-frontend og Sanity. Noe som også kan bidra til mindre feil i fremtiden hvis vi glemmer å oppdatere disse.
Frontend: https://github.com/navikt/familie-ef-sak-frontend/pull/2587
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-14507
=> Dynamisk g vedtaksbrev

src/main/kotlin/no/nav/familie/ef/sak/behandling/RevurderingService.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/RevurderingsController.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/dto/RevurderingDto.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
Skal kunne ha papirsøknad og terminbarn på manuelle revurderinger.
Dersom noen har fått et barn siden sist, men journalføringen går skeis så skal det være mulig å etterregistrere dette barnet før det blir født og registrert i PDL.
Henger sammen med https://github.com/navikt/familie-ef-sak-frontend/pull/2602 og [Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-15806)
=> Papirsøknad + Terminbarn på manuelle revurderinger

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/VedtakController.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/BehandlingRepositoryTest.kt
Det er stadig behov for å endre hvor langt tilbake inntektsuttrekket skal gå. Parameteriserer antall måneder slik at det ikke er nødvendig å endre ef-sak hver gang det skal endres.
=> Send inn antall måneder som parameter for finnPersonerMedAktivStonadIkkeRevurdertSisteMåneder

pom.xml, src/main/kotlin/no/nav/familie/ef/sak/behandling/BarnController.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/NyeBarnService.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/NyeBarnServiceIntegrationTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/NyeBarnServiceTest.kt
Det er behov for å opprette en oppgave av typen "VurderLivshendelse" hvis et barn blir født i måneden etter oppgitt terminmåned. Utleder derfor barn som blir født i måneden etter som familie-ef-personhendelse mottar og oppretter oppgave av : https://github.com/navikt/familie-ef-personhendelse/pull/449
Testet / verifisert ok i preprod. 
Favro : https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-15812
=> Oppgave for barn født i måneden etter oppgitt terminmåned

src/main/kotlin/no/nav/familie/ef/sak/vilkår/dto/TidligereVedtaksperioderDto.kt
Trenger å vise om det er overlapp mellom tidligere vedtaksperioder for barnetilsyn og tidligere perioder for overgangsstønad. Fortsettelse av: https://github.com/navikt/familie-ef-sak/pull/2456
PR i ef-sak-frontend: https://github.com/navikt/familie-ef-sak-frontend/pull/2661
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-16910
=> Overlapp mellom tidligere barnetilsynsperioder og tidligere overgangsstønadsperioder

src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveController.kt
Vi prøver å hente oppgave for ferdigstilte behandlinger - da finner vi ingen oppgave. Dette er kanskje unødvendig, men ikke "feil". Fjerner warning logging.
=> Vil fjerne falske positive warnings (på alle ferdigstilte behandlinger)

src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/BeregningBarnetilsynUtil.kt, src/test/kotlin/no/nav/familie/ef/sak/service/RevurderingServiceIntegrationTest.kt
Nye satser for barnetilsyn. Denne PRen skal merges etter uttrekk av personer som skal revurderes pga satsendringene.
Ref rutine for satsendring: 
https://github.com/navikt/familie-ef-sak/blob/master/doc/BarnetilsynSatsendring_README.md
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-16102
=> Nye satser for barnetilsyn i 2024

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy-unleash-api-token-preprod.yaml, .github/workflows/deploy-unleash-api-token-prod.yaml
---
"For å slippe å ha skumle nøkler med lang levetid i omløp (...)" -> https://nav-it.slack.com/archives/C01DE3M9YBV/p1702893023861639
---
Vil deploye uten secrets.NAIS_DEPLOY_APIKEY
Se mer info: https://doc.nais.io/deployment/github-action/index.html 
(enablet i console og testet i preprod) 
Testet deploy i dev. 
Gjenstår: slette nøkkel fra repo etter merge.
=> Uten nais deploy api key

.github/tag.sh, .github/workflows/deploy-prod.yml, README.md
=> skal endre default branch name fra master til main

.deploy/preprod.yaml, .deploy/prod.yaml, src/main/kotlin/no/nav/familie/ef/sak/forvaltning/InfotrygdForvaltningController.kt, src/main/kotlin/no/nav/familie/ef/sak/forvaltning/KonsistensavstemmingForvaltningController.kt, src/main/kotlin/no/nav/familie/ef/sak/forvaltning/MinsideForvaltningsController.kt, src/main/kotlin/no/nav/familie/ef/sak/forvaltning/OppgaveforvaltningsController.kt, src/main/kotlin/no/nav/familie/ef/sak/infotrygd/InfotrygdController.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/config/RolleConfig.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/sikkerhet/SikkerhetContext.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/sikkerhet/TilgangService.kt, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/kotlin/no/nav/familie/ef/sak/service/TilgangServiceTest.kt, src/test/resources/application-local.yml
Ønsker å bruke forvalterrolle for å autentisere kall mot forvaltningsendepunkt. Fjerner bruk av toggle for å gjøre dette. 
Flytter også endepunkt "infotrygd-rapport" til forvaltnings pakke. 
Testet i preprod og lokalt. Fungerer. 
(Del 1 i oppgave : Forenkle autentisering i swagger og bruk swagger for å kjøre forvaltningsoppgaver. ) 
----
Ta kontakt med meg dersom du trenger rolle forvalter-rolle på din bruker i prod, eller en ida-bruker i preprod. Legges til gruppe i portalz:
Preprod: krever trygdeetate-bruker-innlogging
https://portal.azure.com/#view/Microsoft_AAD_IAM/GroupDetailsMenuBlade/~/Properties/groupId/c62e908a-cf20-4ad0-b7b3-3ff6ca4bf38b
Prod: 
https://portal.azure.com/#view/Microsoft_AAD_IAM/GroupDetailsMenuBlade/~/Members/groupId/3d718ae5-f25e-47a4-b4b3-084a97604c1d
=> Legg til forvalterrolle

src/main/kotlin/no/nav/familie/ef/sak/beregning/barnetilsyn/satsendring/BarnetilsynSatsendringScheduler.kt
Det blir opprettet tasker i prod som feiler og som ikke skal kjøres.
=> Deaktiverer scheduler for barnetilsyn satsendring da det er uført for 2024

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingRepository.kt
Det vil ikke resultere i noen ny behandling (revurdering / tilbakekreving) for de som ikke får noe utbetalt.
=> Inntektskontroll: Filtrerer bort brukere uten utbetalingsbeløp

src/main/kotlin/no/nav/familie/ef/sak/vilkår/regler/vilkår/OppholdINorgeRegel.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/regler/vilkår/ForutgåendeMedlemskapTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/regler/vilkår/OppholdINorgeRegelTest.kt, src/test/kotlin/no/nav/familie/ef/sak/vilkår/regler/vilkår/VilkårGrunnlagTestUtil.kt
- Skal automatisk vurdere inngangsvilkår for opphold når:
- Digital søknad
- Bruker har svart JA på spørsmålet "Oppholder du og barnet/barna dere i Norge?" i søknaden
- Bruker og alle barn må ha Personstatus "Bosatt"
- Bruker mye av det samme testoppsettet som forutgående medlemskap, har derfor lagt funksjoner i en utilsfil som begge bruker, for å ikke gjenta koden.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-18498)
=> Automatisk vurdering av vilkår om opphold i Norge

src/test/kotlin/no/nav/familie/ef/sak/behandling/MigreringServiceTest.kt
Kan ikke migrere dersom periode er mer enn 3 år gammel, og til og med dato kan ikke være lavere enn fra og med dato i periode.
=> Fikser tester som feilet grunnet månedsskifte. Endret datoer i testdata.

src/main/kotlin/no/nav/familie/ef/sak/iverksett/oppgaveterminbarn/ForberedOppgaverTerminbarnService.kt
Det er feil i prod, hvor det er problemer med å lagre oppgave for ugyldig terminbarn fordi det finnes flere ugyldige terminbarn på en behandling. Det feiler med at man ikke får lagret duplikat task. Det holder å lage en oppgave pr person, selv om vedkommende har flere barn med ugyldige terminbarn.
Etter å ha snakket med Mirja er dette et symptom på et annet problem for saksbehandler har opprettet terminbarn tilbake i tid i stedet for at de har rekvirert d-nummer på barna. Tror ikke alle saksbehandlere har tilgang til å gjøre dette i dag, så Mirja og Lars skal ta det opp med avdelingsledere.
=> Håndter at det kan finnes flere ugyldige terminbarn per behandling

pom.xml, src/main/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapper.kt, src/test/kotlin/no/nav/familie/ef/sak/beregning/OmregningServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapperTest.kt, src/test/resources/omregning/expectedIverksettDto.json
Datavarehus (behandlingsstatistikk) ønsker at det også sendes hendelser ved g-omregning. 
Løser dette med en egen task i iverksett. Manglet info om ekstern id for forrige behandling i iverksett, så sender dette over til iverksett. 
[Tilhørende PR i iverksett](https://github.com/navikt/familie-ef-iverksett/pull/916)
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-17409)
=> Sender med forrige ekstern id til iverksett slik at det kan sendes til behandlingsstatistikk

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
Featuretoggle som skal tas i bruk i frontend som skal vise valg om å automatisk behandle tilbakekreving dersom simulering gir feilutbetaling lavere enn 4x rettsgebyr.
=> Featuretoggle for automatisk behandling av tilbakekreving under 4x rettsgebyr

src/main/kotlin/no/nav/familie/ef/sak/kontantstøtte/KontantstøtteClient.kt, src/test/kotlin/no/nav/familie/ef/sak/kontantstøtte/KontantstøtteClientTest.kt
Bugfix: Vil håndtere null-perioder på tom-infotrygdperioder.
Setter også ks-sakperioder (toMåned) til nullable (samme som brukt i ks-sak endepunkt).
=> Bugfix: Vil håndtere null-perioder på tom-infotrygdperioder.

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/sikkerhet/SikkerhetContext.kt, src/main/kotlin/no/nav/familie/ef/sak/journalføring/JournalpostClient.kt, src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveClient.kt, src/main/kotlin/no/nav/familie/ef/sak/oppgave/TilordnetRessursService.kt, src/test/kotlin/no/nav/familie/ef/sak/felles/integration/JournalpostClientTest.kt, src/test/kotlin/no/nav/familie/ef/sak/oppgave/TilordnetRessursServiceTest.kt
Når vi sjekker om vi skal gjøre kall mot oppgave og arkiv (journalpost), noe vi ikke ønsker å gjøre dersom det er utviklere som bruker systemet, sjekker vi også at innlogget bruker har en rolle i ef-sak. Det er ikke nødvendig å sjekke dette her og kan være med på å gjøre koden vanskeligere å lese. 
Ønsker derfor å fjerne "erSaksnehandler" koden (som også er deprecated). Det blir da tydeligere at vi ikke gjør kall mot oppgaver/journalposter hvis innlogget bruker er på liste (unleash) over brukere som ikke skal forsøke å hente slikt.
=> Ta bort ersaksbehandler deprecated

.github/workflows/delete_packages.yml
Dispatch sletter 100 ved hver kjøring. Det tar lang tid å gjøre manuelt. workflow_dispatch er testet og ser ut til å virke fint.
Vil derfor kjøre denne: 
So, 0 2-5 * * * means "At 00 minutes past the hour, at 2 AM, 3 AM, 4 AM, and 5 AM, every day".
=> Legg til schedule i workflow for å slette gamle images:

src/main/kotlin/no/nav/familie/ef/sak/simulering/SimuleringService.kt, src/main/kotlin/no/nav/familie/ef/sak/tilbakekreving/TilbakekrevingOppryddingService.kt, src/test/kotlin/no/nav/familie/ef/sak/iverksett/SimuleringServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/tilbakekreving/TilbakekrevingOppryddingServiceTest.kt
Vil slette tilbakekrevingsvalg dersom vi i 
1. nyeste simulering ikke har noen feilutbetaling, eller 
2. dersom beløp i gammel/ny er forskjellig og tilbakekrevingsvalg er "automatisk behandle under fire rettsgebyr".
Dersom vi ikke sletter tilbakekrevingsvalg kan to ting skje: 
1. Vi gjør et valg - "under 4 rg". Går tilbake til vedtak. Endrer så det blir større feilutbetaling. Resultat: vi kan nå gå videre fra simuleringsfanen uten å gjøre noe simulieringsvalg. Dette valget vises ikke da det ikke skal være mulig å opprette tilbakekreving med dette valget dersom beløpet er høyere enn 4rg. 
2. Dersom vi i "nyeste simulering" ikke får feilutbetalig vil vi fortsatt sende tilbakekrevings(valg) videre til iverksetting. Dette vil ikke føre til noen feil, men det logges mye og historikk på …
=> Vil slette tilbakekrevingsvalg hvis urelevant

src/main/kotlin/no/nav/familie/ef/sak/tilbakekreving/TilbakekrevingController.kt, src/main/kotlin/no/nav/familie/ef/sak/tilbakekreving/TilbakekrevingRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/tilbakekreving/TilbakekrevingService.kt, src/test/kotlin/no/nav/familie/ef/sak/infrastruktur/config/PdlClientConfig.kt, src/test/kotlin/no/nav/familie/ef/sak/service/FagsakServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/tilbakekreving/TilbakekrevingRepositoryTest.kt
Det er ønskelig at det vises en warning dersom bruker har flere behandlinger som det er gjort et tilbakekrevingsvalg på det siste året, ved feilutbetalinger under 4x rettsgebyr, for å gi en heads-up til saksbehandler at det burde vurderes om behandlingen kan/burde behandles automatisk.
[Link til frontend-PR](https://github.com/navikt/familie-ef-sak-frontend/pull/2788)
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-20869)
=> Endepunkt for sjekk på om det finnes flere tilbakekrevinger siste året ved feilutbetalinger under 4x rettsgebyr

src/main/kotlin/no/nav/familie/ef/sak/tilbakekreving/TilbakekrevingController.kt
Får feil i prod om at ressurs/endepunkt ikke finnes: `api/tilbakekreving/behandlinger/2b4d7e04-67b4-401e-8ad1-42a43321e30c/finnesFlereTilbakekrevingerValgtSiste%C3%85r`
Antar at dette har noe å gjøre med å i url, så erstatter denne med aa. Bare litt rart at det virker i preprod.
Slack-tråd: https://nav-it.slack.com/archives/C033WGAFAQ1/p1718262462032289
=> Fjerner å fra url og gjør om til standard url format for ef-sak

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt, src/main/kotlin/no/nav/familie/ef/sak/oppgave/TilordnetRessursService.kt, src/test/kotlin/no/nav/familie/ef/sak/oppgave/TilordnetRessursServiceTest.kt
Ønsker at hentIkkeFerdigstiltOppgaveForBehandling også skal hente oppgaver hvis de er av typen GodkjenneVedtak slik at en oppgave kan tildeles fra behandling.
Lagt til feature toggle for å vise tildel oppgave på behandling
=> Hente godkjenne vedtak oppgaver

src/main/kotlin/no/nav/familie/ef/sak/behandling/oppgavekontroll/BehandlingsoppgaveService.kt
Synes ikke loggingen var helt entydig på hvilken id som ble skrevet ut, så presiserte teksten litt :)
=> presiserer logging for åpne behandlinger uten tilhørende oppgave

src/main/kotlin/no/nav/familie/ef/sak/simulering/SimuleringService.kt
Debug feil i prod om at saksbehandlere får warning om ulik simuleringsresultat
=> Log simuleringsresultat dersom det er ulikt simuleringsresultat i beslutter-steget

src/main/kotlin/no/nav/familie/ef/sak/simulering/SimuleringService.kt, src/test/kotlin/no/nav/familie/ef/sak/iverksett/SimuleringControllerTest.kt, src/test/kotlin/no/nav/familie/ef/sak/iverksett/SimuleringServiceTest.kt
Dette blir feil rundt utbetalingsdato for gjeldende måned. Det som var en vanlig ny utbetaling blir i ny simulering en etterbetaling
=> Ikke ta med etterbetaling i sjekk på om simuleringsresultat er ulikt

.deploy/preprod.yaml
Endringer i nais-validering av sqlInstances config. Feilmelding ved deploy (preprod) 
Error: Status: failure: nais.io/v1alpha1, Kind=Application, Namespace=teamfamilie, Name=familie-ef-sak: updating resource: Application.nais.io "familie-ef-sak" is invalid: [spec.gcp.sqlInstances[0].tier: Required value, : Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation] (total of 1 errors)
Setter til tidligere defaultverdi: db-f1-micro
=> Validering av tier - kan ikke være null

src/main/kotlin/no/nav/familie/ef/sak/beregning/Beregning.kt, src/main/kotlin/no/nav/familie/ef/sak/beregning/BeregningService.kt, src/test/kotlin/no/nav/familie/ef/sak/beregning/BeregningServiceTest.kt
Bruker ikke perMnd fra grunnbeløp for å gjøre utregning av seksGangerGrunnbeløpPerMåned da det kan bli feil utregning når beløpet er rundet ned. Gjør derfor utregning på grunnbeløp.
=> Fix seks g per mnd

src/main/kotlin/no/nav/familie/ef/sak/behandling/TestSaksbehandlingController.kt, src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveService.kt, src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveUtil.kt, src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/task/OpprettOppgaveTaskTest.kt, src/test/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveUtilTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/OppgaveServiceTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-22077
Ending av oppgavebeskrivelse: 
Oppgavebenk
Gosys:
**Forslag til oppgavebeskrivelse når vi oppretter oppgaver:**
Tidligere/nå :grimacing::
Opprinnelig oppgave er feilregistrert. For å kunne utføre behandling har det blitt opprettet en ny oppgave.
----- Opprettet av familie-ef-sak 2024-08-28T11:14 03.817774878 ---
https://ensligmorellerfar.intern.dev.nav.no/oppgavebenk
----- Oppgave må behandles i ny løsning
Forslag:
--- 28.08.2024 11:57 opprettet --- 
Tekst vi legger til her
(Evt en oppgave uten "ekstra tekst: " )
--- 28.08.2024 11:57 opprettet --- 
**Når gosys legger på historikk:
--- 28.08.2024 11:37 F_Z992991 E_Z992991 (Z992991, 1871) ---
Oppgaven er flyttet fra enhet 4489 til 1871, fra …
=> Vil fjerne unødvendig beskrivelse på oppgaver vi oppretter

pom.xml, src/main/kotlin/no/nav/familie/ef/sak/ekstern/EksternStønadsperioderController.kt, src/main/kotlin/no/nav/familie/ef/sak/ekstern/stønadsperiode/EksternStønadsperioderService.kt, src/main/kotlin/no/nav/familie/ef/sak/ekstern/stønadsperiode/util/ArenaPeriodeUtil.kt, src/main/kotlin/no/nav/familie/ef/sak/infotrygd/PeriodeService.kt, src/test/kotlin/no/nav/familie/ef/sak/infotrygd/PeriodeServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt, src/test/kotlin/no/nav/familie/ef/sak/service/EksternStønadsperioderServiceTest.kt
Tilleggstønader trenger å vite om overgangsstønadsperioder og skolepengeperioder for å avgjøre om bruker skal ha deres barnetilsyn-stønad. Henter overgangsstønad fra ef-sak og infotrygd, mens skolepenger bare hentes ut fra ny løsning. Skolepenger-perioden hentes fra vedtak og ikke tilkjent ytelse som følge av behovet til tilleggstønader.
Behov meldt i slack: https://nav-it.slack.com/archives/G012YEK9YQ1/p1724059196190939
Tester i preprod før merge.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-22408)
=> Endepunkt som skal brukes av tilleggsstønader for å hente ut perioder med overgangsstønad og skolepenger

pom.xml, src/main/kotlin/no/nav/familie/ef/sak/ekstern/EksternStønadsperioderController.kt, src/main/kotlin/no/nav/familie/ef/sak/ekstern/stønadsperiode/EksternStønadsperioderService.kt, src/main/kotlin/no/nav/familie/ef/sak/infotrygd/PeriodeService.kt, src/test/kotlin/no/nav/familie/ef/sak/service/EksternStønadsperioderServiceTest.kt
Tilleggsstønader trenger noen ganger barnetilsyn, legger derfor til støtte for å filtrere på stønadstype.
Tilleggstønader er i prod og lar derfor det andre endepunktet leve inntil de har gått over til nytt endepunkt.
=> Endepunkt for tilleggsstønader: Hent perioder for ytelser

src/main/kotlin/no/nav/familie/ef/sak/fagsak/SøkController.kt, src/main/kotlin/no/nav/familie/ef/sak/fagsak/SøkService.kt, src/main/kotlin/no/nav/familie/ef/sak/fagsak/dto/Søkeresultat.kt, src/test/kotlin/no/nav/familie/ef/sak/service/SøkServiceTest.kt
Ønsker å sende med noen ekstra felter i responsen fra kall mot `samme-adresse`.
Feltene skal brukes for å gjøre det enklere å se hvilke personer som er relevante fra "beboer-knappen".
`erSøker` og `erBarn` kan samles til `erAktuelle`, da disse feltene uansett blir behandlet likt i frontend. Tanken var at disse skulle brukes for å enkelt skille søker fra søker sine barn...
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-22526)
=> Ekstra info til beboer-knappen

src/main/kotlin/no/nav/familie/ef/sak/behandling/migrering/InfotrygdPeriodeValideringService.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/migrering/InfotrygdPeriodeValideringServiceTest.kt
Det er ønskelig å opphøre overgangsstønad og barnetilsyn tilbake til 2009 for en person
=> Skal tillate at Mirja migrerer saker tilbake til 2009

src/main/kotlin/no/nav/familie/ef/sak/fagsak/SøkController.kt, src/main/kotlin/no/nav/familie/ef/sak/fagsak/SøkService.kt, src/main/kotlin/no/nav/familie/ef/sak/fagsak/dto/Søkeresultat.kt, src/test/kotlin/no/nav/familie/ef/sak/service/SøkServiceTest.kt
Refaktorert og endret `søkEtterPersonerMedSammeAdresse` til å returnere liste med barn av søker.
[PR Frontend](https://github.com/navikt/familie-ef-sak-frontend/pull/2948)
=> Info på beboer på personopplysninger

.deploy/preprod.yaml, .deploy/prod.yaml, src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/fullmakt/FullmaktClient.kt, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/fullmakt/FullmaktClientTest.kt
Pdl-api har byttet til repr-api, og det er ikke lenge til pdl-api slutter å virke, ref: https://nav-it.slack.com/archives/C020Q1K6EAY/p1732611753116999
Repr-api finnes i gcp og url/scope må byttes til å gå mot gcp i stedet.
Dette må også gjøres for klage. 
Testet OK i preprod.
Vi er gitt tilganger her:
https://github.com/navikt/representasjon/blob/cc057eab93023fb4a3d7b5572b6373b3ec5bc8ea/.nais/prod-gcp/repr-api.yaml
=> Bytt til representasjon-api i gcp

src/main/kotlin/no/nav/familie/ef/sak/vedtak/uttrekk/UttrekkArbeidssøkerService.kt, src/test/kotlin/no/nav/familie/ef/sak/vedtak/uttrekk/UttrekkArbeidssøkerServiceTest.kt
Dette fikser en bug som ble meldt av saksbehandler, hvor noen med opphørt stønad vises. Dersom kjøringen skjer i desember, hvor november skal sjekkes, vil personer med opphørt stønad fra og med desember vises. Denne endringen gjør det slik at de ikke tas med, fordi til og med dato må være større enn siste dato i måneden det sjekkes for (forrige måned).
=> En periode må ha sluttdato større enn siste dato for forrige måned, for at den skal være relevant å ta med i uttrekk

src/main/resources/db/migration/V148__konsistensavstemming_tidsplan_2025.sql
Vi tremger å vite når vi skal kjøre konsistensavstemming. 
Datoer fra PO utbetaling, team Moby : 
https://nav-it.slack.com/archives/C01EH16LAD9/p1732692427434029
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-23441
=> Vil legge inn datoer for konsistensavstemming 2025.

src/main/kotlin/no/nav/familie/ef/sak/vedtak/VedtakController.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/dto/VedtakDto.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-23504)
Validering for å ikke bruke utgåtte avslagsårsaker til lagre vedtak endepunktet.
=> Lagt til validering for sjekk av avslags vedtak hvor utgåtte avslagsårsaker gir feilmelding

.deploy/preprod.yaml, src/main/resources/application-dev.yml
Team Tilbake skal ta over tilbakekrevingsløsningen. Den eksisterende løsningen kjører nå i teamfamilie nais teamet, og for å ta ordentlig eierskap til løsningen og gjøre det til en NAV fellestjeneste ønsker vi å flytte det til et NAIS team som er mer generelt.
=> Ta i bruk tilbakekreving som er flyttet til nytt nais team i preprod

src/main/kotlin/no/nav/familie/ef/sak/selvstendig/NæringsinntektBrukernotifikasjonService.kt, src/main/resources/application.yml
Topic peker nå mot den nye implementasjonen, slik det er eksemplifisert i [migrerings-guide](https://navikt.github.io/tms-dokumentasjon/varsler/migrere/). 
Vi bruker nå `min-side.aapen-brukervarsel-v1`.
=> Brukernotifikasjon topic peker nå mot den nye implementasjonen

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml
Denne PRen prøver å fjerne deprecated work flow variabler fra bygg og deploy taskene. NAIS har satt og `identity_provider` og `project_id` deprecated og skal fjernes, da alle setter de samme verdiene her og utledes derfor automatisk av nais-plattformen nå. Workflows med disse parameterene satt vil ikke lenger virke etter 3. mars.
Oppgaven og beskrivelse kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-24100).
Dette er en av mange PRer der denne samme endringen gjøres for repoer tilhørende enslig-forsørger.
=> Legacy - fjerne deprecated work flow variabler fra build & deploy

.deploy/prod.yaml
Vil skru på auditlogging for familie-ef-sak 
Vil også kjøre : 
$ nais postgres enable-audit familie-ef-sak teamfamilie prod-gcp
Favro: 
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-24266
Se doc: 
https://doc.nais.io/persistence/postgres/how-to/enable-auditing/
=> Vil legge til autitlogging på endringer(write) i database.

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingController.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingService.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/RevurderingController.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/RevurderingService.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/ÅrsakRevurderingService.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/ÅrsakRevurderingsRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SendTilBeslutterSteg.kt, src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/ÅrsakRevurderingSteg.kt, src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/task/BehandlingsstatistikkTask.kt, src/main/kotlin/no/nav/familie/ef/sak/blankett/BlankettService.kt, src/main/kotlin/no/nav/familie/ef/sak/ekstern/EksternBehandlingService.kt, src/main/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapper.kt, src/main/kotlin/no/nav/familie/ef/sak/sigrun/SigrunService.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/BehandlingPåVentServiceIntegrationTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/MigreringServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/ÅrsakRevurderingServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/ÅrsakRevurderingsRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SendTilBeslutterStegTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/ÅrsakRevurderingStegTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandlingsflyt/task/BehandlingsstatistikkTaskTest.kt, src/test/kotlin/no/nav/familie/ef/sak/ekstern/EksternBehandlingControllerTest.kt, src/test/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapperTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/RevurderingServiceIntegrationTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/RevurderingServiceTest.kt
- Controller-metode blir trigget av personhendelse når inntektsendringkontroll er kjørt.
- Flyttet filer i behandling relatert til revurdering i egen pakke.
Dette er første steg for å analysere hvor mange av brukere med 10% endring i inntekt over tre måneder som består gitte kriterier. Se metode `kanAutomatiskRevurderes()` og [Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-23903) for å se hvilke kriterier som er definert opp hittil.
Hører til PR: https://github.com/navikt/familie-ef-personhendelse/pull/576
=> Filtrer ut kandidater til automatisk revurdering etter gitte kriterier. 

src/main/kotlin/no/nav/familie/ef/sak/forvaltning/FerdigstillOppgavetypePåBehandlingTask.kt, src/main/kotlin/no/nav/familie/ef/sak/forvaltning/OppgaveforvaltningsController.kt, src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveService.kt
Ved en feil var det mulig å trykke "Send til beslutter" flere ganger, dette gjorde at 2 oppgaver ble opprettet.
Løser dette med et forvaltningsendepunkt som sender med id på behandling og oppgavetypen, for så å ferdigstille en av de ekstra oppgavene i ef-sak og gosys.
=> Forvaltning controller oppgave

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/UnleashNextService.kt
Når systembruker prøver å gjøre et kall sender vi med en tom map av UnleashContextField verdier da disse ikke blir tatt i bruk.
=> Unleash - empty map for UnleashContextField når bruker er systembruker

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTask.kt
I BehandleAutomatiskInntektsendringTask lagres det ned både ident og ukenummer i payload. Dette må parses ut riktig ved videre bruk av personident.
=> Bugfix: Det lagres ned både personident og ukenummer i payload

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTask.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/RevurderingService.kt, src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/task/BehandlingsstatistikkTask.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTaskTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/RevurderingServiceIntegrationTest.kt, src/test/kotlin/testutil/SøknadHelperService.kt, src/test/kotlin/testutil/VedtakHelperService.kt, src/test/kotlin/testutil/VilkårHelperService.kt
Kopierer vilkår og vedtak fra forrige behandling.
Det som må settes er verdier som er på førstesiden av en revurdering, årsak til revurdering. Se screenshot for preutfylte verdier som settes med denne koden.
I stedet for "Opplysninger fra intern kontroll" skal det settes noe ala "automatisk inntektskontroll", men det må avklares først.
I tillegg skal forventet inntekt og revurderes fra-dato fylles ut automatisk på vedtak og beregning, men dette krever analyse og avklaringer. Derfor kopieres alt over uten endring, inntil videre. 
Dette er fortsatt gjemt bak en featuretoggle. Planen er at det bare skal logges i prod ved neste kjøring.
=> Opprett og initier revurdering for inntektsendring

pom.xml, src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTask.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTaskTest.kt
Mer passende opplysningskilde for behandlinger opprettet ved automatisk sjekk av inntektsendring
=> Byttet opplysningskilde til AUTOMATISK_OPPRETTET_BEHANDLING

src/main/kotlin/no/nav/familie/ef/sak/amelding/InntektResponse.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt
Tilpasse seg funskjonene for utregning av forventet inntekt til den faktiske inntektresponsen vi jobber på. Tar nå hensyn til at det kan være lagt til inntekt for gjeldende måned allerede, som skal filtreres bort. Tar også nå hensyn til lønn tilknyttet en inntektsmåned kan være delt opp og må legges sammen. Filtrerer også nå bort lønn i sammenheng med ytelser tilknyttet ef.
=> Automatisering inntektsendring tilpasse inntektsresponse til data

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingService.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTaskTest.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/DomainUtil.kt
Dette gjøres for å redusere kompleksitet i første mvp.
Etter en rask gjennomgang av forrige kjøring for potensielle kandidater til automatisk revurdering, vil ikke denne begrensningen redusere antallet noe særlig. Det ser ut til at de fleste med stabil inntekt har gjerne kun en vedtak- og inntektsperiode. Neste steg vil være å forbedre det slik at dette ikke er en begrensning, men det ville vært fint å teste at resten av flyten virker slik det er nå.
=> Legger inn en validering på at behandling har kun en vedtak- og inntektsperiode for at den kan revurderes automatisk

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/RevurderingService.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTaskTest.kt
Automatisk inntektsendring: Legger Behandle-sak oppgavene i egen mappe og markerer med egen tekst, da de blir opprette som følge av inntektskontroll den 6. og at det kan være lurt at de samme personene tar tak i disse oppgavene til å starte med.
=> Forbedre behandle-sak oppgaver som blir lagd som følge av automatisk inntektsendring

src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleController.kt, src/main/kotlin/no/nav/familie/ef/sak/infrastruktur/featuretoggle/FeatureToggleService.kt
Gjøre det letter for saksbehandlerer å kopiere feilmelding så vi forhåpentligvis får mindre bilder av feilmeldinger.
=> Lagt til toggle for å vise kopier knapp i alert error

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingService.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingServiceTest.kt
Det er dessverre mye problemer ved kall mot sigrun i preprod.
For å ikke ødelegge for testingen, så featuretoggles kallet for å slippe unødvendige problemer. Det går helt fint å disable dette, da dette kallet kun brukes til å sjekk om bruker har næringsinntekt.
=> Disable kall mot sigrun i inntektskontroll i preprod

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTask.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTaskTest.kt
Setter årsinntekt riktig i behandling som blir automatisk opprettet.
=> Bugfix: Skal sette årsinntekt i riktig felt i ny behandling

src/main/kotlin/no/nav/familie/ef/sak/amelding/InntektResponse.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTask.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/RevurderingService.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingServiceTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTaskTest.kt
For å finne revurderes fra-dato er vi avhengige av at inntektresponse er sortert, lista fra a-inntekt kommer usortert, så hovedendringen er at det legges til sortering. I tillegg tas det høyde for at forrige innvilget behandling sin startdato ved beregning av revurderes fra-dato, slik at det ikke beregnes en dato som er før forrige innvilgelse.
Det ser ut som det er flere endringer enn det faktisk er, fordi jeg har lagt eksisterende kode i egne metode for å forbedre lesbarheten i `BehandleAutomatiskInntektsendringTask`
=> Avgrens revurderes fra dato til med forrige vedtak

src/main/kotlin/no/nav/familie/ef/sak/vedtak/VedtakController.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/BehandlingRepositoryTest.kt
Det krever endring av vedtaksdato i db hver gang en skal teste en ny bruker uten denne endringen.
=> Gjør det enklere å teste inntektskontroll i preprod ved at det ikke må være 3 måneder siden forrige innvilgelse for at testperson blir med

src/main/kotlin/no/nav/familie/ef/sak/samværsavtale/SamværsavtaleService.kt, src/test/kotlin/no/nav/familie/ef/sak/samværsavtale/SamværsavtaleServiceTest.kt
Fra [feil meldt inn på teams](https://teams.microsoft.com/l/message/19:55fb7a15fdad4fb29e568d7dc617b52e@thread.tacv2/1747741024028?tenantId=62366534-1ec3-4962-8869-9b5535279d0b&groupId=11014155-e8a7-46ad-8be0-b5c10a863a36&parentMessageId=1747741024028&teamName=Team%20enslig%20fors%C3%B8rger%20kontinuerlig%20forbedring&channelName=EF%20sak&createdTime=1747741024028)
Når man oppretter en ny behandling vil man først gjenbruke vilkår og samværsavtaler fra nærmeste egnede behandling på **samme** fagsak. Deretter vil man prøve å gjenbruke fra nærmeste egnede behandling **uavhengig** av fagsak. 
På grunn av dette er man ved gjenbruk nødt til å sjekke om samværsavtalen man prøver å gjenbruke har en entitet i databasen fra før. I såfall må vi gjøre en `update` i stedet for `insert`
=> Gjenbruk samvaersavtale fix

.deploy/preprod.yaml, .deploy/prod.yaml, src/main/kotlin/no/nav/familie/ef/sak/amelding/InntektController.kt, src/main/kotlin/no/nav/familie/ef/sak/amelding/ekstern/AMeldingInntektClient.kt, src/main/resources/application.yml
* Skal gå mot ny ingress i stedet for via proxy.
_Inntektskomponenten kjører nå på Nais. Den er tilgjengelig fra både gcp og fss. Må bruke Entra ID, da sts ikke er videreført i nais versjonen av Inntektskomponenten._
=> Ny ingress inntekt

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTask.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingEtterGOmregningTest.kt
Inntektsbegrunnelse skal inneholde en del informasjon om hvordan det er kommet frem til revurderingsdato og forventet inntekt. Malen som er laget her skal oppfylle krav til dette og følger det slik saksbehandler gjør i de vanligste sakene.
=> Fyll ut periodebegrunnelse automatisk

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/RevurderingService.kt
Lager en limit på antall tasker slik at det ikke blir for mange oppgaver som opprettes første gangen. Antakelig ville det ikke vært så veldig mange flere, men bruker dette som en sikring, slik at saksbehandlere ikke får altfor mange automatiske revurderinger til behandling og testing.
=> Limit på antall behandleAutomatiskInntektsendringTask som lagres

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/OpprettAutomatiskRevurderingFraForvaltningTask.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/RevurderingService.kt, src/main/kotlin/no/nav/familie/ef/sak/oppgave/OppgaveService.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingEtterGOmregningTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTaskTest.kt, src/test/kotlin/no/nav/familie/ef/sak/service/RevurderingServiceTest.kt
Det var lagt inn feil mappeId. Denne PR'n sørger for å finne riktig mappe som oppgaven skal knyttes til. Mappen er merket med "63 Inntektskontroll". Det er dessverre skrivefeil i preprod på mappenavnet (Inntekstkontroll) - derfor ble mappenavnet som søkes på "63 Innte" for å få treff i både prod og preprod.
=> Bugfix: Finn inntektsmappe for BehandleSak oppgavene til Automatisk revurdering av inntekt

src/main/kotlin/no/nav/familie/ef/sak/brev/domain/Brevmottakere.kt, src/main/kotlin/no/nav/familie/ef/sak/iverksett/IverksettingDtoMapper.kt
Kan slette ubrukt mottaker roller enum 'FULLMAKT' da den ikke blir sendt med fra frontend lenger 'FULLMEKTIG' brukes i stedet.
=> Slette ubrukt enum mottaker rolle FULLMAKT

src/main/kotlin/no/nav/familie/ef/sak/amelding/InntektResponse.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingService.kt, src/test/kotlin/no/nav/familie/ef/sak/amelding/InntektResponseTest.kt, src/test/resources/json/inntekt/InntektFastlønnMedEnMånedMedKunFeriepenger.json
Skal i første omgang ikke automatisk revurdere tilfeller hvor det er kun feriepenger en måned. Det vanligste er at det er registrert fastlønn i tillegg til feriepenger.
=> Skal ikke ta med feriepenger i beregningen av forventet inntekt.

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml
Forsøker å redusere deploy-tid. Ved deploy til dev kjøres tester og selve deploy i parallell. Det vil si at testene kan feile og allikevel blir det deployet til dev, men det kan se ut til at man kan spare 2-3 min på å gjøre det slik.
Ved deploy til prod kjøres også deploy til dev og enhetstester parallelt, men begge må ha kjørt ferdig uten feil før det deployes til prod. Usikker på hvor mye tid det er å hente her, men vi kan teste om dette hjelper.
=> Forsøk på raskere deploy til dev

src/test/kotlin/no/nav/familie/ef/sak/næringsinntektskontroll/NæringsinntektKontrollServiceTest.kt
Setter dato dynamisk slik at person alltid vil ha innvilget overgangsstønad.
=> Dynamisk dato i andel tilkjent ytelse

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTask.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingEtterGOmregningTest.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTaskTest.kt
Etter tilbakemelding fra fag etter forrige kjøring
=> Liten tekstendring i inntektsbegrunnelse ved automatisk revurdering av inntekt

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTask.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTaskTest.kt
Tekst er forenklet i caser hvor forrige behandling er en G-omregning.
[NAV-25696](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-25696)
=> Rettet tekst i inntektsbegrunnelse etter tilbakemelding fra fag

src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/TidligereVedtaksperioderService.kt, src/test/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/TidligereVedtaksperioderServiceTest.kt
Dette kan skje dersom vi f.eks. prøver å sjekke annen forelder som bare er registrert med NPID og er hentet fra relasjon til barn.
Vi får f.eks ikke opprettet grunlagsdata dersom vi har andre foreldre som kun er registrert med NPID. 
Testet i preprod her: Får etter fiks laget og iverksatt behandling.
https://ensligmorellerfar.ansatt.dev.nav.no/behandling/b8eb8076-7275-45da-9750-54ab0418d7f3/inngangsvilkar
Laget ny favro-oppgave for å fjerne lenker til annen forelder i UI:
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-25735
=> Ikke hent tidligere vedtak hvis folkeregisteridentifikator er tom

src/main/kotlin/no/nav/familie/ef/sak/behandling/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ef/sak/vedtak/VedtakController.kt, src/test/kotlin/no/nav/familie/ef/sak/repository/BehandlingRepositoryTest.kt, src/test/kotlin/testutil/TestoppsettService.kt
Dette gjelder både for opprettelse av oppgaver ved inntektsendring og automatisk revurdering.
Denne endringen filtrerer ut behandlinger som har blitt revurdert rett før g-omregning, altså at vedtakstidspunkt er mindre enn 3 mnd på behandling før g-omregning. Det er linket til en behandling i favro-oppgaven som er et eksempel på hva som vil bli filtrert ut med denne endringen. Denne ble forsøkt automatisk revurdert, men ble henlagt, da den hadde vært revurdert nylig.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-25696
=> Dersom noe er revurdert manuelt siste 3 måneder skal det ikke med i inntektskontrollen

src/main/kotlin/no/nav/familie/ef/sak/behandlingsflyt/steg/SendTilBeslutterSteg.kt, src/main/kotlin/no/nav/familie/ef/sak/oppfølgingsoppgave/OppfølgingsoppgaveService.kt, src/test/kotlin/no/nav/familie/ef/sak/oppfølgingsoppgave/OppfølgingsoppgaveServiceIntegrationTest.kt, src/test/kotlin/no/nav/familie/ef/sak/oppfølgingsoppgave/OppfølgingsoppgaveServiceTest.kt
Litt rydding. Sett ifbm feilsøking av nylig meldt prodfeil, hvor behandlingstatus ble oppdatert uten at resten av koden i `utførSteg` kjørte.
=> Enabler tester som har blitt testet og gjort noe opprydding.

src/main/kotlin/no/nav/familie/ef/sak/amelding/InntektResponse.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTask.kt, src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTaskTest.kt
Implementeres etter ønske fra saksbehandlere. Må testes i preprod og ta en avsjekk med fag om teksten, men dette kan gjøres etter merge.
=> Tar med inntektsbegrunnelse dersom bruker har hatt feriepenge-utbetaling siste 3 måneder, og at det ikke tas med i beregningen av forventet inntekt.

src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingInntektsbegrunnelse.kt, src/main/kotlin/no/nav/familie/ef/sak/behandling/revurdering/BehandleAutomatiskInntektsendringTask.kt
Forsøker å gjøre det lettere å lese koden. Navn på flettefelter skal avklares med fag for å sikre riktig begrepsbruk i fremtiden.
=> Refaktorering: Lager egne flettefelt-klasser for generering av inntektsbegrunnelse

pom.xml
Feilen i nyeste versjon av surefire er diskutert her: https://github.com/cucumber/cucumber-jvm/issues/2984
=> Midlertidig nedgradering av surefire-versjon for at maven skal rapportere byggfeil dersom en cucumber-test feiler.

src/test/kotlin/no/nav/familie/ef/sak/behandling/revurdering/AutomatiskRevurderingEtterGOmregningTest.kt, src/test/kotlin/no/nav/familie/ef/sak/iverksett/oppgaveforbarn/AktivitetspliktigAlderTest.kt, src/test/kotlin/no/nav/familie/ef/sak/iverksett/oppgaveforbarn/BarnFyllerÅrOppfølgingsoppgaveServiceTest.kt, src/test/resources/json/inntekt/InntektResponseØktInntektSamtidigMedGOmregning.json
Vi er akkurat i en periode av året hvor 6 mnd tilbake ikke er mer enn 183 dager, endret derfor test til å bare teste opp mot 6 mnd tilbake.
Når det gjelder inntektstestene skal vi forbedre dette, slik at de virker ved månedsskifte og forhåpentligvis være mer lesbare og forståelige.
=> Rettet tester som feilet som følge av månedsskifte
